var JSX={};
(function(){function zb(a,b,c){Object.defineProperty(a,b,{get:function(){var d=c();delete a[b];return a[b]=d},set:function(c){delete a[b];a[b]=c},enumerable:!0,configurable:!0})}function Gb(){}function pb(){}function sc(){}function rb(){}function tc(){var a,b;this.r=12;this.x=0;this.y=10;this.ax=this.vz=this.vy=this.vx=this.z=0;this.ay=-120;this.az=0;a=Math.cos(0);b=Math.sin(0);this.rot=new Ab(a,b,0*b,0*b);this.radius=8;this.isBraking=!1}function J(){}function hc(){var a=this,b,c,d,e,f,h,g,j,i,k,
l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,B,E,T,V,X,kb,S,K,W,M,lb,Q,mb,N,ub,A,D,C,R,L,G,Bb,P,vb,J,Wa,Xa,Ya,Za,$a,Ja,Ka,La,ab,bb,Oa,cb,Pa,db,ka,la,Qa,Ra,eb,Sa,Da,Ma,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,aa,ba,wa,U,ma,na,xa,oa,ya,ca,da,ga,ha,ia,ja,Y,Z,Aa,Ba,Ca,fb,gb,hb,ib,jb,O;this.trees=this.player=null;this.treeRadius=0;this.items=null;this.totalElapsedMsec=this.itemRadius=0;Qc(["http://murooka.me/project2/image/tree.png","http://murooka.me/project2/image/so-nya.png","http://murooka.me/project2/image/redbull_free.png",
"http://murooka.me/project2/image/sky1.jpg"]);this.isStarted=!1;O=this.engine=new ic("canvas_demo2");O._skyImageSrc="./image/sky1.jpg";O._skyImage=I.images["./image/sky1.jpg"];O._isMobile&&((L=this.engine.camera).farZ=200,L.fovyX=0.7853981633974483,g=L.view,j=L.target,i=L.upper,k=L.fovyX,l=L.nearZ,p=L.farZ,r=L.aspectRatio,t=new m(j.x-g.x,j.y-g.y,j.z-g.z),v=Math.sqrt((G=t.x)*G+(Bb=t.y)*Bb+(P=t.z)*P),q=1E-9>v?new m(0,0,0):t.divSelf$N(v),z=new m((Ya=i.y)*(J=q.z)-(vb=i.z)*(Xa=q.y),vb*(Za=q.x)-(Wa=i.x)*
J,Wa*Xa-Ya*Za),F=Math.sqrt(($a=z.x)*$a+(Ja=z.y)*Ja+(Ka=z.z)*Ka),s=1E-9>F?new m(0,0,0):z.divSelf$N(F),x=new m((cb=q.y)*(ab=s.z)-(La=q.z)*(Oa=s.y),La*(Pa=s.x)-(bb=q.x)*ab,bb*Oa-cb*Pa),y=Math.sqrt((db=x.x)*db+(ka=x.y)*ka+(la=x.z)*la),u=1E-9>y?new m(0,0,0):x.divSelf$N(y),n=new H([Qa=s.x,Ra=s.y,eb=s.z,-(Qa*(Da=g.x)+Ra*(Ea=g.y)+eb*(ea=g.z)),Sa=u.x,Ma=u.y,Fa=u.z,-(Sa*Da+Ma*Ea+Fa*ea),fa=q.x,Ga=q.y,Ha=q.z,-(fa*Da+Ga*Ea+Ha*ea),0,0,0,1]),w=1/Math.tan(k/2),B=w/r,E=p/(p-l),T=-E*l,o=new H([w,0,0,0,0,B,0,0,0,0,
E,T,0,0,1,0]),L.viewMatrix=n,L.projectionMatrix=o,V=(pa=o._m11)*(ta=n._m11)+(qa=o._m12)*(ua=n._m21)+(ra=o._m13)*(va=n._m31)+(sa=o._m14)*(aa=n._m41),X=pa*(wa=n._m12)+qa*(ma=n._m22)+ra*(xa=n._m32)+sa*(ya=n._m42),kb=pa*(ca=n._m13)+qa*(da=n._m23)+ra*(ga=n._m33)+sa*(ha=n._m43),S=pa*(ia=n._m14)+qa*(ja=n._m24)+ra*(Y=n._m34)+sa*(Z=n._m44),K=(ba=o._m21)*ta+(U=o._m22)*ua+(na=o._m23)*va+(oa=o._m24)*aa,W=ba*wa+U*ma+na*xa+oa*ya,M=ba*ca+U*da+na*ga+oa*ha,lb=ba*ia+U*ja+na*Y+oa*Z,Q=(Aa=o._m31)*ta+(Ba=o._m32)*ua+(Ca=
o._m33)*va+(fb=o._m34)*aa,mb=Aa*wa+Ba*ma+Ca*xa+fb*ya,N=Aa*ca+Ba*da+Ca*ga+fb*ha,ub=Aa*ia+Ba*ja+Ca*Y+fb*Z,A=(gb=o._m41)*ta+(hb=o._m42)*ua+(ib=o._m43)*va+(jb=o._m44)*aa,D=gb*wa+hb*ma+ib*xa+jb*ya,C=gb*ca+hb*da+ib*ga+jb*ha,R=gb*ia+hb*ja+ib*Y+jb*Z,L.matrix=new H([V,X,kb,S,K,W,M,lb,Q,mb,N,ub,A,D,C,R]));this.player={r:12,x:0,y:10,z:0,vx:0,vy:0,vz:0,ax:0,ay:-120,az:0,rot:vc(0,1,0,0),radius:8,isBraking:!1};this.trees=new Lb([new m(-271,-3,450),new m(-200,-3,720),new m(139,-3,351),new m(171,-3,254),new m(214,
-3,192),new m(-253,-3,555),new m(29,-3,385),new m(-72,-3,530),new m(96,-3,678),new m(-49,-3,222)]);this.treeRadius=24;this.items=new Lb([new m(149,-10,724),new m(107,-10,483),new m(279,-10,551),new m(-295,-10,261),new m(-16,-10,225),new m(95,-10,165),new m(264,-10,161),new m(-50,-10,325),new m(-169,-10,254),new m(271,-10,401)]);this.itemRadius=8;b=function(b){var c,e,d,f,g,h,i,j,k,l,n,o,p,r,q,s,t,u,v,w,x,y,z,B,E,F,T,V,X,S,kb,K,M,W,Q,lb,mb,N,L,ub,A,D,C,uc,ca,da,ga,ha,ia,ja,Y,Z,ba,U,na,I,pa,qa,ra,sa,
ta,ua,va,aa,wa,ma,xa,oa,ya,R,ea,Aa,Ba,Ca,G,Da,Ea,Fa,fa,Ga,Ha,P,J,Bb,Ma,O,Qb,Oa,Pa,ka,la,Qa,Ra,Sa,vb,Wa,Xa,Ya,Za,$a,Ja,Ka,La;a._updateClearedPlayer$N(b);c=a.player;e=new m(c.x+Math.sin(a.totalElapsedMsec/5E3)*50,c.y+20,c.z+Math.cos(a.totalElapsedMsec/5E3)*50);d=new m(c.x,c.y,c.z);(N=a.engine.camera).target=d;N.view=e;f=N.view;g=N.target;h=N.upper;i=N.fovyX;j=N.nearZ;k=N.farZ;l=N.aspectRatio;s=new m(g.x-f.x,g.y-f.y,g.z-f.z);t=Math.sqrt((L=s.x)*L+(ub=s.y)*ub+(A=s.z)*A);p=t<1E-9?new m(0,0,0):s.divSelf$N(t);
u=new m((da=h.y)*(C=p.z)-(D=h.z)*(ca=p.y),D*(ga=p.x)-(uc=h.x)*C,uc*ca-da*ga);v=Math.sqrt((ha=u.x)*ha+(ia=u.y)*ia+(ja=u.z)*ja);r=v<1E-9?new m(0,0,0):u.divSelf$N(v);w=new m((na=p.y)*(Z=r.z)-(Y=p.z)*(U=r.y),Y*(I=r.x)-(ba=p.x)*Z,ba*U-na*I);x=Math.sqrt((pa=w.x)*pa+(qa=w.y)*qa+(ra=w.z)*ra);q=x<1E-9?new m(0,0,0):w.divSelf$N(x);n=new H([sa=r.x,ta=r.y,ua=r.z,-(sa*(aa=f.x)+ta*(ma=f.y)+ua*(oa=f.z)),va=q.x,wa=q.y,xa=q.z,-(va*aa+wa*ma+xa*oa),ya=p.x,R=p.y,ea=p.z,-(ya*aa+R*ma+ea*oa),0,0,0,1]);y=1/Math.tan(i/2);
z=y/l;B=k/(k-j);o=new H([y,0,0,0,0,z,0,0,0,0,B,-B*j,0,0,1,0]);N.viewMatrix=n;N.projectionMatrix=o;E=(Aa=o._m11)*(Da=n._m11)+(Ba=o._m12)*(Ea=n._m21)+(Ca=o._m13)*(Fa=n._m31)+(G=o._m14)*(fa=n._m41);F=Aa*(Ha=n._m12)+Ba*(J=n._m22)+Ca*(Ma=n._m32)+G*(Qb=n._m42);T=Aa*(Oa=n._m13)+Ba*(Pa=n._m23)+Ca*(ka=n._m33)+G*(la=n._m43);V=Aa*(Qa=n._m14)+Ba*(Ra=n._m24)+Ca*(Sa=n._m34)+G*(vb=n._m44);X=(Ga=o._m21)*Da+(P=o._m22)*Ea+(Bb=o._m23)*Fa+(O=o._m24)*fa;S=Ga*Ha+P*J+Bb*Ma+O*Qb;kb=Ga*Oa+P*Pa+Bb*ka+O*la;K=Ga*Qa+P*Ra+Bb*
Sa+O*vb;M=(Wa=o._m31)*Da+(Xa=o._m32)*Ea+(Ya=o._m33)*Fa+(Za=o._m34)*fa;W=Wa*Ha+Xa*J+Ya*Ma+Za*Qb;Q=Wa*Oa+Xa*Pa+Ya*ka+Za*la;lb=Wa*Qa+Xa*Ra+Ya*Sa+Za*vb;mb=($a=o._m41)*Da+(Ja=o._m42)*Ea+(Ka=o._m43)*Fa+(La=o._m44)*fa;N.matrix=new H([E,F,T,V,X,S,kb,K,M,W,Q,lb,mb,$a*Ha+Ja*J+Ka*Ma+La*Qb,$a*Oa+Ja*Pa+Ka*ka+La*la,$a*Qa+Ja*Ra+Ka*Sa+La*vb])};c=function(b){a._checkCollisionWithFloor$N(b);a._checkCollisionWithTrees$();a._checkCollisionWithItems$();a._updateViewpoint$()};d=function(b){a._renderPlayer$LContext3D$(b);
a._renderField$LContext3D$(b)};e=function(b){a._renderPlayer$LContext3D$(b);a._renderTrees$LContext3D$(b);a._renderItems$LContext3D$(b);a._renderField$LContext3D$(b)};f=!1;this.engine.onUpdate=function(g){var h,i,j;if(a.isStarted){if(a.player.y<-1E3){a.player={r:12,x:0,y:10,z:0,vx:0,vy:0,vz:0,ax:0,ay:-120,az:0,rot:vc(0,1,0,0),radius:8,isBraking:false};a.isStarted=false}if(!f&&1050<=(h=(i=a.player).x)&&h<=1110&&1350<=(j=i.z)&&j<=1410){c=b;e=d;f=true}c(g)}};h=new za(90,135,150);this.engine.onRender=
function(b,c){a.totalElapsedMsec=a.totalElapsedMsec+c;b.backgroundColor=h;e(b)};this.engine._isMobile?this._setMobileOperation$():this._setPCOperation$()}function $b(){}function yc(){}function D(){}function m(a,b,c){this.x=a;this.y=b;this.z=c;this.w=1}function R(a,b,c,d){a=this.x=a/d;this.y=b/d;this.z=c/d;this.w=1;NaN===a&&console.log(d)}function zc(a){this.x=a.x;this.y=a.y;this.z=a.z;this.w=1}function O(){}function Cb(){this._m11=1;this._m21=this._m14=this._m13=this._m12=0;this._m22=1;this._m32=
this._m31=this._m24=this._m23=0;this._m33=1;this._m43=this._m42=this._m41=this._m34=0;this._m44=1}function H(a){this._m11=a[0];this._m12=a[1];this._m13=a[2];this._m14=a[3];this._m21=a[4];this._m22=a[5];this._m23=a[6];this._m24=a[7];this._m31=a[8];this._m32=a[9];this._m33=a[10];this._m34=a[11];this._m41=a[12];this._m42=a[13];this._m43=a[14];this._m44=a[15]}function $(){}function Ac(a,b){this.t=a;this.x=b.x;this.y=b.y;this.z=b.z}function Bc(a){this.t=0;this.x=a.x;this.y=a.y;this.z=a.z}function Ab(a,
b,c,d){this.t=a;this.x=b;this.y=c;this.z=d}function I(){}function ic(a){var b,c,d,e,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,B,E,T,V,X,kb,S,K,W,M,lb,Q,mb,N,ub,A,D,C,I,L,R,G,J,O,za,Wa,Xa,Ya,Za,$a,Ja,Ka,La,ab,bb,Oa,cb,Pa,db,ka,la,Qa,Ra,eb,Sa,Da,Ma,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,aa,ba,wa,U,ma,na,xa,oa,ya,ca,da,ga,ha,ia,ja,Y,Z,Aa,Ba,Ca,fb,gb,hb,ib,jb,$,Ia,Na,Ta,Ua,sb,Va,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb;this._skyImage=this._skyImageSrc=this.onRender=this.onUpdate=this.screenMatrix=this.camera=null;
this._isRunning=!1;b=P.window.navigator.userAgent;this._isMobile=/iPhone/.test(b)||/Android/.test(b);var jc,wc=P.document.getElementById(a);jc=wc instanceof HTMLElement?wc:null;c=jc instanceof HTMLCanvasElement?jc:null;var xc=c.getContext("2d");this.context=xc instanceof CanvasRenderingContext2D?xc:null;Oa=this._width=c.width;h=this._height=c.height;g=new H([1,0,0,Oa/2,0,1,0,h/2,0,0,1,0,0,0,0,1]);y=Oa/2;w=-h/2;j=g._m11;i=g._m12;k=g._m13;l=g._m14;p=g._m21;r=g._m22;n=g._m23;o=g._m24;q=g._m31;s=g._m32;
u=g._m33;t=g._m34;v=g._m41;z=g._m42;F=g._m43;x=g._m44;g._m11=j*y+0*i+0*k+0*l;g._m12=0*j+i*w+0*k+0*l;g._m13=0*j+0*i+1*k+0*l;g._m14=0*j+0*i+0*k+1*l;g._m21=p*y+0*r+0*n+0*o;g._m22=0*p+r*w+0*n+0*o;g._m23=0*p+0*r+1*n+0*o;g._m24=0*p+0*r+0*n+1*o;g._m31=q*y+0*s+0*u+0*t;g._m32=0*q+s*w+0*u+0*t;g._m33=0*q+0*s+1*u+0*t;g._m34=0*q+0*s+0*u+1*t;g._m41=v*y+0*z+0*F+0*x;g._m42=0*v+z*w+0*F+0*x;g._m43=0*v+0*z+1*F+0*x;g._m44=0*v+0*z+0*F+1*x;this.screenMatrix=g;this._skyImage=this._skyImageSrc=null;this._isRunning=!1;d=
new m(0,0,-90);e=new m(0,0,0);f=new m(0,1,0);B=this.camera=new kc(d,e,f,1.0471975511965976,0,500,this._height/this._width);E=B.view;T=B.target;V=B.upper;X=B.fovyX;kb=B.nearZ;S=B.farZ;K=B.aspectRatio;N=new m(T.x-E.x,T.y-E.y,T.z-E.z);ub=Math.sqrt((cb=N.x)*cb+(Pa=N.y)*Pa+(db=N.z)*db);lb=1E-9>ub?new m(0,0,0):N.divSelf$N(ub);A=new m((eb=V.y)*(la=lb.z)-(ka=V.z)*(Ra=lb.y),ka*(Sa=lb.x)-(Qa=V.x)*la,Qa*Ra-eb*Sa);D=Math.sqrt((Da=A.x)*Da+(Ma=A.y)*Ma+(Ea=A.z)*Ea);Q=1E-9>D?new m(0,0,0):A.divSelf$N(D);C=new m((Ha=
lb.y)*(ea=Q.z)-(Fa=lb.z)*(Ga=Q.y),Fa*(pa=Q.x)-(fa=lb.x)*ea,fa*Ga-Ha*pa);I=Math.sqrt((qa=C.x)*qa+(ra=C.y)*ra+(sa=C.z)*sa);mb=1E-9>I?new m(0,0,0):C.divSelf$N(I);W=new H([ta=Q.x,ua=Q.y,va=Q.z,-(ta*(ba=E.x)+ua*(U=E.y)+va*(na=E.z)),aa=mb.x,wa=mb.y,ma=mb.z,-(aa*ba+wa*U+ma*na),xa=lb.x,oa=lb.y,ya=lb.z,-(xa*ba+oa*U+ya*na),0,0,0,1]);L=1/Math.tan(X/2);R=L/K;G=S/(S-kb);M=new H([L,0,0,0,0,R,0,0,0,0,G,-G*kb,0,0,1,0]);B.viewMatrix=W;B.projectionMatrix=M;J=(ca=M._m11)*(ia=W._m11)+(da=M._m12)*(ja=W._m21)+(ga=M._m13)*
(Y=W._m31)+(ha=M._m14)*(Z=W._m41);O=ca*(Ba=W._m12)+da*(fb=W._m22)+ga*(hb=W._m32)+ha*(jb=W._m42);za=ca*($=W._m13)+da*(Ia=W._m23)+ga*(Na=W._m33)+ha*(Ta=W._m43);Wa=ca*(Ua=W._m14)+da*(sb=W._m24)+ga*(Va=W._m34)+ha*(Rb=W._m44);Xa=(Aa=M._m21)*ia+(Ca=M._m22)*ja+(gb=M._m23)*Y+(ib=M._m24)*Z;Ya=Aa*Ba+Ca*fb+gb*hb+ib*jb;Za=Aa*$+Ca*Ia+gb*Na+ib*Ta;$a=Aa*Ua+Ca*sb+gb*Va+ib*Rb;Ja=(Sb=M._m31)*ia+(Tb=M._m32)*ja+(Ub=M._m33)*Y+(Vb=M._m34)*Z;Ka=Sb*Ba+Tb*fb+Ub*hb+Vb*jb;La=Sb*$+Tb*Ia+Ub*Na+Vb*Ta;ab=Sb*Ua+Tb*sb+Ub*Va+Vb*Rb;
bb=(Wb=M._m41)*ia+(Xb=M._m42)*ja+(Yb=M._m43)*Y+(Zb=M._m44)*Z;B.matrix=new H([J,O,za,Wa,Xa,Ya,Za,$a,Ja,Ka,La,ab,bb,Wb*Ba+Xb*fb+Yb*hb+Zb*jb,Wb*$+Xb*Ia+Yb*Na+Zb*Ta,Wb*Ua+Xb*sb+Yb*Va+Zb*Rb])}function C(){}function Cc(a){this._groupCenter=this._polygonList=null;this._ignoringZHidden=!1;this._worldMatrix=new Cb;this._matrixStack=new lc;this.camera=a;this._depth=3;this.modelList1=new nb;this.modelList2=new nb;this.modelList3=new nb;this.modelList4=new nb;this.modelList5=new nb;this.backgroundColor=new za(90,
135,158)}function Ib(){}function kc(a,b,c,d,e,f,h){var g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,B,E,T,V,X,kb,S,K,W,M,A,Q,mb,N,ub,C,D,I,R,L,G,J,O,P,$,Wa,Xa,Ya,Za,$a,Ja,Ka,La,ab,bb,Oa,cb,Pa,db,ka,la,Qa,Ra,eb,Sa,Da,Ma,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,aa,ba,wa,U,ma,na,xa,oa,ya,ca,da,ga,ha,ia,ja,Y,Z,Aa,Ba,Ca;this.matrix=this.projectionMatrix=this.viewMatrix=null;this.view=a;this.target=b;this.upper=c;this.fovyX=d;this.nearZ=e;this.farZ=f;this.aspectRatio=h;this.rotatingMatrix=new Cb;g=this.view;j=this.target;
i=this.upper;k=this.fovyX;l=this.nearZ;p=this.farZ;r=this.aspectRatio;t=new m(j.x-g.x,j.y-g.y,j.z-g.z);v=Math.sqrt((C=t.x)*C+(D=t.y)*D+(I=t.z)*I);q=1E-9>v?new m(0,0,0):t.divSelf$N(v);z=new m((O=i.y)*(L=q.z)-(R=i.z)*(J=q.y),R*(P=q.x)-(G=i.x)*L,G*J-O*P);F=Math.sqrt(($=z.x)*$+(Wa=z.y)*Wa+(Xa=z.z)*Xa);s=1E-9>F?new m(0,0,0):z.divSelf$N(F);x=new m((Ka=q.y)*(Za=s.z)-(Ya=q.z)*(Ja=s.y),Ya*(La=s.x)-($a=q.x)*Za,$a*Ja-Ka*La);y=Math.sqrt((ab=x.x)*ab+(bb=x.y)*bb+(Oa=x.z)*Oa);u=1E-9>y?new m(0,0,0):x.divSelf$N(y);
n=new H([cb=s.x,Pa=s.y,db=s.z,-(cb*(la=g.x)+Pa*(Ra=g.y)+db*(Sa=g.z)),ka=u.x,Qa=u.y,eb=u.z,-(ka*la+Qa*Ra+eb*Sa),Da=q.x,Ma=q.y,Ea=q.z,-(Da*la+Ma*Ra+Ea*Sa),0,0,0,1]);w=1/Math.tan(k/2);B=w/r;E=p/(p-l);o=new H([w,0,0,0,0,B,0,0,0,0,E,-E*l,0,0,1,0]);this.viewMatrix=n;this.projectionMatrix=o;T=(Fa=o._m11)*(Ha=n._m11)+(ea=o._m12)*(pa=n._m21)+(fa=o._m13)*(qa=n._m31)+(Ga=o._m14)*(ra=n._m41);V=Fa*(ta=n._m12)+ea*(va=n._m22)+fa*(ba=n._m32)+Ga*(U=n._m42);X=Fa*(ma=n._m13)+ea*(na=n._m23)+fa*(xa=n._m33)+Ga*(oa=n._m43);
kb=Fa*(ya=n._m14)+ea*(ca=n._m24)+fa*(da=n._m34)+Ga*(ga=n._m44);S=(sa=o._m21)*Ha+(ua=o._m22)*pa+(aa=o._m23)*qa+(wa=o._m24)*ra;K=sa*ta+ua*va+aa*ba+wa*U;W=sa*ma+ua*na+aa*xa+wa*oa;M=sa*ya+ua*ca+aa*da+wa*ga;A=(ha=o._m31)*Ha+(ia=o._m32)*pa+(ja=o._m33)*qa+(Y=o._m34)*ra;Q=ha*ta+ia*va+ja*ba+Y*U;mb=ha*ma+ia*na+ja*xa+Y*oa;N=ha*ya+ia*ca+ja*da+Y*ga;ub=(Z=o._m41)*Ha+(Aa=o._m42)*pa+(Ba=o._m43)*qa+(Ca=o._m44)*ra;this.matrix=new H([T,V,X,kb,S,K,W,M,A,Q,mb,N,ub,Z*ta+Aa*va+Ba*ba+Ca*U,Z*ma+Aa*na+Ba*xa+Ca*oa,Z*ya+Aa*
ca+Ba*da+Ca*ga])}function Hb(){}function za(a,b,c){this.r=a;this.g=b;this.b=c}function wb(){}function Dc(){this.vCenter=this.center=null}function ob(){}function Mb(a,b){this.vVertices=this.vCenter=this.center=null;this.vertices=a;this._color=b;this._enabledLighting=!0;this.updateCenter$()}function tb(){}function Ec(a,b){this.vCenter=null;this.polygons=a;this.center=b;this._ignoringZHidden=!1}function mc(a,b,c){this.vCenter=null;this.polygons=a;this.center=b;this._ignoringZHidden=c}function xb(){}
function nc(a,b){ac.call(this,a,b,6,6,4,2)}function ac(a,b,c,d,e,f){var h,g,j,i,k;h=new za(0,0,0);this.vVertices=this.vCenter=this.center=null;this.vertices=a;this._color=h;this._enabledLighting=!0;this.updateCenter$();this._src=b;this._image=I.images[b];this.vertices=a;b=a[1];h=a[0];i=b.x-h.x;k=b.y-h.y;b=Math.sqrt(i*i+k*k+(g=b.z-h.z)*g);this._width=0<=b?b:-b;g=a[2];a=a[1];b=g.x-a.x;h=g.y-a.y;a=Math.sqrt(b*b+h*h+(j=g.z-a.z)*j);this._height=0<=a?a:-a;this._maxHorizontalDiv=c;this._maxVerticalDiv=d;
this._maxDiv=e;this._minDiv=f;this.updateCenter$()}function Db(){}function oc(a,b,c,d){this.vCenter=null;this._width=b;this._height=c;this._src=d;this._image=I.images[d];this.center=a}function Na(){}function Lb(a){var b,c;this.tail=this.head=null;this.length=0;b=a.length;for(c=0;c<b;c++)this.prepend$LVector$(a.pop())}function bc(){}function Ta(){}function lc(){this.tail=this.head=null;this.length=0}function cc(){}function Ua(){}function nb(){this.tail=this.head=null;this.length=0}function dc(){}function Va(){}
function Eb(){this.tail=this.head=null;this.length=0}function ec(){}function P(){}function Fc(){}function G(){}function Gc(){}function pc(){}function Hc(){}function Nb(){}function Ic(){}function Ia(){}function Jc(){this._lastLapMsec=null;this._elapsedMsec=0;this._startedMsec=null}function yb(){}function Kc(){this._fpsElement=null;this._stopwatch={_elapsedMsec:0,_startedMsec:null,_lastLapMsec:null};this._recentlyMsecLog=[];this._lastMsec=0;this._enabledHtmlLog=!1;this._enabledConsoleLog=!0}function Lc(a){a=
P.document.getElementById(a);this._fpsElement=a instanceof HTMLElement?a:null;this._stopwatch={_elapsedMsec:0,_startedMsec:null,_lastLapMsec:null};this._recentlyMsecLog=[];this._lastMsec=0;this._enabledHtmlLog=!0;this._enabledConsoleLog=!1}function A(){}function Mc(){}function fc(){window.removeEventListener("load",fc);document.removeEventListener("DOMContentLoaded",fc);JSX.runMain("jsx/demo2.jsx",[])}JSX.require=function(a){a=Rc[a];return void 0!==a?a:null};JSX.profilerIsRunning=function(){return null!=
Gb.getResults};JSX.getProfileResults=function(){return(Gb.getResults||function(){return{}})()};JSX.postProfileResults=function(a){if(null==Gb.postResults)throw Error("profiler has not been turned on");return Gb.postResults(a)};JSX.resetProfileResults=function(){if(null==Gb.resetResults)throw Error("profiler has not been turned on");return Gb.resetResults()};pb.prototype={};sc.prototype=new pb;pb.sphere$LContext3D$NI=function(a,b,c){var d,e,f,h,g,j,i,k,l;d=2*c;e=Math.sin;f=Math.cos;h=new m(0,0,0);
a._polygonList=new Eb;a._groupCenter=h;a._ignoringZHidden=!1;for(h=0;h<d;h++)j=1,i=h+1,k=h,Ob(a,[new m(f(6.283185307179586*i/d)*e(0/c)*b,f(0/c)*b,e(6.283185307179586*i/d)*e(0/c)*b),new m(f(6.283185307179586*i/d)*e(3.141592653589793*j/c)*b,f(3.141592653589793*j/c)*b,e(6.283185307179586*i/d)*e(3.141592653589793*j/c)*b),new m(f(6.283185307179586*k/d)*e(3.141592653589793*j/c)*b,f(3.141592653589793*j/c)*b,e(6.283185307179586*k/d)*e(3.141592653589793*j/c)*b)],new za(128,128,255));for(h=1;h<c-1;h++)for(l=
0;l<d;l++)g=h,j=h+1,i=l+1,k=l,Ob(a,[new m(f(6.283185307179586*i/d)*e(3.141592653589793*h/c)*b,f(3.141592653589793*h/c)*b,e(6.283185307179586*i/d)*e(3.141592653589793*h/c)*b),new m(f(6.283185307179586*i/d)*e(3.141592653589793*j/c)*b,f(3.141592653589793*j/c)*b,e(6.283185307179586*i/d)*e(3.141592653589793*j/c)*b),new m(f(6.283185307179586*k/d)*e(3.141592653589793*j/c)*b,f(3.141592653589793*j/c)*b,e(6.283185307179586*k/d)*e(3.141592653589793*j/c)*b),new m(f(6.283185307179586*k/d)*e(3.141592653589793*
g/c)*b,f(3.141592653589793*g/c)*b,e(6.283185307179586*k/d)*e(3.141592653589793*g/c)*b)],new za(128,128,255));for(h=0;h<d;h++)g=c-1,j=c,i=h+1,k=h,Ob(a,[new m(f(6.283185307179586*h/d)*e(3.141592653589793*g/c)*b,f(3.141592653589793*g/c)*b,e(6.283185307179586*h/d)*e(3.141592653589793*g/c)*b),new m(f(6.283185307179586*i/d)*e(3.141592653589793*g/c)*b,f(3.141592653589793*g/c)*b,e(6.283185307179586*i/d)*e(3.141592653589793*g/c)*b),new m(f(6.283185307179586*k/d)*e(3.141592653589793*j/c)*b,f(3.141592653589793*
j/c)*b,e(6.283185307179586*k/d)*e(3.141592653589793*j/c)*b)],new za(128,128,255));gc(a)};var Sc=pb.sphere$LContext3D$NI;pb.tile$LContext3D$IIIILColor$=function(a,b,c,d,e,f){b=[new m(b-e/2,c,d-e/2),new m(b-e/2,c,d+e/2),new m(b+e/2,c,d+e/2),new m(b+e/2,c,d-e/2)];Jb(a,new Mb(b,f))};pb.tileOnGroup$LContext3D$IIIILColor$=function(a,b,c,d,e,f){Ob(a,[new m(b-e/2,c,d-e/2),new m(b-e/2,c,d+e/2),new m(b+e/2,c,d+e/2),new m(b+e/2,c,d-e/2)],f)};var qc=pb.tileOnGroup$LContext3D$IIIILColor$;pb.tileRectXZ$LContext3D$IIIIIILColor$LColor$=
function(a,b,c,d,e,f,h,g,j){var i,k,l,p,r;i=e/h;k=d/h;l=new m(0,0,0);a._polygonList=new Eb;a._groupCenter=l;a._ignoringZHidden=!0;for(l=0;l<i;l++)for(p=0;p<k;p++)r=0===(l+p)%2?g:j,qc(a,b-d/2+(p+0.5)*h,f,c-e/2+(l+0.5)*h,h,r);gc(a)};var Fb=pb.tileRectXZ$LContext3D$IIIIIILColor$LColor$;rb.prototype={};tc.prototype=new rb;rb.moveForward$LPlayer$=function(a){qb(a,50,0)};rb.move$LPlayer$NN=function(a,b,c){var d,e,f;d=a.vx;e=a.vz;f=Math.sqrt(d*d+e*e);if(1E-9<(0<=e?e:-e))e/=f;if(1E-9<(0<=d?d:-d))d/=f;e=Math.atan2(d,
e);d=Math.sin(e);e=Math.cos(e);a.az=e*b-d*c;a.ax=d*b+e*c};var qb=rb.move$LPlayer$NN;rb.brake$LPlayer$=function(a){a.isBraking=!0};rb.unbrake$LPlayer$=function(a){a.isBraking=!1};rb.update$LPlayer$N=function(a,b){var c,d,e,f,h,g,j,i,k,l;c=b/1E3;0.1<c&&(c=0.1);d=a.vx+=a.ax*c;a.vy+=a.ay*c;a.vz+=a.az*c;d=-100>=d?-100:d;a.vx=100<=d?100:d;d=a.vy;d=-3E3>=d?-3E3:d;a.vy=3E3<=d?3E3:d;d=a.vz;d=-100>=d?-100:d;f=a.vz=100<=d?100:d;d=a.vx*c;e=a.vy*c;f*=c;a.x+=d;a.y+=e;a.z+=f;e=a.isBraking?0.05:0.0010;a.vx-=(0<=
d?d:-d)*a.vx*e;a.vz-=(0<=f?f:-f)*a.vz*e;a.isBraking&&(c=Math.pow(2.718281828459045,-c),a.az*=c,a.ax*=c);c=new m(0-1*f,0*f-0*d,1*d-0);e=Math.sqrt((h=c.x)*h+(g=c.y)*g+(j=c.z)*j);h=1E-9>e?new m(0,0,0):c.divSelf$N(e);d=Math.sqrt(d*d+0+f*f)/a.r;g=h.x;j=h.y;c=h.z;h=Math.cos(d/2);d=Math.sin(d/2);g*=d;j*=d;l=c*d;c=a.rot;d=(f=c.t)*h-((e=c.x)*g+(i=c.y)*j+(k=c.z)*l);c.t=d;c.x=f*g+h*e+(i*l-k*j);c.y=f*j+h*i+(k*g-e*l);c.z=f*l+h*k+(e*j-i*g)};var Tc=rb.update$LPlayer$N;rb.bounce$LPlayer$LVector$=function(a,b){var c,
d,e,f;c=a.vx*(d=b.x)+a.vy*(e=b.y)+a.vz*(f=b.z);a.vx-=1.5*c*d;a.vy-=1.5*c*e;a.vz-=1.5*c*f};J.prototype={};hc.prototype=new J;J.prototype._initTrees$=function(){this.trees=new Lb([new m(-271,-3,450),new m(-200,-3,720),new m(139,-3,351),new m(171,-3,254),new m(214,-3,192),new m(-253,-3,555),new m(29,-3,385),new m(-72,-3,530),new m(96,-3,678),new m(-49,-3,222)]);this.treeRadius=24};J.prototype._initItems$=function(){this.items=new Lb([new m(149,-10,724),new m(107,-10,483),new m(279,-10,551),new m(-295,
-10,261),new m(-16,-10,225),new m(95,-10,165),new m(264,-10,161),new m(-50,-10,325),new m(-169,-10,254),new m(271,-10,401)]);this.itemRadius=8};J.prototype._checkCollisionWithFloor$N=function(a){var b,c,d,e,f,h,g,j,i,k,l,p,r,n,o;b=this.player;Tc(b,a);c=b.x;d=b.y;e=b.z;if((-30<=c&&30>=c&&-30<=e&&150>=e||-300<=c&&300>=c&&150<=e&&750>=e||-30<=c&&30>=c&&750<=e&&810>=e||-30<=c&&570>=c&&810<=e&&870>=e||510<=c&&1110>=c&&150<=e&&210>=e||1050<=c&&1110>=c&&750<=e&&1350>=e)&&2*-b.radius<d&&0>d)a=0*b.vx+1*b.vy+
0*b.vz,b.vx-=0*a,b.vy-=1.5*a,b.vz-=0*a,b.y=0;510<=c&&(570>=c&&510<=e&&810>=e)&&(a=Math.floor((810-e)/30),a*=5,a-2*b.radius<d&&d<a&&(j=new m(0,30,5),i=Math.sqrt((k=j.x)*k+(l=j.y)*l+(f=j.z)*f),f=1E-9>i?new m(0,0,0):j.divSelf$N(i),f=b.vx*(k=f.x)+b.vy*(l=f.y)+b.vz*(j=f.z),b.vx-=1.5*f*k,b.vy-=1.5*f*l,b.vz-=1.5*f*j,b.y=a));510<=c&&(570>=c&&210<=e&&510>e)&&(a=Math.floor((e-210)/30),a*=5,a-2*b.radius<d&&d<a&&(k=new m(0,30,-5),l=Math.sqrt((p=k.x)*p+(r=k.y)*r+(h=k.z)*h),h=1E-9>l?new m(0,0,0):k.divSelf$N(l),
h=b.vx*(p=h.x)+b.vy*(r=h.y)+b.vz*(k=h.z),b.vx-=1.5*h*p,b.vy-=1.5*h*r,b.vz-=1.5*h*k,b.y=a));1110<=c&&(1270>=c&&150<=e&&810>=e)&&(a=80*((c-1110)/160),a-2*b.radius<d&&d<a&&(c=new m(-1,2,0),d=Math.sqrt((n=c.x)*n+(o=c.y)*o+(g=c.z)*g),g=1E-9>d?new m(0,0,0):c.divSelf$N(d),g=b.vx*(n=g.x)+b.vy*(o=g.y)+b.vz*(c=g.z),b.vx-=1.5*g*n,b.vy-=1.5*g*o,b.vz-=1.5*g*c,b.y=a))};J.prototype._checkCollisionWithTrees$=function(){var a=this,b;b=this.player;this.trees.forEach$F$LVector$V$(function(c){var d,e,f,h,g,j,i,k,l;d=
b.x-c.x;e=b.y-c.y;c=b.z-c.z;f=a.treeRadius+b.radius;d*d+e*e+c*c<f*f&&(d=new m(d,e,c),e=Math.sqrt((h=d.x)*h+(g=d.y)*g+(j=d.z)*j),h=1E-9>e?new m(0,0,0):d.divSelf$N(e),g=Math.sqrt((i=b.vx)*i+(k=b.vy)*k+(l=b.vz)*l),b.ax+=2*g*(i=h.x),b.vy+=2*g*h.y,b.az+=2*g*(k=h.z),b.x+=i*(i=a.treeRadius)/4,b.z+=k*i/4)})};J.prototype._checkCollisionWithItems$=function(){var a,b,c,d,e,f,h,g;a=this.player;b=this.items;c=this.itemRadius;for(d=b.head;d;d=d._next)e=d.value,f=e.x-a.x,h=e.y-a.y,e=e.z-a.z,g=c+a.radius,f*f+h*h+
e*e<g*g&&b.remove$LNode$Vector$E$(d)};J.prototype._updateViewpoint$=function(){var a,b,c,d,e,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,B,E,T,V,X,kb,S,K,W,M,A,Q,mb,N,C,D,I,R,G,L,J,O,P,$,za,Wa,Xa,Ya,Za,$a,Ja,Ka,La,ab,bb,Oa,cb,Pa,db,ka,la,Qa,Ra,eb,Sa,Da,Ma,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,aa,ba,wa,U,ma,na,xa,oa,ya,ca,da,ga,ha,ia,ja,Y,Z,Aa,Ba,Ca,fb,gb,hb,ib,jb;a=this.player;b=-a.vz;c=-a.vx;d=Math.sqrt(b*b+c*c);1E-9>d?(b=-1,c=0):(b/=d,c/=d);e=a.y;0>e&&(e=-300<=e?e:-300,e=-e/2);f=10;h=Math.sqrt((R=
a.vx)*R+(G=a.vz)*G);50>h&&(f-=0.6*(50-h));g=new m(a.x+50*c,1.2*e+f,a.z+50*b);j=new m(a.x,a.y,a.z);(L=this.engine.camera).target=j;L.view=g;i=L.view;k=L.target;l=L.upper;p=L.fovyX;r=L.nearZ;n=L.farZ;o=L.aspectRatio;z=new m(k.x-i.x,k.y-i.y,k.z-i.z);F=Math.sqrt((J=z.x)*J+(O=z.y)*O+(P=z.z)*P);u=1E-9>F?new m(0,0,0):z.divSelf$N(F);x=new m((Ya=l.y)*(za=u.z)-($=l.z)*(Xa=u.y),$*(Za=u.x)-(Wa=l.x)*za,Wa*Xa-Ya*Za);y=Math.sqrt(($a=x.x)*$a+(Ja=x.y)*Ja+(Ka=x.z)*Ka);t=1E-9>y?new m(0,0,0):x.divSelf$N(y);w=new m((cb=
u.y)*(ab=t.z)-(La=u.z)*(Oa=t.y),La*(Pa=t.x)-(bb=u.x)*ab,bb*Oa-cb*Pa);B=Math.sqrt((db=w.x)*db+(ka=w.y)*ka+(la=w.z)*la);v=1E-9>B?new m(0,0,0):w.divSelf$N(B);q=new H([Qa=t.x,Ra=t.y,eb=t.z,-(Qa*(Da=i.x)+Ra*(Ea=i.y)+eb*(ea=i.z)),Sa=v.x,Ma=v.y,Fa=v.z,-(Sa*Da+Ma*Ea+Fa*ea),fa=u.x,Ga=u.y,Ha=u.z,-(fa*Da+Ga*Ea+Ha*ea),0,0,0,1]);E=1/Math.tan(p/2);T=E/o;V=n/(n-r);s=new H([E,0,0,0,0,T,0,0,0,0,V,-V*r,0,0,1,0]);L.viewMatrix=q;L.projectionMatrix=s;X=(pa=s._m11)*(ta=q._m11)+(qa=s._m12)*(ua=q._m21)+(ra=s._m13)*(va=q._m31)+
(sa=s._m14)*(aa=q._m41);kb=pa*(wa=q._m12)+qa*(ma=q._m22)+ra*(xa=q._m32)+sa*(ya=q._m42);S=pa*(ca=q._m13)+qa*(da=q._m23)+ra*(ga=q._m33)+sa*(ha=q._m43);K=pa*(ia=q._m14)+qa*(ja=q._m24)+ra*(Y=q._m34)+sa*(Z=q._m44);W=(ba=s._m21)*ta+(U=s._m22)*ua+(na=s._m23)*va+(oa=s._m24)*aa;M=ba*wa+U*ma+na*xa+oa*ya;A=ba*ca+U*da+na*ga+oa*ha;Q=ba*ia+U*ja+na*Y+oa*Z;mb=(Aa=s._m31)*ta+(Ba=s._m32)*ua+(Ca=s._m33)*va+(fb=s._m34)*aa;N=Aa*wa+Ba*ma+Ca*xa+fb*ya;C=Aa*ca+Ba*da+Ca*ga+fb*ha;D=Aa*ia+Ba*ja+Ca*Y+fb*Z;I=(gb=s._m41)*ta+(hb=
s._m42)*ua+(ib=s._m43)*va+(jb=s._m44)*aa;L.matrix=new H([X,kb,S,K,W,M,A,Q,mb,N,C,D,I,gb*wa+hb*ma+ib*xa+jb*ya,gb*ca+hb*da+ib*ga+jb*ha,gb*ia+hb*ja+ib*Y+jb*Z])};J.prototype._updateClearedPlayer$N=function(a){var b,c,d,e;b=this.player;c=b.x-1080;d=b.y-20;e=b.z-1380;1>(0<=c?c:-c)&&1>(0<=e?e:-e)?b.y-=10*Math.sin(this.totalElapsedMsec/1E3)*a/1E3:(b.x-=c*a/1E3,b.y-=d*a/1E3,b.z-=e*a/1E3)};J.prototype._updateClearedViewpoint$=function(){var a,b,c,d,e,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,B,E,T,V,X,kb,S,
K,A,M,C,Q,D,N,I,R,G,J,O,L,P,$,za,Ia,Na,Wa,Xa,Ya,Za,$a,Ja,Ka,La,ab,bb,Oa,cb,Pa,db,ka,la,Qa,Ra,eb,Sa,Da,Ma,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,aa,ba,wa,U,ma,na,xa,oa,ya,ca,da,ga,ha,ia,ja,Y,Z;a=this.player;b=new m(a.x+50*Math.sin(this.totalElapsedMsec/5E3),a.y+20,a.z+50*Math.cos(this.totalElapsedMsec/5E3));c=new m(a.x,a.y,a.z);(Q=this.engine.camera).target=c;Q.view=b;d=Q.view;e=Q.target;f=Q.upper;h=Q.fovyX;g=Q.nearZ;j=Q.farZ;i=Q.aspectRatio;o=new m(e.x-d.x,e.y-d.y,e.z-d.z);q=Math.sqrt((D=o.x)*D+(N=
o.y)*N+(I=o.z)*I);p=1E-9>q?new m(0,0,0):o.divSelf$N(q);s=new m((L=f.y)*(G=p.z)-(R=f.z)*(O=p.y),R*(P=p.x)-(J=f.x)*G,J*O-L*P);u=Math.sqrt(($=s.x)*$+(za=s.y)*za+(Ia=s.z)*Ia);r=1E-9>u?new m(0,0,0):s.divSelf$N(u);t=new m((Za=p.y)*(Wa=r.z)-(Na=p.z)*(Ya=r.y),Na*($a=r.x)-(Xa=p.x)*Wa,Xa*Ya-Za*$a);v=Math.sqrt((Ja=t.x)*Ja+(Ka=t.y)*Ka+(La=t.z)*La);n=1E-9>v?new m(0,0,0):t.divSelf$N(v);k=new H([ab=r.x,bb=r.y,Oa=r.z,-(ab*(Pa=d.x)+bb*(ka=d.y)+Oa*(Qa=d.z)),cb=n.x,db=n.y,la=n.z,-(cb*Pa+db*ka+la*Qa),Ra=p.x,eb=p.y,Sa=
p.z,-(Ra*Pa+eb*ka+Sa*Qa),0,0,0,1]);z=1/Math.tan(h/2);F=z/i;x=j/(j-g);l=new H([z,0,0,0,0,F,0,0,0,0,x,-x*g,0,0,1,0]);Q.viewMatrix=k;Q.projectionMatrix=l;y=(Da=l._m11)*(ea=k._m11)+(Ma=l._m12)*(fa=k._m21)+(Ea=l._m13)*(Ga=k._m31)+(Fa=l._m14)*(Ha=k._m41);w=Da*(qa=k._m12)+Ma*(sa=k._m22)+Ea*(ua=k._m32)+Fa*(aa=k._m42);B=Da*(ba=k._m13)+Ma*(wa=k._m23)+Ea*(U=k._m33)+Fa*(ma=k._m43);E=Da*(na=k._m14)+Ma*(xa=k._m24)+Ea*(oa=k._m34)+Fa*(ya=k._m44);T=(pa=l._m21)*ea+(ra=l._m22)*fa+(ta=l._m23)*Ga+(va=l._m24)*Ha;V=pa*
qa+ra*sa+ta*ua+va*aa;X=pa*ba+ra*wa+ta*U+va*ma;kb=pa*na+ra*xa+ta*oa+va*ya;S=(ca=l._m31)*ea+(da=l._m32)*fa+(ga=l._m33)*Ga+(ha=l._m34)*Ha;K=ca*qa+da*sa+ga*ua+ha*aa;A=ca*ba+da*wa+ga*U+ha*ma;M=ca*na+da*xa+ga*oa+ha*ya;C=(ia=l._m41)*ea+(ja=l._m42)*fa+(Y=l._m43)*Ga+(Z=l._m44)*Ha;Q.matrix=new H([y,w,B,E,T,V,X,kb,S,K,A,M,C,ia*qa+ja*sa+Y*ua+Z*aa,ia*ba+ja*wa+Y*U+Z*ma,ia*na+ja*xa+Y*oa+Z*ya])};J.prototype._renderPlayer$LContext3D$=function(a){var b,c,d,e,f,h,g,j,i,k,l,p,r,n,o,q,m,u,t,v,z,F,x,y,w,B;(b=this.player).y<
-b.radius?Kb(a,5):Kb(a,3);b=(d=this.player).x;c=d.y-12;d=d.z;e=a._worldMatrix;f=e._m11;h=e._m12;g=e._m13;j=e._m14;i=e._m21;k=e._m22;l=e._m23;p=e._m24;r=e._m31;n=e._m32;o=e._m33;q=e._m34;m=e._m41;u=e._m42;t=e._m43;v=e._m44;e._m11=1*f+0*h+0*g+0*j;e._m12=0*f+1*h+0*g+0*j;e._m13=0*f+0*h+1*g+0*j;e._m14=f*b+h*c+g*d+1*j;e._m21=1*i+0*k+0*l+0*p;e._m22=0*i+1*k+0*l+0*p;e._m23=0*i+0*k+1*l+0*p;e._m24=i*b+k*c+l*d+1*p;e._m31=1*r+0*n+0*o+0*q;e._m32=0*r+1*n+0*o+0*q;e._m33=0*r+0*n+1*o+0*q;e._m34=r*b+n*c+o*d+1*q;e._m41=
1*m+0*u+0*t+0*v;e._m42=0*m+1*u+0*t+0*v;e._m43=0*m+0*u+1*t+0*v;e._m44=m*b+u*c+t*d+1*v;e=this.player.rot;b=a._worldMatrix;g=2*(x=e.x)*x;j=2*(y=e.y)*y;d=2*(w=e.z)*w;c=2*x*y;f=2*x*w;h=2*y*w;i=2*x*(x=e.t);k=2*y*x;e=2*w*x;w=1-j-d;y=c+e;x=f-k;c-=e;d=1-g-d;e=h+i;f+=k;h-=i;B=1-g-j;g=b._m11;j=b._m12;i=b._m13;k=b._m14;l=b._m21;p=b._m22;r=b._m23;n=b._m24;o=b._m31;q=b._m32;m=b._m33;u=b._m34;t=b._m41;v=b._m42;z=b._m43;F=b._m44;b._m11=g*w+j*c+i*f+0*k;b._m12=g*y+j*d+i*h+0*k;b._m13=g*x+j*e+i*B+0*k;b._m14=0*g+0*j+
0*i+1*k;b._m21=l*w+p*c+r*f+0*n;b._m22=l*y+p*d+r*h+0*n;b._m23=l*x+p*e+r*B+0*n;b._m24=0*l+0*p+0*r+1*n;b._m31=o*w+q*c+m*f+0*u;b._m32=o*y+q*d+m*h+0*u;b._m33=o*x+q*e+m*B+0*u;b._m34=0*o+0*q+0*m+1*u;b._m41=t*w+v*c+z*f+0*F;b._m42=t*y+v*d+z*h+0*F;b._m43=t*x+v*e+z*B+0*F;b._m44=0*t+0*v+0*z+1*F;Sc(a,this.player.radius,6);a._worldMatrix=new Cb};J.prototype._renderTrees$LContext3D$=function(a){Kb(a,3);this.trees.forEach$F$LVector$V$(function(b){var c,d,e,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v;c=b.x;d=b.y;b=b.z;a._matrixStack.prepend$LMatrix$(a._worldMatrix.copy$());
e=a._worldMatrix;f=e._m11;h=e._m12;g=e._m13;j=e._m14;i=e._m21;k=e._m22;l=e._m23;p=e._m24;r=e._m31;n=e._m32;o=e._m33;q=e._m34;s=e._m41;u=e._m42;t=e._m43;v=e._m44;e._m11=1*f+0*h+0*g+0*j;e._m12=0*f+1*h+0*g+0*j;e._m13=0*f+0*h+1*g+0*j;e._m14=f*c+h*d+g*b+1*j;e._m21=1*i+0*k+0*l+0*p;e._m22=0*i+1*k+0*l+0*p;e._m23=0*i+0*k+1*l+0*p;e._m24=i*c+k*d+l*b+1*p;e._m31=1*r+0*n+0*o+0*q;e._m32=0*r+1*n+0*o+0*q;e._m33=0*r+0*n+1*o+0*q;e._m34=r*c+n*d+o*b+1*q;e._m41=1*s+0*u+0*t+0*v;e._m42=0*s+1*u+0*t+0*v;e._m43=0*s+0*u+1*t+
0*v;e._m44=s*c+u*d+t*b+1*v;Uc(a,new m(0,0,0),50,34,"./image/tree.png");a._worldMatrix=a._matrixStack.removeFirst$()})};J.prototype._renderItems$LContext3D$=function(a){var b,c,d,e,f;Kb(a,3);b=3.141592653589793*this.totalElapsedMsec/1E3;c=Math.cos(b/2);d=Math.sin(b/2);e=0*d;f=0*d;this.items.forEach$F$LVector$V$(function(b){var g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,B,E,T,V,X,A;g=b.x;j=b.y;b=b.z;a._matrixStack.prepend$LMatrix$(a._worldMatrix.copy$());i=a._worldMatrix;k=i._m11;l=i._m12;p=i._m13;r=i._m14;
n=i._m21;o=i._m22;q=i._m23;s=i._m24;u=i._m31;t=i._m32;v=i._m33;z=i._m34;F=i._m41;x=i._m42;y=i._m43;w=i._m44;i._m11=1*k+0*l+0*p+0*r;i._m12=0*k+1*l+0*p+0*r;i._m13=0*k+0*l+1*p+0*r;i._m14=k*g+l*j+p*b+1*r;i._m21=1*n+0*o+0*q+0*s;i._m22=0*n+1*o+0*q+0*s;i._m23=0*n+0*o+1*q+0*s;i._m24=n*g+o*j+q*b+1*s;i._m31=1*u+0*t+0*v+0*z;i._m32=0*u+1*t+0*v+0*z;i._m33=0*u+0*t+1*v+0*z;i._m34=u*g+t*j+v*b+1*z;i._m41=1*F+0*x+0*y+0*w;i._m42=0*F+1*x+0*y+0*w;i._m43=0*F+0*x+1*y+0*w;i._m44=F*g+x*j+y*b+1*w;g=a._worldMatrix;o=2*e*e;
q=2*d*d;l=2*f*f;k=2*e*d;r=2*e*f;n=2*d*f;s=2*e*c;u=2*d*c;p=2*f*c;j=1-q-l;b=k+p;i=r-u;k-=p;l=1-o-l;p=n+s;r+=u;n-=s;A=1-o-q;o=g._m11;q=g._m12;s=g._m13;u=g._m14;t=g._m21;v=g._m22;z=g._m23;F=g._m24;x=g._m31;y=g._m32;w=g._m33;B=g._m34;E=g._m41;T=g._m42;V=g._m43;X=g._m44;g._m11=o*j+q*k+s*r+0*u;g._m12=o*b+q*l+s*n+0*u;g._m13=o*i+q*p+s*A+0*u;g._m14=0*o+0*q+0*s+1*u;g._m21=t*j+v*k+z*r+0*F;g._m22=t*b+v*l+z*n+0*F;g._m23=t*i+v*p+z*A+0*F;g._m24=0*t+0*v+0*z+1*F;g._m31=x*j+y*k+w*r+0*B;g._m32=x*b+y*l+w*n+0*B;g._m33=
x*i+y*p+w*A+0*B;g._m34=0*x+0*y+0*w+1*B;g._m41=E*j+T*k+V*r+0*X;g._m42=E*b+T*l+V*n+0*X;g._m43=E*i+T*p+V*A+0*X;g._m44=0*E+0*T+0*V+1*X;Vc(a,[new m(-15,-10,0),new m(15,-10,0),new m(15,10,0),new m(-15,10,0)],"./image/redbull_free.png",2,2,1,1);a._worldMatrix=a._matrixStack.removeFirst$()})};J.prototype._renderField$LContext3D$=function(a){var b,c,d,e,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t;b=new za(192,192,192);c=new za(160,255,160);d=new za(96,255,96);Kb(a,4);Fb(a,0,60,60,180,-20,30,b,b);Fb(a,0,450,600,600,-20,
30,c,d);Fb(a,0,780,60,60,-20,30,d,c);Fb(a,270,840,600,60,-20,30,d,c);a._matrixStack.prepend$LMatrix$(a._worldMatrix.copy$());b=new m(0,0,0);a._polygonList=new Eb;a._groupCenter=b;a._ignoringZHidden=!0;b=a._worldMatrix;e=b._m11;f=b._m12;h=b._m13;g=b._m14;j=b._m21;i=b._m22;k=b._m23;l=b._m24;p=b._m31;r=b._m32;n=b._m33;o=b._m34;q=b._m41;s=b._m42;u=b._m43;t=b._m44;b._m11=1*e+0*f+0*h+0*g;b._m12=0*e+1*f+0*h+0*g;b._m13=0*e+0*f+1*h+0*g;b._m14=510*e+0*f+510*h+1*g;b._m21=1*j+0*i+0*k+0*l;b._m22=0*j+1*i+0*k+0*
l;b._m23=0*j+0*i+1*k+0*l;b._m24=510*j+0*i+510*k+1*l;b._m31=1*p+0*r+0*n+0*o;b._m32=0*p+1*r+0*n+0*o;b._m33=0*p+0*r+1*n+0*o;b._m34=510*p+0*r+510*n+1*o;b._m41=1*q+0*s+0*u+0*t;b._m42=0*q+1*s+0*u+0*t;b._m43=0*q+0*s+1*u+0*t;b._m44=510*q+0*s+510*u+1*t;for(b=0;10>b;b++)for(e=0;2>e;e++)f=0===(b+e)%2?c:d,qc(a,30*e+15,-20+5*(9-b),30*b+15,30,f);for(b=0;10>b;b++)for(e=0;2>e;e++)f=0===(b+e)%2?c:d,qc(a,30*e+15,-20+5*(9-b),30*-b-15,30,f);gc(a);a._worldMatrix=a._matrixStack.removeFirst$();Fb(a,810,180,600,60,-20,30,
d,c);a._matrixStack.prepend$LMatrix$(a._worldMatrix.copy$());b=new m(0,0,0);a._polygonList=new Eb;a._groupCenter=b;a._ignoringZHidden=!0;b=a._worldMatrix;e=b._m11;f=b._m12;h=b._m13;g=b._m14;j=b._m21;i=b._m22;k=b._m23;l=b._m24;p=b._m31;r=b._m32;n=b._m33;o=b._m34;q=b._m41;s=b._m42;u=b._m43;t=b._m44;b._m11=1*e+0*f+0*h+0*g;b._m12=0*e+1*f+0*h+0*g;b._m13=0*e+0*f+1*h+0*g;b._m14=1110*e+0*f+150*h+1*g;b._m21=1*j+0*i+0*k+0*l;b._m22=0*j+1*i+0*k+0*l;b._m23=0*j+0*i+1*k+0*l;b._m24=1110*j+0*i+150*k+1*l;b._m31=1*
p+0*r+0*n+0*o;b._m32=0*p+1*r+0*n+0*o;b._m33=0*p+0*r+1*n+0*o;b._m34=1110*p+0*r+150*n+1*o;b._m41=1*q+0*s+0*u+0*t;b._m42=0*q+1*s+0*u+0*t;b._m43=0*q+0*s+1*u+0*t;b._m44=1110*q+0*s+150*u+1*t;for(b=0;4>b;b++)for(e=0;22>e;e++)f=0===(b+e)%2?c:d,Ob(a,[new m(40*b,-20+20*b,30*e),new m(40*b,-20+20*b,30*(e+1)),new m(40*(b+1),-20+20*(b+1),30*(e+1)),new m(40*(b+1),-20+20*(b+1),30*e)],f);gc(a);a._worldMatrix=a._matrixStack.removeFirst$();Fb(a,1080,1050,60,600,-20,30,d,c);Fb(a,1080,1380,60,60,-20,15,new za(255,215,
0),new za(255,255,255));Kb(a,3)};J.prototype._setMobileOperation$=function(){var a=this;P.window.addEventListener("devicemotion",function(b){var c,d,e,b=b instanceof DeviceMotionEvent?b:null;c=30*b.accelerationIncludingGravity.y;b=30*b.accelerationIncludingGravity.x/2;c=120>=c?c:120;-60>c?(c=d=a.player,c.isBraking=!0,qb(d,0,b/4)):0>c?(c=d=a.player,c.isBraking=!1,qb(d,0,b/2)):(d=e=a.player,d.isBraking=!1,qb(e,c,b))});P.window.addEventListener("touchstart",function(){a.isStarted?a.player.vy=80:(a.isStarted=
!0,a.player.vz=100)})};J.prototype._setPCOperation$=function(){var a=this;P.window.document.addEventListener("keypress",function(b){var c;if(a.isStarted)switch(b=b instanceof KeyboardEvent?b:null,b.keyCode){case 119:b=c=a.player;b.isBraking=!1;qb(c,100,0);break;case 115:b=a.player;b.isBraking=!0;break;case 97:b=c=a.player;b.isBraking=!1;qb(c,0,-50);break;case 100:b=c=a.player;b.isBraking=!1;qb(c,0,50);break;case 104:b=c=a.player;b.isBraking=!1;qb(c,0,-50);break;case 106:b=a.player;b.isBraking=!0;
break;case 107:b=c=a.player;b.isBraking=!1;qb(c,100,0);break;case 108:b=c=a.player;b.isBraking=!1;qb(c,0,50);break;case 113:b=a.engine;b._isRunning=!1;break;case 32:a.player.vy=80}else a.isStarted=!0,a.player.vz=100},!1)};J.prototype.run$=function(){this.engine.start$()};$b.prototype={};yc.prototype=new $b;$b.main$AS=function(){(new hc).engine.start$()};D.prototype={};m.prototype=new D;R.prototype=new D;zc.prototype=new D;D.origin$=function(){return new m(0,0,0)};D.prototype.add$LVector$=function(a){return new m(this.x+
a.x,this.y+a.y,this.z+a.z)};D.prototype.addSelf$LVector$=function(a){this.x+=a.x;this.y+=a.y;this.z+=a.z;return this};D.prototype.sub$LVector$=function(a){return new m(this.x-a.x,this.y-a.y,this.z-a.z)};D.prototype.subSelf$LVector$=function(a){this.x-=a.x;this.y-=a.y;this.z-=a.z;return this};D.prototype.mul$N=function(a){return new m(this.x*a,this.y*a,this.z*a)};D.prototype.mulSelf$N=function(a){this.x*=a;this.y*=a;this.z*=a;return this};D.prototype.div$N=function(a){return new m(this.x/a,this.y/
a,this.z/a)};D.prototype.divSelf$N=function(a){this.x/=a;this.y/=a;this.z/=a;return this};D.prototype.dot$LVector$=function(a){return this.x*a.x+this.y*a.y+this.z*a.z};D.prototype.cross$LVector$=function(a){var b,c,d,e,f,h;return new m((f=this.y)*(c=a.z)-(b=this.z)*(e=a.y),b*(h=a.x)-(d=this.x)*c,d*e-f*h)};D.prototype.crossSelf$LVector$=function(a){var b,c,d,e,f;b=(f=this.y)*(c=a.z)-(d=this.z)*(e=a.y);c=d*(d=a.x)-(a=this.x)*c;this.x=b;this.y=c;this.z=a*e-f*d;return this};D.prototype.unit$=function(){var a,
b,c,d;a=Math.sqrt((b=this.x)*b+(c=this.y)*c+(d=this.z)*d);return 1E-9>a?new m(0,0,0):new m(this.x/a,this.y/a,this.z/a)};D.prototype.unitSelf$=function(){var a,b,c,d;a=Math.sqrt((b=this.x)*b+(c=this.y)*c+(d=this.z)*d);return 1E-9>a?new m(0,0,0):this.divSelf$N(a)};D.prototype.sqabs$=function(){var a,b,c;return(a=this.x)*a+(b=this.y)*b+(c=this.z)*c};D.prototype.abs$=function(){var a,b,c;return Math.sqrt((a=this.x)*a+(b=this.y)*b+(c=this.z)*c)};D.prototype.rotateX$N=function(a){var b,c,d;b=Math.sin(a);
a=Math.cos(a);return new m(this.x,(d=this.y)*a-(c=this.z)*b,c*a+d*b)};D.prototype.rotateXSelf$N=function(a){var b,c,d,e;b=Math.sin(a);a=Math.cos(a);this.y=c=(e=this.y)*a-(d=this.z)*b;this.z=d*a+e*b;return this};D.prototype.rotateY$N=function(a){var b,c,d;b=Math.sin(a);a=Math.cos(a);return new m((d=this.x)*a+(c=this.z)*b,this.y,c*a-d*b)};D.prototype.rotateYSelf$N=function(a){var b,c,d,e;b=Math.sin(a);a=Math.cos(a);this.x=c=(e=this.x)*a+(d=this.z)*b;this.z=d*a-e*b;return this};D.prototype.rotateZ$N=
function(a){var b,c,d;b=Math.sin(a);a=Math.cos(a);return new m(this.x*a-(c=this.y)*b,c*a+(d=this.z)*b,d)};D.prototype.rotateZSelf$N=function(a){var b,c,d;b=Math.sin(a);c=Math.cos(a);a=this.x*c-(d=this.y)*b;b=d*c+this.z*b;this.x=a;this.y=b;return this};D.prototype.transform$LMatrix$=function(a){var b,c,d,e,f;b=a._m11*(c=this.x)+a._m12*(d=this.y)+a._m13*(e=this.z)+a._m14*(f=this.w);return new R(b,a._m21*c+a._m22*d+a._m23*e+a._m24*f,a._m31*c+a._m32*d+a._m33*e+a._m34*f,a._m41*c+a._m42*d+a._m43*e+a._m44*
f)};D.prototype.transformSelf$LMatrix$=function(a){var b,c,d,e,f,h,g;b=a._m11*(e=this.x)+a._m12*(f=this.y)+a._m13*(h=this.z)+a._m14*(g=this.w);c=a._m21*e+a._m22*f+a._m23*h+a._m24*g;d=a._m31*e+a._m32*f+a._m33*h+a._m34*g;a=a._m41*e+a._m42*f+a._m43*h+a._m44*g;this.x=b/a;this.y=c/a;this.z=d/a;this.w=1;return this};D.prototype.toString=function(){var a;a=function(a){var c,d,a=a.toFixed(1);c=a.length;for(d=0;d<8-c;d++)a=" "+a;return a};return"("+a(this.x)+","+a(this.y)+","+a(this.z)+","+a(this.w)+")"};
O.prototype={};Cb.prototype=new O;H.prototype=new O;O.prototype.copy$=function(){return new H([this._m11,this._m12,this._m13,this._m14,this._m21,this._m22,this._m23,this._m24,this._m31,this._m32,this._m33,this._m34,this._m41,this._m42,this._m43,this._m44])};O.translating$LVector$=function(a){return new H([1,0,0,a.x,0,1,0,a.y,0,0,1,a.z,0,0,0,1])};O.translating$NNN=function(a,b,c){return new H([1,0,0,a,0,1,0,b,0,0,1,c,0,0,0,1])};O.rotatingX$N=function(a){var b;b=Math.sin(a);a=Math.cos(a);return new H([1,
0,0,0,0,a,-b,0,0,b,a,0,0,0,0,1])};O.rotatingY$N=function(a){var b;b=Math.sin(a);a=Math.cos(a);return new H([a,0,b,0,0,1,0,0,-b,0,a,0,0,0,0,1])};O.rotatingZ$N=function(a){var b;b=Math.sin(a);a=Math.cos(a);return new H([a,-b,0,0,b,a,0,0,0,0,1,0,0,0,0,1])};O.scaling$NNN=function(a,b,c){return new H([a,0,0,0,0,b,0,0,0,0,c,0,0,0,0,1])};O.prototype.mul$LVector$=function(a){var b,c,d,e,a=this._m11*(b=a.x)+this._m12*(c=a.y)+this._m13*(d=a.z)+this._m14*(e=a.w);return new R(a,this._m21*b+this._m22*c+this._m23*
d+this._m24*e,this._m31*b+this._m32*c+this._m33*d+this._m34*e,this._m41*b+this._m42*c+this._m43*d+this._m44*e)};O.prototype.compose$LMatrix$=function(a){var b,c,d,e,f,h,g,j,i,k,l,p,r,n,o,m,s,u,t,v,z,F,x,y,w,B,E,T,V,A;b=(g=this._m11)*(k=a._m11)+(j=this._m12)*(l=a._m21)+(i=this._m13)*(p=a._m31)+(e=this._m14)*(h=a._m41);c=g*(n=a._m12)+j*(m=a._m22)+i*(u=a._m32)+e*(v=a._m42);d=g*(z=a._m13)+j*(F=a._m23)+i*(x=a._m33)+e*(y=a._m43);a=g*(g=a._m14)+j*(j=a._m24)+i*(i=a._m34)+e*(w=a._m44);e=(r=this._m21)*k+(o=
this._m22)*l+(s=this._m23)*p+(t=this._m24)*h;f=(B=this._m31)*k+(E=this._m32)*l+(T=this._m33)*p+(V=this._m34)*h;h=(A=this._m41)*k+(k=this._m42)*l+(l=this._m43)*p+(p=this._m44)*h;return new H([b,c,d,a,e,r*n+o*m+s*u+t*v,r*z+o*F+s*x+t*y,r*g+o*j+s*i+t*w,f,B*n+E*m+T*u+V*v,B*z+E*F+T*x+V*y,B*g+E*j+T*i+V*w,h,A*n+k*m+l*u+p*v,A*z+k*F+l*x+p*y,A*g+k*j+l*i+p*w])};O.prototype.composeSelf$LMatrix$=function(a){var b,c,d,e,f,h,g,j,i,k,l,p,m,n,o,q,s,u,t,v,z,F,x,y,w,B,E,T;b=this._m11;c=this._m12;d=this._m13;e=this._m14;
f=this._m21;h=this._m22;g=this._m23;j=this._m24;i=this._m31;k=this._m32;l=this._m33;p=this._m34;m=this._m41;n=this._m42;o=this._m43;q=this._m44;this._m11=b*(s=a._m11)+c*(u=a._m21)+d*(t=a._m31)+e*(v=a._m41);this._m12=b*(z=a._m12)+c*(F=a._m22)+d*(x=a._m32)+e*(y=a._m42);this._m13=b*(w=a._m13)+c*(B=a._m23)+d*(E=a._m33)+e*(T=a._m43);this._m14=b*(b=a._m14)+c*(c=a._m24)+d*(d=a._m34)+e*(a=a._m44);this._m21=f*s+h*u+g*t+j*v;this._m22=f*z+h*F+g*x+j*y;this._m23=f*w+h*B+g*E+j*T;this._m24=f*b+h*c+g*d+j*a;this._m31=
i*s+k*u+l*t+p*v;this._m32=i*z+k*F+l*x+p*y;this._m33=i*w+k*B+l*E+p*T;this._m34=i*b+k*c+l*d+p*a;this._m41=m*s+n*u+o*t+q*v;this._m42=m*z+n*F+o*x+q*y;this._m43=m*w+n*B+o*E+q*T;this._m44=m*b+n*c+o*d+q*a;return this};O.prototype.toString=function(){var a,b;a=function(a){var b,e,a=a.toFixed(1);b=a.length;for(e=0;e<8-b;e++)a=" "+a;return a};b=""+("|"+a(this._m11)+","+a(this._m12)+","+a(this._m13)+","+a(this._m14)+"|\n");b+="|"+a(this._m21)+","+a(this._m22)+","+a(this._m23)+","+a(this._m24)+"|\n";b+="|"+a(this._m31)+
","+a(this._m32)+","+a(this._m33)+","+a(this._m34)+"|\n";return b+="|"+a(this._m41)+","+a(this._m42)+","+a(this._m43)+","+a(this._m44)+"|\n"};O.prototype.invert$=function(){var a,b,c,d,e,f;d=[this._m11,this._m12,this._m13,this._m14,this._m21,this._m22,this._m23,this._m24,this._m31,this._m32,this._m33,this._m34,this._m41,this._m42,this._m43,this._m44];e=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];for(a=0;3>a;a++){c=d[4*a+a];for(b=0;4>b;b++)d[4*a+b]/=c,e[4*a+b]/=c;for(b=a+1;4>b;b++){f=d[4*b+a];for(c=0;4>c;c++)d[4*
b+c]-=d[4*a+c]*f,e[4*b+c]-=e[4*a+c]*f}}for(a=3;0<a;a--)for(b=a-1;0<=b;b--){f=d[4*b+a];for(c=0;4>c;c++)d[4*b+c]-=d[4*a+c]*f,e[4*b+c]-=e[4*a+c]*f}return new H(e)};$.prototype={};Ac.prototype=new $;Bc.prototype=new $;Ab.prototype=new $;$.prototype.copy$=function(){return new Ab(this.t,this.x,this.y,this.z)};$.prototype.mul$LQuaternion$=function(a){var b,c,d,e,f,h,g,j,i;b=new Ab(this.t,this.x,this.y,this.z);a=(c=b.t)*(e=a.t)-((f=b.x)*(d=a.x)+(h=b.y)*(i=a.y)+(j=b.z)*(g=a.z));b.t=a;b.x=c*d+e*f+(h*g-j*i);
b.y=c*i+e*h+(j*d-f*g);b.z=c*g+e*j+(f*i-h*d);return b};$.prototype.mulSelf$LQuaternion$=function(a){var b,c,d,e,f,h,g,j;this.t=a=(b=this.t)*(d=a.t)-((e=this.x)*(c=a.x)+(f=this.y)*(j=a.y)+(g=this.z)*(h=a.z));this.x=b*c+d*e+(f*h-g*j);this.y=b*j+d*f+(g*c-e*h);this.z=b*h+d*g+(e*j-f*c);return this};$.prototype.toMatrix$=function(){var a,b,c,d,e,f,h,g,j,i;a=2*(h=this.x)*h;b=2*(g=this.y)*g;c=2*(j=this.z)*j;d=2*h*g;e=2*h*j;f=2*g*j;h=2*h*(i=this.t);g=2*g*i;j=2*j*i;return new H([1-b-c,d+j,e-g,0,d-j,1-a-c,f+
h,0,e+g,f-h,1-a-b,0,0,0,0,1])};$.prototype.toString=function(){var a,b,c;a=this.x.toFixed(3);b=this.y.toFixed(3);c=this.z.toFixed(3);return this.t.toFixed(3)+" : ("+a+", "+b+", "+c+", )"};$.rotating$NNNN=function(a,b,c,d){var e;e=Math.cos(a/2);a=Math.sin(a/2);return new Ab(e,b*a,c*a,d*a)};var vc=$.rotating$NNNN;$.rotating$NLVector$=function(a,b){var c,d,e,f,h;c=b.x;d=b.y;e=b.z;f=Math.cos(a/2);h=Math.sin(a/2);return new Ab(f,c*h,d*h,e*h)};$.rotate$LVector$LVector$N=function(a,b,c){var d,e,f,h,g,j,
i,k,l,p;d=Math.cos(c/2);e=Math.sin(c/2);c=a.x;h=a.y;g=a.z;a=b.x*e;j=b.y*e;i=b.z*e;k=-b.x*e;l=-b.y*e;p=-b.z*e;b=0*d-(k*c+l*h+p*g);e=d*c+0*k+(l*g-p*h);f=d*h+0*l+(p*c-k*g);c=d*g+0*p+(k*h-l*c);return new m(b*a+d*e+(f*i-c*j),b*j+d*f+(c*a-e*i),b*i+d*c+(e*j-f*a))};I.prototype={};ic.prototype=new I;I.prototype.isMobile$=function(){return this._isMobile};I.loadImages$AS=function(a){var b,c,d;d=P.document.getElementById("tmp_canvas");d=d instanceof HTMLElement?d:null;d=(d instanceof HTMLCanvasElement?d:null).getContext("2d");
b=d instanceof CanvasRenderingContext2D?d:null;c=function(a){I.images[a].onload=function(){var c;c=I.images[a];I.isLoadedImage[a]=!0;b.drawImage(c,0,0);I.imageDatas[a]=b.getImageData(0,0,c.width,c.height)}};A.global.setTimeout(function(){var b,d,h;for(b=0;b<a.length;b++)d=a[b],h=P.document.createElement("img"),h=h instanceof HTMLImageElement?h:null,h.src=d,I.isLoadedImage[d]=!1,I.images[d]=h,c(d)},1E3)};var Qc=I.loadImages$AS;I.prototype.setSkyImage$S=function(a){this._skyImageSrc=a;this._skyImage=
I.images[a]};I.prototype.start$=function(){var a=this,b,c;b={_stopwatch:{_elapsedMsec:0,_startedMsec:null,_lastLapMsec:null},_recentlyMsecLog:[],_lastMsec:0,_fpsElement:null,_enabledHtmlLog:!1,_enabledConsoleLog:!0,_enabledHtmlLog:!1,_enabledConsoleLog:!1};Nc(b._stopwatch);this._isRunning=!0;c=function(){var d,e;Wc(b);d=b._lastMsec;a.onUpdate(d);e={_worldMatrix:new Cb,_matrixStack:new lc,camera:a.camera,_depth:3,modelList1:new nb,modelList2:new nb,modelList3:new nb,modelList4:new nb,modelList5:new nb,
_polygonList:null,_groupCenter:null,_ignoringZHidden:!1,backgroundColor:new za(90,135,158)};a._skyImage&&I.isLoadedImage[a._skyImageSrc]?(a.context.fillStyle="#"+e.backgroundColor.toHexString$(),a.context.fillRect(0,0,a._width,a._height),a.renderSkyImage$()):(a.context.fillStyle="#"+e.backgroundColor.toHexString$(),a.context.fillRect(0,0,a._width,a._height));a.onRender(e,d);e.modelList5.forEach$F$LRenderable$V$(function(b){b.draw$LEngine$(a)});e.modelList4.forEach$F$LRenderable$V$(function(b){b.draw$LEngine$(a)});
e.modelList3.forEach$F$LRenderable$V$(function(b){b.draw$LEngine$(a)});e.modelList2.forEach$F$LRenderable$V$(function(b){b.draw$LEngine$(a)});e.modelList1.forEach$F$LRenderable$V$(function(b){b.draw$LEngine$(a)});a._isRunning&&A.global.setTimeout(c,0)};A.global.setTimeout(function(){P.window.scrollTo(0,1)},500);A.global.setTimeout(c,0)};I.prototype.stop$=function(){this._isRunning=!1};I.prototype.renderSkyImage$=function(){var a,b,c,d,e,f,h,g,j,i;e=(d=this.camera).target;f=d.view;d=e.x-f.x;a=e.y-
f.y;e=e.z-f.z;a=-a;b=Math.atan2(d,e);c=Math.atan2(a,Math.sqrt(d*d+e*e));d=(e=this._skyImage).width;a=e.height;e=(f=this.camera).fovyX/3.141592653589793/2*d;f=e*f.aspectRatio;b=(b/3.141592653589793/2+0.5)*d-e/2;c=(c/3.141592653589793+0.5)*a-f/2;0>b&&(b+=d);0>c&&(c+=a);h=b+e>=d;g=c+f>=a;h&&g?(j=(d-b)/e,f=(a-c)/f,this.context.drawImage(this._skyImage,~~b,~~c,~~(d-b),~~(a-c),0,0,~~(this._width*j),~~(this._height*f)),0!==~~(b+e-d)&&this.context.drawImage(this._skyImage,0,~~c,~~(b+e-d),~~(a-c),~~((i=this._width)*
j),0,~~(i*(1-j)),~~(this._height*f))):h?(i=(d-b)/e,0!==~~(d-b)&&0!==~~(this._width*i)&&this.context.drawImage(this._skyImage,~~b,~~c,~~(d-b),~~f,0,0,~~(this._width*i),this._height),0!==~~(b+e-d)&&0!==~~(this._width*(1-i))&&this.context.drawImage(this._skyImage,0,~~c,~~(b+e-d),~~f,~~((j=this._width)*i),0,~~(j*(1-i)),this._height)):g?this.context.drawImage(this._skyImage,~~b,~~c,~~e,~~(a-c),0,0,this._width,~~(this._height*((a-c)/f))):this.context.drawImage(this._skyImage,~~b,~~c,~~e,~~f,0,0,this._width,
this._height)};I.prototype.setScreenMatrix$NN=function(a,b){var c,d,e,f,h,g,j,i,k,l,p,m,n,o,q,s,u,t,v;c=new H([1,0,0,a/2,0,1,0,b/2,0,0,1,0,0,0,0,1]);t=a/2;v=-b/2;d=c._m11;e=c._m12;f=c._m13;h=c._m14;g=c._m21;j=c._m22;i=c._m23;k=c._m24;l=c._m31;p=c._m32;m=c._m33;n=c._m34;o=c._m41;q=c._m42;s=c._m43;u=c._m44;c._m11=d*t+0*e+0*f+0*h;c._m12=0*d+e*v+0*f+0*h;c._m13=0*d+0*e+1*f+0*h;c._m14=0*d+0*e+0*f+1*h;c._m21=g*t+0*j+0*i+0*k;c._m22=0*g+j*v+0*i+0*k;c._m23=0*g+0*j+1*i+0*k;c._m24=0*g+0*j+0*i+1*k;c._m31=l*t+
0*p+0*m+0*n;c._m32=0*l+p*v+0*m+0*n;c._m33=0*l+0*p+1*m+0*n;c._m34=0*l+0*p+0*m+1*n;c._m41=o*t+0*q+0*s+0*u;c._m42=0*o+q*v+0*s+0*u;c._m43=0*o+0*q+1*s+0*u;c._m44=0*o+0*q+0*s+1*u;this.screenMatrix=c};I.prototype.updateMatrix$=function(){var a,b,c,d,e,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,B,E,T,A,X,C,S,K,W,M,D,Q,I,N,R,G;a=this.camera;b=a.view;c=a.target;d=a.upper;e=a.fovyX;f=a.nearZ;h=a.farZ;g=a.aspectRatio;c=new m(c.x-b.x,c.y-b.y,c.z-b.z);p=Math.sqrt((i=c.x)*i+(u=c.y)*u+(t=c.z)*t);i=1E-9>p?new m(0,
0,0):c.divSelf$N(p);d=new m((x=d.y)*(v=i.z)-(r=d.z)*(F=i.y),r*(y=i.x)-(z=d.x)*v,z*F-x*y);r=Math.sqrt((k=d.x)*k+(n=d.y)*n+(w=d.z)*w);k=1E-9>r?new m(0,0,0):d.divSelf$N(r);n=new m((T=i.y)*(q=k.z)-(o=i.z)*(E=k.y),o*(A=k.x)-(B=i.x)*q,B*E-T*A);o=Math.sqrt((l=n.x)*l+(X=n.y)*X+(C=n.z)*C);l=1E-9>o?new m(0,0,0):n.divSelf$N(o);b=new H([S=k.x,K=k.y,W=k.z,-(S*(D=b.x)+K*(I=b.y)+W*(N=b.z)),M=l.x,Q=l.y,s=l.z,-(M*D+Q*I+s*N),j=i.x,R=i.y,G=i.z,-(j*D+R*I+G*N),0,0,0,1]);e=1/Math.tan(e/2);h/=h-f;j=new H([e,0,0,0,0,e/g,
0,0,0,0,h,-h*f,0,0,1,0]);a.viewMatrix=b;a.projectionMatrix=j;f=(N=j._m11)*(C=b._m11)+(G=j._m12)*(l=b._m21)+(X=j._m13)*(R=b._m31)+(o=j._m14)*(s=b._m41);g=N*(e=b._m12)+G*(S=b._m22)+X*(K=b._m32)+o*(W=b._m42);h=N*(M=b._m13)+G*(D=b._m23)+X*(Q=b._m33)+o*(I=b._m43);b=N*(N=b._m14)+G*(G=b._m24)+X*(X=b._m34)+o*(k=b._m44);o=(B=j._m21)*C+(E=j._m22)*l+(T=j._m23)*R+(A=j._m24)*s;q=(n=j._m31)*C+(w=j._m32)*l+(r=j._m33)*R+(v=j._m34)*s;s=(z=j._m41)*C+(C=j._m42)*l+(l=j._m43)*R+(j=j._m44)*s;a.matrix=new H([f,g,h,b,o,
B*e+E*S+T*K+A*W,B*M+E*D+T*Q+A*I,B*N+E*G+T*X+A*k,q,n*e+w*S+r*K+v*W,n*M+w*D+r*Q+v*I,n*N+w*G+r*X+v*k,s,z*e+C*S+l*K+j*W,z*M+C*D+l*Q+j*I,z*N+C*G+l*X+j*k])};C.prototype={};Cc.prototype=new C;C.setDepth$LContext3D$I=function(a,b){if(!(1<=b&&5>=b)){debugger;throw Error("[jsx/engine.jsx:277] assertion failure");}a._depth=b};var Kb=C.setDepth$LContext3D$I;C.getDepth$LContext3D$=function(a){return a._depth};C.setBackgroundColor$LContext3D$LColor$=function(a,b){a.backgroundColor=b};C.pushMatrix$LContext3D$=function(a){a._matrixStack.prepend$LMatrix$(a._worldMatrix.copy$())};
C.popMatrix$LContext3D$=function(a){a._worldMatrix=a._matrixStack.removeFirst$()};C.resetMatrix$LContext3D$=function(a){a._worldMatrix=new Cb};C.translate$LContext3D$NNN=function(a,b,c,d){var e,f,h,g,j,i,k,l,p,m,n,o,q,s,u,t,a=a._worldMatrix;e=a._m11;f=a._m12;h=a._m13;g=a._m14;j=a._m21;i=a._m22;k=a._m23;l=a._m24;p=a._m31;m=a._m32;n=a._m33;o=a._m34;q=a._m41;s=a._m42;u=a._m43;t=a._m44;a._m11=1*e+0*f+0*h+0*g;a._m12=0*e+1*f+0*h+0*g;a._m13=0*e+0*f+1*h+0*g;a._m14=e*b+f*c+h*d+1*g;a._m21=1*j+0*i+0*k+0*l;a._m22=
0*j+1*i+0*k+0*l;a._m23=0*j+0*i+1*k+0*l;a._m24=j*b+i*c+k*d+1*l;a._m31=1*p+0*m+0*n+0*o;a._m32=0*p+1*m+0*n+0*o;a._m33=0*p+0*m+1*n+0*o;a._m34=p*b+m*c+n*d+1*o;a._m41=1*q+0*s+0*u+0*t;a._m42=0*q+1*s+0*u+0*t;a._m43=0*q+0*s+1*u+0*t;a._m44=q*b+s*c+u*d+1*t};C.scale$LContext3D$NNN=function(a,b,c,d){var e,f,h,g,j,i,k,l,m,r,n,o,q,s,u,t,a=a._worldMatrix;e=a._m11;f=a._m12;h=a._m13;g=a._m14;j=a._m21;i=a._m22;k=a._m23;l=a._m24;m=a._m31;r=a._m32;n=a._m33;o=a._m34;q=a._m41;s=a._m42;u=a._m43;t=a._m44;a._m11=e*b+0*f+0*
h+0*g;a._m12=0*e+f*c+0*h+0*g;a._m13=0*e+0*f+h*d+0*g;a._m14=0*e+0*f+0*h+1*g;a._m21=j*b+0*i+0*k+0*l;a._m22=0*j+i*c+0*k+0*l;a._m23=0*j+0*i+k*d+0*l;a._m24=0*j+0*i+0*k+1*l;a._m31=m*b+0*r+0*n+0*o;a._m32=0*m+r*c+0*n+0*o;a._m33=0*m+0*r+n*d+0*o;a._m34=0*m+0*r+0*n+1*o;a._m41=q*b+0*s+0*u+0*t;a._m42=0*q+s*c+0*u+0*t;a._m43=0*q+0*s+u*d+0*t;a._m44=0*q+0*s+0*u+1*t};C.rotate$LContext3D$LQuaternion$=function(a,b){var c,d,e,f,h,g,j,i,k,l,m,r,n,o,q,s,u,t,v,z,F,x,y,w,B,E;c=a._worldMatrix;d=2*(y=b.x)*y;e=2*(w=b.y)*w;t=
2*(B=b.z)*B;v=2*y*w;z=2*y*B;F=2*w*B;f=2*y*(y=b.t);h=2*w*y;x=2*B*y;B=1-e-t;w=v+x;y=z-h;v-=x;t=1-d-t;x=F+f;z+=h;F-=f;E=1-d-e;d=c._m11;e=c._m12;f=c._m13;h=c._m14;g=c._m21;j=c._m22;i=c._m23;k=c._m24;l=c._m31;m=c._m32;r=c._m33;n=c._m34;o=c._m41;q=c._m42;s=c._m43;u=c._m44;c._m11=d*B+e*v+f*z+0*h;c._m12=d*w+e*t+f*F+0*h;c._m13=d*y+e*x+f*E+0*h;c._m14=0*d+0*e+0*f+1*h;c._m21=g*B+j*v+i*z+0*k;c._m22=g*w+j*t+i*F+0*k;c._m23=g*y+j*x+i*E+0*k;c._m24=0*g+0*j+0*i+1*k;c._m31=l*B+m*v+r*z+0*n;c._m32=l*w+m*t+r*F+0*n;c._m33=
l*y+m*x+r*E+0*n;c._m34=0*l+0*m+0*r+1*n;c._m41=o*B+q*v+s*z+0*u;c._m42=o*w+q*t+s*F+0*u;c._m43=o*y+q*x+s*E+0*u;c._m44=0*o+0*q+0*s+1*u};C.beginGroup$LContext3D$LVector$=function(a,b){a._polygonList=new Eb;a._groupCenter=b;a._ignoringZHidden=!1};C.beginGroup$LContext3D$LVector$B=function(a,b,c){a._polygonList=new Eb;a._groupCenter=b;a._ignoringZHidden=c};C.renderPolygonGroup$LContext3D$ALVector$LColor$=function(a,b,c){b=new Mb(b,c);b.applyWorldMatrix$LMatrix$(a._worldMatrix);b.applyViewMatrix$LMatrix$(a.camera.viewMatrix);
b.isHidden$LCamera$(a.camera)||a._polygonList.prepend$LPolygon$(b)};var Ob=C.renderPolygonGroup$LContext3D$ALVector$LColor$;C.endGroup$LContext3D$=function(a){0!==a._polygonList.length&&Jb(a,new mc(a._polygonList,a._groupCenter,a._ignoringZHidden))};var gc=C.endGroup$LContext3D$;C.renderPolygon$LContext3D$ALVector$LColor$=function(a,b,c){Jb(a,new Mb(b,c))};C.renderBillboard$LContext3D$LVector$IIS=function(a,b,c,d,e){Jb(a,new oc(b,c,d,e))};var Uc=C.renderBillboard$LContext3D$LVector$IIS;C.renderTexture$LContext3D$ALVector$SIIII=
function(a,b,c,d,e,f,h){Jb(a,new ac(b,c,d,e,f,h))};var Vc=C.renderTexture$LContext3D$ALVector$SIIII;C.renderTexture$LContext3D$ALVector$S=function(a,b,c){Jb(a,new nc(b,c))};C.renderModel$LContext3D$LRenderable$=function(a,b){b.applyWorldMatrix$LMatrix$(a._worldMatrix);b.applyViewMatrix$LMatrix$(a.camera.viewMatrix);if(!b.isHidden$LCamera$(a.camera))switch(a._depth){case 1:Pb(a,a.modelList1,b);break;case 2:Pb(a,a.modelList2,b);break;case 3:Pb(a,a.modelList3,b);break;case 4:Pb(a,a.modelList4,b);break;
case 5:Pb(a,a.modelList5,b)}};var Jb=C.renderModel$LContext3D$LRenderable$;C.insertModelByZValue$LContext3D$LList$Renderable$E$LRenderable$=function(a,b,c){var d,a=!1;for(d=b.head;null!=d;d=d._next)if(d.value.vCenter.z<c.vCenter.z){b.insertBefore$LNode$Renderable$E$LRenderable$(d,c);a=!0;break}a||b.append$LRenderable$(c)};var Pb=C.insertModelByZValue$LContext3D$LList$Renderable$E$LRenderable$;Ib.prototype={};kc.prototype=new Ib;Ib.prototype.move$LVector$=function(a){var b,c,d,e,f;c=this.rotatingMatrix;
a=c._m11*(e=a.x)+c._m12*(b=a.y)+c._m13*(d=a.z)+c._m14*(f=a.w);b=new R(a,c._m21*e+c._m22*b+c._m23*d+c._m24*f,c._m31*e+c._m32*b+c._m33*d+c._m34*f,c._m41*e+c._m42*b+c._m43*d+c._m44*f);d=this.view;d.x+=c=b.x;d.y+=e=b.y;d.z+=d=b.z;b=this.target;b.x+=c;b.y+=e;b.z+=d};Ib.prototype.rotateY$N=function(a){var b,c,d,e,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,B,E,A,C;b=this.target;c=this.view;b=new m(b.x-c.x,b.y-c.y,b.z-c.z);i=Math.sin(a);k=Math.cos(a);c=k*(l=b.x)+0*(p=b.y)+i*(r=b.z)+0*(n=b.w);d=0*l+0*p+0*r+
1*n;b.x=c/d;b.y=(0*l+1*p+0*r+0*n)/d;b.z=(-i*l+0*p+k*r+0*n)/d;b.w=1;c=this.view;b.x+=c.x;b.y+=c.y;b.z+=c.z;this.target=b;b=Math.sin(a);a=Math.cos(a);a=new H([a,0,b,0,0,1,0,0,-b,0,a,0,0,0,0,1]);e=this.rotatingMatrix;f=a._m11;h=a._m12;g=a._m13;j=a._m14;b=a._m21;c=a._m22;d=a._m23;i=a._m24;k=a._m31;l=a._m32;p=a._m33;r=a._m34;n=a._m41;o=a._m42;q=a._m43;s=a._m44;a._m11=f*(u=e._m11)+h*(t=e._m21)+g*(v=e._m31)+j*(z=e._m41);a._m12=f*(F=e._m12)+h*(x=e._m22)+g*(y=e._m32)+j*(w=e._m42);a._m13=f*(B=e._m13)+h*(E=
e._m23)+g*(A=e._m33)+j*(C=e._m43);a._m14=f*(f=e._m14)+h*(h=e._m24)+g*(g=e._m34)+j*(e=e._m44);a._m21=b*u+c*t+d*v+i*z;a._m22=b*F+c*x+d*y+i*w;a._m23=b*B+c*E+d*A+i*C;a._m24=b*f+c*h+d*g+i*e;a._m31=k*u+l*t+p*v+r*z;a._m32=k*F+l*x+p*y+r*w;a._m33=k*B+l*E+p*A+r*C;a._m34=k*f+l*h+p*g+r*e;a._m41=n*u+o*t+q*v+s*z;a._m42=n*F+o*x+q*y+s*w;a._m43=n*B+o*E+q*A+s*C;a._m44=n*f+o*h+q*g+s*e;this.rotatingMatrix=a};Ib.prototype.updateMatrix$=function(){var a,b,c,d,e,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,B,E,A,C,D,G,S,K,
I,M,R,Q,J,N,O;a=this.view;b=this.target;c=this.upper;d=this.fovyX;e=this.nearZ;f=this.farZ;h=this.aspectRatio;b=new m(b.x-a.x,b.y-a.y,b.z-a.z);l=Math.sqrt((j=b.x)*j+(s=b.y)*s+(u=b.z)*u);j=1E-9>l?new m(0,0,0):b.divSelf$N(l);c=new m((F=c.y)*(t=j.z)-(p=c.z)*(z=j.y),p*(x=j.x)-(v=c.x)*t,v*z-F*x);p=Math.sqrt((i=c.x)*i+(r=c.y)*r+(y=c.z)*y);i=1E-9>p?new m(0,0,0):c.divSelf$N(p);r=new m((E=j.y)*(o=i.z)-(n=j.z)*(B=i.y),n*(A=i.x)-(w=j.x)*o,w*B-E*A);n=Math.sqrt((k=r.x)*k+(C=r.y)*C+(D=r.z)*D);k=1E-9>n?new m(0,
0,0):r.divSelf$N(n);a=new H([G=i.x,S=i.y,K=i.z,-(G*(M=a.x)+S*(Q=a.y)+K*(J=a.z)),I=k.x,R=k.y,q=k.z,-(I*M+R*Q+q*J),g=j.x,N=j.y,O=j.z,-(g*M+N*Q+O*J),0,0,0,1]);d=1/Math.tan(d/2);f/=f-e;g=new H([d,0,0,0,0,d/h,0,0,0,0,f,-f*e,0,0,1,0]);this.viewMatrix=a;this.projectionMatrix=g;e=(J=g._m11)*(D=a._m11)+(O=g._m12)*(k=a._m21)+(C=g._m13)*(N=a._m31)+(n=g._m14)*(q=a._m41);h=J*(d=a._m12)+O*(G=a._m22)+C*(S=a._m32)+n*(K=a._m42);f=J*(I=a._m13)+O*(M=a._m23)+C*(R=a._m33)+n*(Q=a._m43);a=J*(J=a._m14)+O*(O=a._m24)+C*(C=
a._m34)+n*(i=a._m44);n=(w=g._m21)*D+(B=g._m22)*k+(E=g._m23)*N+(A=g._m24)*q;o=(r=g._m31)*D+(y=g._m32)*k+(p=g._m33)*N+(t=g._m34)*q;q=(v=g._m41)*D+(D=g._m42)*k+(k=g._m43)*N+(g=g._m44)*q;this.matrix=new H([e,h,f,a,n,w*d+B*G+E*S+A*K,w*I+B*M+E*R+A*Q,w*J+B*O+E*C+A*i,o,r*d+y*G+p*S+t*K,r*I+y*M+p*R+t*Q,r*J+y*O+p*C+t*i,q,v*d+D*G+k*S+g*K,v*I+D*M+k*R+g*Q,v*J+D*O+k*C+g*i])};Hb.prototype={};za.prototype=new Hb;Hb.prototype._to2DigitHex$I=function(a){a=Math.floor(a).toString(16);1===a.length&&(a="0"+a);return a};
Hb.prototype.toHexString$=function(){return this._to2DigitHex$I(this.r)+this._to2DigitHex$I(this.g)+this._to2DigitHex$I(this.b)};Hb.prototype.toString=function(){return"#"+this._to2DigitHex$I(this.r)+this._to2DigitHex$I(this.g)+this._to2DigitHex$I(this.b)};wb.prototype={};Dc.prototype=new wb;wb.isHiddenXY$ALVector$LEngine$=function(a,b){var c,d,e,f,h;c=0;for(h=a.length;c<h;c++)if(d=a[c],-0<(e=d.x)&&e<b._width+0&&-0<(f=d.y)&&f<b._height+0)return!1;return!0};var rc=wb.isHiddenXY$ALVector$LEngine$;ob.prototype=
new wb;Mb.prototype=new ob;ob.prototype.applyWorldMatrix$LMatrix$=function(a){var b,c,d,e,f,h,g,j,i;for(b=0;b<this.vertices.length;b++)c=this.vertices[b],d=a._m11*(h=c.x)+a._m12*(g=c.y)+a._m13*(j=c.z)+a._m14*(i=c.w),e=a._m21*h+a._m22*g+a._m23*j+a._m24*i,f=a._m31*h+a._m32*g+a._m33*j+a._m34*i,h=a._m41*h+a._m42*g+a._m43*j+a._m44*i,c.x=d/h,c.y=e/h,c.z=f/h,c.w=1;this.updateCenter$()};ob.prototype.applyViewMatrix$LMatrix$=function(a){var b,c,d,e,f,h,g,j,i,k,l,p;b=[];for(c=p=l=k=0;c<this.vertices.length;c++)d=
this.vertices[c],d=a._m11*(h=d.x)+a._m12*(g=d.y)+a._m13*(j=d.z)+a._m14*(i=d.w),e=a._m21*h+a._m22*g+a._m23*j+a._m24*i,f=a._m31*h+a._m32*g+a._m33*j+a._m34*i,h=a._m41*h+a._m42*g+a._m43*j+a._m44*i,d=new R(d,e,f,h),b.push(d),k+=d.x,l+=d.y,p+=d.z;a=this.vertices.length;this.vCenter=new m(k/a,l/a,p/a);this.vVertices=b};ob.prototype.isHidden$LCamera$=function(a){var b;return a.nearZ<(b=this.vCenter.z)&&b<a.farZ?!1:!0};ob.prototype.move$LVector$=function(a){var b,c;for(b=0;b<this.vertices.length;b++)c=this.vertices[b],
c.x+=a.x,c.y+=a.y,c.z+=a.z;this.updateCenter$()};ob.prototype.updateCenter$=function(){var a,b,c,d,e;for(a=e=d=c=0;a<this.vertices.length;a++)b=this.vertices[a],c+=b.x,d+=b.y,e+=b.z;a=this.vertices.length;this.center=new m(c/a,d/a,e/a)};ob.prototype.toString=function(){var a,b;a="[";for(b=0;b<this.vertices.length;b++)a+=this.vertices[b].toString()+",";return a+"]"};ob.prototype.draw$LEngine$=function(a){var b,c,d,e,f,h,g,j,i,k,l,p,r,n,o;b=a.context;c=this.vertices.length;d=this.vVertices;e=this._color;
this._enabledLighting&&(f=this.vCenter,g=d[0],i=g.x-f.x,o=g.y-f.y,l=g.z-f.z,g=d[1],g=new m(g.x-f.x,g.y-f.y,g.z-f.z),k=(n=g.y)*l-(r=g.z)*o,l=r*i-(r=g.x)*l,k=g.x=k,l=g.y=l,i=g.z=r*o-n*i,i=Math.sqrt(k*k+l*l+i*i),g=1E-9>i?new m(0,0,0):g.divSelf$N(i),i=Math.sqrt((h=f.x)*h+(j=f.y)*j+(p=f.z)*p),f=1E-9>i?new m(0,0,0):new m(f.x/i,f.y/i,f.z/i),j=g.x*f.x+g.y*f.y+g.z*f.z,f=(0.5599999999999999*j+0.5)*e.r,h=(0.5599999999999999*j+0.5)*e.g,e=(0.5599999999999999*j+0.5)*e.b,e=new za(255<=f?255:f,255<=h?255:h,255<=
e?255:e));for(f=0;f<c;f++)h=d[f],i=a.camera.projectionMatrix,j=i._m11*(o=h.x)+i._m12*(n=h.y)+i._m13*(r=h.z)+i._m14*(k=h.w),p=i._m21*o+i._m22*n+i._m23*r+i._m24*k,g=i._m31*o+i._m32*n+i._m33*r+i._m34*k,i=i._m41*o+i._m42*n+i._m43*r+i._m44*k,h.x=j/i,h.y=p/i,h.z=g/i,h.w=1;for(f=0;f<c;f++)h=d[f],i=a.screenMatrix,j=i._m11*(o=h.x)+i._m12*(n=h.y)+i._m13*(r=h.z)+i._m14*(k=h.w),p=i._m21*o+i._m22*n+i._m23*r+i._m24*k,g=i._m31*o+i._m32*n+i._m33*r+i._m34*k,i=i._m41*o+i._m42*n+i._m43*r+i._m44*k,h.x=j/i,h.y=p/i,h.z=
g/i,h.w=1;if(rc(d,a))return!1;f=0;for(j=d.length;f<j;f++)if(a=(f+1)%j,h=(f+2)%j,0>Xc(d[a].x-d[f].x,d[a].y-d[f].y,d[h].x-d[f].x,d[h].y-d[f].y))return!1;e="#"+(e._to2DigitHex$I(e.r)+e._to2DigitHex$I(e.g)+e._to2DigitHex$I(e.b));b.strokeStyle=e;for(f=0;f<c;f++)b.beginPath(),b.moveTo(d[f].x,d[f].y),b.lineTo(d[(f+1)%c].x,d[(f+1)%c].y),b.stroke();b.fillStyle=e;b.beginPath();for(f=0;f<c;f++)e=d[f].x,a=d[f].y,b.lineTo(e,a);b.closePath();b.fill();return!0};tb.prototype=new wb;Ec.prototype=new tb;mc.prototype=
new tb;tb.prototype.applyWorldMatrix$LMatrix$=function(a){var b,c,d,e,f,h,g,j;b=this.center;c=a._m11*(f=b.x)+a._m12*(h=b.y)+a._m13*(g=b.z)+a._m14*(j=b.w);d=a._m21*f+a._m22*h+a._m23*g+a._m24*j;e=a._m31*f+a._m32*h+a._m33*g+a._m34*j;a=a._m41*f+a._m42*h+a._m43*g+a._m44*j;b.x=c/a;b.y=d/a;b.z=e/a;b.w=1};tb.prototype.applyViewMatrix$LMatrix$=function(a){var b,c,d,e,f;b=this.center;b=a._m11*(c=b.x)+a._m12*(d=b.y)+a._m13*(e=b.z)+a._m14*(f=b.w);this.vCenter=new R(b,a._m21*c+a._m22*d+a._m23*e+a._m24*f,a._m31*
c+a._m32*d+a._m33*e+a._m34*f,a._m41*c+a._m42*d+a._m43*e+a._m44*f)};tb.prototype.isHidden$LCamera$=function(a){return this._ignoringZHidden?!1:a.nearZ<this.vCenter.z&&this.vCenter.z<a.farZ?!1:!0};tb.prototype.draw$LEngine$=function(a){this.polygons.forEach$F$LPolygon$V$(function(b){b.isHidden$LCamera$(a.camera)||b.draw$LEngine$(a)});return!0};xb.prototype=new ob;nc.prototype=new xb;ac.prototype=new xb;xb.prototype.applyWorldMatrix$LMatrix$=function(a){var b,c,d,e,f,h,g,j,i;for(b=0;b<this.vertices.length;b++)c=
this.vertices[b],d=a._m11*(h=c.x)+a._m12*(g=c.y)+a._m13*(j=c.z)+a._m14*(i=c.w),e=a._m21*h+a._m22*g+a._m23*j+a._m24*i,f=a._m31*h+a._m32*g+a._m33*j+a._m34*i,h=a._m41*h+a._m42*g+a._m43*j+a._m44*i,c.x=d/h,c.y=e/h,c.z=f/h,c.w=1;b=this.center;c=a._m11*(f=b.x)+a._m12*(h=b.y)+a._m13*(g=b.z)+a._m14*(j=b.w);d=a._m21*f+a._m22*h+a._m23*g+a._m24*j;e=a._m31*f+a._m32*h+a._m33*g+a._m34*j;a=a._m41*f+a._m42*h+a._m43*g+a._m44*j;b.x=c/a;b.y=d/a;b.z=e/a;b.w=1};xb.prototype.applyViewMatrix$LMatrix$=function(a){var b,c,
d,e,f;b=[];for(c=0;c<this.vertices.length;c++)b.push(this.vertices[c].transform$LMatrix$(a));this.vVertices=b;d=this.center;d=a._m11*(b=d.x)+a._m12*(c=d.y)+a._m13*(e=d.z)+a._m14*(f=d.w);this.vCenter=new R(d,a._m21*b+a._m22*c+a._m23*e+a._m24*f,a._m31*b+a._m32*c+a._m33*e+a._m34*f,a._m41*b+a._m42*c+a._m43*e+a._m44*f)};xb.prototype.isHidden$LCamera$=function(a){var b;return a.nearZ<(b=this.vCenter.z)&&b<a.farZ?!1:!0};xb.prototype.draw$LEngine$=function(a){var b=this,c,d,e,f,h,g,j,i,k,l,p,r,n,o,q,s,u,
t,v,z,F,x,y,w,B,E,A,C,D,G,S,K,J,M,O,Q,H,N,P,$,za,Ia,Na,L,Ta,Ua,Va,vb,rb,Wa,Xa,Ya,Za,$a,Ja,Ka,La,ab,bb,Oa,cb,Pa,db,ka,la,Qa,Ra,eb,Sa,Da,Ma,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,aa,ba,wa,U,ma,na,xa,oa,ya,ca,da,ga,ha,ia,ja,Y,Z,Aa,Ba,Ca,fb,gb,hb,ib,jb,nb,ob,pb,qb,wb,sb,tb;if(!I.isLoadedImage[this._src])return!1;c=a.context;d=(vb=this.vertices)[3];e=vb[0];f=vb[1];h=vb[2];p=a.screenMatrix;S=(rb=a.camera).projectionMatrix;K=rb.viewMatrix;J=(Wa=S._m11)*($a=K._m11)+(Xa=S._m12)*(Ja=K._m21)+(Ya=S._m13)*(Ka=
K._m31)+(Za=S._m14)*(La=K._m41);M=Wa*(bb=K._m12)+Xa*(cb=K._m22)+Ya*(db=K._m32)+Za*(la=K._m42);O=Wa*(Qa=K._m13)+Xa*(Ra=K._m23)+Ya*(eb=K._m33)+Za*(Sa=K._m43);Q=Wa*(Da=K._m14)+Xa*(Ma=K._m24)+Ya*(Ea=K._m34)+Za*(Fa=K._m44);H=(ab=S._m21)*$a+(Oa=S._m22)*Ja+(Pa=S._m23)*Ka+(ka=S._m24)*La;N=ab*bb+Oa*cb+Pa*db+ka*la;P=ab*Qa+Oa*Ra+Pa*eb+ka*Sa;$=ab*Da+Oa*Ma+Pa*Ea+ka*Fa;za=(ea=S._m31)*$a+(fa=S._m32)*Ja+(Ga=S._m33)*Ka+(Ha=S._m34)*La;Ia=ea*bb+fa*cb+Ga*db+Ha*la;Na=ea*Qa+fa*Ra+Ga*eb+Ha*Sa;L=ea*Da+fa*Ma+Ga*Ea+Ha*Fa;
Ta=(pa=S._m41)*$a+(qa=S._m42)*Ja+(ra=S._m43)*Ka+(sa=S._m44)*La;Ua=pa*bb+qa*cb+ra*db+sa*la;Va=pa*Qa+qa*Ra+ra*eb+sa*Sa;tb=pa*Da+qa*Ma+ra*Ea+sa*Fa;r=(ta=p._m11)*J+(ua=p._m12)*H+(va=p._m13)*za+(aa=p._m14)*Ta;n=ta*M+ua*N+va*Ia+aa*Ua;o=ta*O+ua*P+va*Na+aa*Va;q=ta*Q+ua*$+va*L+aa*tb;s=(ba=p._m21)*J+(wa=p._m22)*H+(U=p._m23)*za+(ma=p._m24)*Ta;u=ba*M+wa*N+U*Ia+ma*Ua;t=ba*O+wa*P+U*Na+ma*Va;v=ba*Q+wa*$+U*L+ma*tb;z=(na=p._m31)*J+(xa=p._m32)*H+(oa=p._m33)*za+(ya=p._m34)*Ta;F=na*M+xa*N+oa*Ia+ya*Ua;x=na*O+xa*P+oa*
Na+ya*Va;y=na*Q+xa*$+oa*L+ya*tb;w=(ca=p._m41)*J+(da=p._m42)*H+(ga=p._m43)*za+(ha=p._m44)*Ta;B=ca*M+da*N+ga*Ia+ha*Ua;E=ca*O+da*P+ga*Na+ha*Va;sb=ca*Q+da*$+ga*L+ha*tb;A=r*(ia=d.x)+n*(ja=d.y)+o*(Y=d.z)+q*(Z=d.w);g=new R(A,s*ia+u*ja+t*Y+v*Z,z*ia+F*ja+x*Y+y*Z,w*ia+B*ja+E*Y+sb*Z);C=r*(Aa=e.x)+n*(Ba=e.y)+o*(Ca=e.z)+q*(fb=e.w);j=new R(C,s*Aa+u*Ba+t*Ca+v*fb,z*Aa+F*Ba+x*Ca+y*fb,w*Aa+B*Ba+E*Ca+sb*fb);D=r*(gb=f.x)+n*(hb=f.y)+o*(ib=f.z)+q*(jb=f.w);i=new R(D,s*gb+u*hb+t*ib+v*jb,z*gb+F*hb+x*ib+y*jb,w*gb+B*hb+E*ib+
sb*jb);G=r*(nb=h.x)+n*(ob=h.y)+o*(pb=h.z)+q*(qb=h.w);k=new R(G,s*nb+u*ob+t*pb+v*qb,z*nb+F*ob+x*pb+y*qb,w*nb+B*ob+E*pb+sb*qb);if(rc([g,j,i,k],a))return!1;l=function(a,d,e,f,g,h,i,j,k,p,A,C,D,G){var I,J,S,N,O,T,K,M,Q,H,L,P,V,X,W,$,ca,da,ga,ha,ia,ja,Y,Z,aa,ba,U,ma,na,oa,pa,qa,ra,sa,ta,ua,va,wa,xa,ya,za,Aa,Ba,Ca,Da,Ea,Fa,ea,fa,Ga,Ha,kb,Ia,Ma,Na,Oa,Pa,ka,la,Qa,Ra,Sa,Wa,Xa,Ya,Za,$a,Ja,Ka,La,Ta,Ua,Va,ab,bb,cb,db,eb,fb,gb,hb,ib,jb,lb,mb,nb,ob,pb,qb,rb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Ib,Hb,Jb;I=
function(a,b){return Math.sqrt(a*a+b*b)};J=I(j.x-i.x,j.y-i.y);S=I(k.x-h.x,k.y-h.y);N=I(h.x-i.x,h.y-i.y);O=I(k.x-j.x,k.y-j.y);T=J/S;K=O/N;1>T&&(T=1/T);1>K&&(K=1/K);M=1.01<T;Q=1.01<K;p<=b._minDiv||p<=b._maxDiv&&M&&Q?(Y=new m(d.x+g.x,d.y+g.y,d.z+g.z),Y.x/=2,Y.y/=2,Y.z/=2,H=Y,Z=new m(e.x+f.x,e.y+f.y,e.z+f.z),Z.x/=2,Z.y/=2,Z.z/=2,L=Z,aa=new m(d.x+e.x,d.y+e.y,d.z+e.z),aa.x/=2,aa.y/=2,aa.z/=2,P=aa,ba=new m(g.x+f.x,g.y+f.y,g.z+f.z),ba.x/=2,ba.y/=2,ba.z/=2,V=ba,U=new m(d.x+f.x,d.y+f.y,d.z+f.z),U.x/=2,U.y/=
2,U.z/=2,ma=r*(Ja=H.x)+n*(Ka=H.y)+o*(La=H.z)+q*(Ta=H.w),na=s*Ja+u*Ka+t*La+v*Ta,oa=z*Ja+F*Ka+x*La+y*Ta,pa=w*Ja+B*Ka+E*La+sb*Ta,X=new R(ma,na,oa,pa),qa=r*(Ua=L.x)+n*(Va=L.y)+o*(ab=L.z)+q*(bb=L.w),ra=s*Ua+u*Va+t*ab+v*bb,sa=z*Ua+F*Va+x*ab+y*bb,ta=w*Ua+B*Va+E*ab+sb*bb,W=new R(qa,ra,sa,ta),ua=r*(cb=P.x)+n*(db=P.y)+o*(eb=P.z)+q*(fb=P.w),va=s*cb+u*db+t*eb+v*fb,wa=z*cb+F*db+x*eb+y*fb,xa=w*cb+B*db+E*eb+sb*fb,$=new R(ua,va,wa,xa),ya=r*(gb=V.x)+n*(hb=V.y)+o*(ib=V.z)+q*(jb=V.w),za=s*gb+u*hb+t*ib+v*jb,Aa=z*gb+
F*hb+x*ib+y*jb,Ba=w*gb+B*hb+E*ib+sb*jb,ca=new R(ya,za,Aa,Ba),Ca=r*(lb=U.x)+n*(mb=U.y)+o*(nb=U.z)+q*(ob=U.w),Da=s*lb+u*mb+t*nb+v*ob,Ea=z*lb+F*mb+x*nb+y*ob,Fa=w*lb+B*mb+E*nb+sb*ob,da=new R(Ca,Da,Ea,Fa),l(a,d,P,U,H,h,$,da,X,p+1,A,C,D/2,G/2),l(a,P,e,L,U,$,i,W,da,p+1,A,C+G/2,D/2,G/2),l(a,H,U,V,g,X,da,ca,k,p+1,A+D/2,C,D/2,G/2),l(a,U,L,f,V,da,W,j,ca,p+1,A+D/2,C+G/2,D/2,G/2)):p<=b._maxVerticalDiv&&Q?(ea=new m(d.x+g.x,d.y+g.y,d.z+g.z),ea.x/=2,ea.y/=2,ea.z/=2,H=ea,fa=new m(e.x+f.x,e.y+f.y,e.z+f.z),fa.x/=2,
fa.y/=2,fa.z/=2,L=fa,Ga=r*(pb=H.x)+n*(qb=H.y)+o*(rb=H.z)+q*(tb=H.w),Ha=s*pb+u*qb+t*rb+v*tb,kb=z*pb+F*qb+x*rb+y*tb,Ia=w*pb+B*qb+E*rb+sb*tb,X=new R(Ga,Ha,kb,Ia),Ma=r*(ub=L.x)+n*(vb=L.y)+o*(wb=L.z)+q*(xb=L.w),Na=s*ub+u*vb+t*wb+v*xb,Oa=z*ub+F*vb+x*wb+y*xb,Pa=w*ub+B*vb+E*wb+sb*xb,W=new R(Ma,Na,Oa,Pa),l(a,d,e,L,H,h,i,W,X,p+1,A,C,D/2,G),l(a,H,L,f,g,X,W,j,k,p+1,A+D/2,C,D/2,G)):p<=b._maxHorizontalDiv&&M?(ka=new m(d.x+e.x,d.y+e.y,d.z+e.z),ka.x/=2,ka.y/=2,ka.z/=2,P=ka,la=new m(g.x+f.x,g.y+f.y,g.z+f.z),la.x/=
2,la.y/=2,la.z/=2,V=la,Qa=r*(yb=P.x)+n*(zb=P.y)+o*(Ab=P.z)+q*(Bb=P.w),Ra=s*yb+u*zb+t*Ab+v*Bb,Sa=z*yb+F*zb+x*Ab+y*Bb,Wa=w*yb+B*zb+E*Ab+sb*Bb,$=new R(Qa,Ra,Sa,Wa),Xa=r*(Cb=V.x)+n*(Db=V.y)+o*(Eb=V.z)+q*(Fb=V.w),Ya=s*Cb+u*Db+t*Eb+v*Fb,Za=z*Cb+F*Db+x*Eb+y*Fb,$a=w*Cb+B*Db+E*Eb+sb*Fb,ca=new R(Xa,Ya,Za,$a),l(a,d,P,V,g,h,$,ca,k,p+1,A,C,D,G/2),l(a,P,e,f,V,$,i,j,ca,p+1,A,C+G/2,D,G/2)):(ga=((Ib=k.x)-(Hb=h.x))/D,ha=((Jb=i.y)-(Gb=h.y))/G,ia=(k.y-Gb)/(Ib-Hb),ja=(i.x-Hb)/(Jb-Gb),c.transform(1,0,0,1,Hb,Gb),c.transform(1,
ia,ja,1,0,0),c.transform(ga,0,0,ha,0,0),c.drawImage(a,~~A,~~C,~~D,~~G,0,0,Math.ceil(D),Math.ceil(G)),c.setTransform(1,0,0,1,0,0))};l(wb=this._image,d,e,f,h,g,j,i,k,1,0,0,wb.width,wb.height);return!0};Db.prototype=new wb;oc.prototype=new Db;Db.prototype.applyWorldMatrix$LMatrix$=function(a){var b,c,d,e,f,h,g,j;b=this.center;c=a._m11*(f=b.x)+a._m12*(h=b.y)+a._m13*(g=b.z)+a._m14*(j=b.w);d=a._m21*f+a._m22*h+a._m23*g+a._m24*j;e=a._m31*f+a._m32*h+a._m33*g+a._m34*j;a=a._m41*f+a._m42*h+a._m43*g+a._m44*j;
b.x=c/a;b.y=d/a;b.z=e/a;b.w=1};Db.prototype.applyViewMatrix$LMatrix$=function(a){var b,c,d,e,f;b=this.center;b=a._m11*(c=b.x)+a._m12*(d=b.y)+a._m13*(e=b.z)+a._m14*(f=b.w);this.vCenter=new R(b,a._m21*c+a._m22*d+a._m23*e+a._m24*f,a._m31*c+a._m32*d+a._m33*e+a._m34*f,a._m41*c+a._m42*d+a._m43*e+a._m44*f)};Db.prototype.isHidden$LCamera$=function(a){var b;return a.nearZ<(b=this.vCenter.z)&&b<a.farZ?!1:!0};Db.prototype.draw$LEngine$=function(a){var b,c,d,e,f,h,g,j,i,k,l,m,r,n,o,q,s,u,t,v,z,A,x,y,w,B,E,C,
D,G,H,J,K;if(!I.isLoadedImage[this._src])return!1;b=a.context;h=a.screenMatrix;g=a.camera.projectionMatrix;e=(l=h._m11)*(v=g._m11)+(k=h._m12)*(z=g._m21)+(i=h._m13)*(A=g._m31)+(j=h._m14)*(q=g._m41);d=l*(s=g._m12)+k*(x=g._m22)+i*(y=g._m32)+j*(w=g._m42);f=l*(u=g._m13)+k*(B=g._m23)+i*(E=g._m33)+j*(C=g._m43);g=l*(c=g._m14)+k*(t=g._m24)+i*(D=g._m34)+j*(G=g._m44);j=(l=h._m21)*v+(m=h._m22)*z+(r=h._m23)*A+(n=h._m24)*q;i=l*s+m*x+r*y+n*w;k=l*u+m*B+r*E+n*C;l=l*c+m*t+r*D+n*G;m=(o=h._m31)*v+(H=h._m32)*z+(J=h._m33)*
A+(K=h._m34)*q;r=o*s+H*x+J*y+K*w;n=o*u+H*B+J*E+K*C;o=o*c+H*t+J*D+K*G;q=(H=h._m41)*v+(v=h._m42)*z+(z=h._m43)*A+(h=h._m44)*q;s=H*s+v*x+z*y+h*w;u=H*u+v*B+z*E+h*C;B=H*c+v*t+z*D+h*G;c=this.vCenter;E=this._width/2;C=this._height/2;E=c.x-E;C=c.y-C;x=c.z-0;t=this.vCenter;t=e*(c=t.x)+d*(y=t.y)+f*(w=t.z)+g*(D=t.w);c=new R(t,j*c+i*y+k*w+l*D,m*c+r*y+n*w+o*D,q*c+s*y+u*w+B*D);d=new R(e*E+d*C+f*x+1*g,j*E+i*C+k*x+1*l,m*E+r*C+n*x+1*o,q*E+s*C+u*x+1*B);e=d.x-c.x;d=d.y-c.y;if(rc([c],a))return!1;a=2*(e/(f=this._image).width);
f=2*(d/f.height);b.setTransform(a,0,0,f,0,0);b.drawImage(this._image,~~((c.x-e)/a),~~((c.y-d)/f));b.setTransform(1,0,0,1,0,0);return!0};Na.prototype={};(function(){this.tail=this.head=null;this.length=0}).prototype=new Na;Lb.prototype=new Na;Na.prototype.prepend$LVector$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.tail=this.head=a:(a._next=b=this.head,this.head=b._prev=a);this.length++;return this};Na.prototype.append$LVector$=function(a){var b,a={value:a,_prev:null,_next:null};
0===this.length?this.head=a:(a._prev=b=this.tail,b._next=a);this.tail=a;this.length++;return this};Na.prototype.remove$LNode$Vector$E$=function(a){a._prev?a._prev._next=a._next:this.head=a._next;a._next?a._next._prev=a._prev:this.tail=a._prev;return a.value};Na.prototype.removeFirst$=function(){var a,b;a=this.head;this.head=b=a._next;null!=b&&(a._next._prev=null);this.length--;return a.value};Na.prototype.removeLast$=function(){var a,b;a=this.tail;this.tail=b=a._prev;null!=b&&(a._prev._next=null);
this.length--;return a.value};Na.prototype.insertAfter$LNode$Vector$E$LVector$=function(a,b){var c,d;c={value:b,_prev:null,_next:null};null==a._next?(c._prev=a,this.tail=a._next=c):(c._next=d=a._next,c._prev=a,d._prev=c,a._next=c);this.length++;return this};Na.prototype.insertBefore$LNode$Vector$E$LVector$=function(a,b){var c,d;c={value:b,_prev:null,_next:null};null==a._prev?(c._next=a,this.head=a._prev=c):(c._next=a,c._prev=d=a._prev,d._next=c,a._prev=c);this.length++;return this};Na.prototype.forEach$F$LVector$V$=
function(a){var b;for(b=this.head;b;b=b._next)a(b.value)};Na.prototype.toString=function(){var a,b;a="list : [";for(b=this.head;null!=b;b=b._next)a+=" "+b.value.toString()+",";return a+"]"};bc.prototype={};(function(a){this.value=a;this._next=this._prev=null}).prototype=new bc;bc.prev$LNode$Vector$E$=function(a){return a._prev};bc.next$LNode$Vector$E$=function(a){return a._next};Ta.prototype={};lc.prototype=new Ta;(function(a){var b,c;this.tail=this.head=null;this.length=0;b=a.length;for(c=0;c<b;c++)this.prepend$LMatrix$(a.pop())}).prototype=
new Ta;Ta.prototype.prepend$LMatrix$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.tail=this.head=a:(a._next=b=this.head,this.head=b._prev=a);this.length++;return this};Ta.prototype.append$LMatrix$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.head=a:(a._prev=b=this.tail,b._next=a);this.tail=a;this.length++;return this};Ta.prototype.remove$LNode$Matrix$E$=function(a){a._prev?a._prev._next=a._next:this.head=a._next;a._next?a._next._prev=a._prev:
this.tail=a._prev;return a.value};Ta.prototype.removeFirst$=function(){var a,b;a=this.head;this.head=b=a._next;null!=b&&(a._next._prev=null);this.length--;return a.value};Ta.prototype.removeLast$=function(){var a,b;a=this.tail;this.tail=b=a._prev;null!=b&&(a._prev._next=null);this.length--;return a.value};Ta.prototype.insertAfter$LNode$Matrix$E$LMatrix$=function(a,b){var c,d;c={value:b,_prev:null,_next:null};null==a._next?(c._prev=a,this.tail=a._next=c):(c._next=d=a._next,c._prev=a,d._prev=c,a._next=
c);this.length++;return this};Ta.prototype.insertBefore$LNode$Matrix$E$LMatrix$=function(a,b){var c,d;c={value:b,_prev:null,_next:null};null==a._prev?(c._next=a,this.head=a._prev=c):(c._next=a,c._prev=d=a._prev,d._next=c,a._prev=c);this.length++;return this};Ta.prototype.forEach$F$LMatrix$V$=function(a){var b;for(b=this.head;b;b=b._next)a(b.value)};Ta.prototype.toString=function(){var a,b;a="list : [";for(b=this.head;null!=b;b=b._next)a+=" "+b.value.toString()+",";return a+"]"};cc.prototype={};(function(a){this.value=
a;this._next=this._prev=null}).prototype=new cc;cc.prev$LNode$Matrix$E$=function(a){return a._prev};cc.next$LNode$Matrix$E$=function(a){return a._next};Ua.prototype={};nb.prototype=new Ua;(function(a){var b,c;this.tail=this.head=null;this.length=0;b=a.length;for(c=0;c<b;c++)this.prepend$LRenderable$(a.pop())}).prototype=new Ua;Ua.prototype.prepend$LRenderable$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.tail=this.head=a:(a._next=b=this.head,this.head=b._prev=a);this.length++;
return this};Ua.prototype.append$LRenderable$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.head=a:(a._prev=b=this.tail,b._next=a);this.tail=a;this.length++;return this};Ua.prototype.remove$LNode$Renderable$E$=function(a){a._prev?a._prev._next=a._next:this.head=a._next;a._next?a._next._prev=a._prev:this.tail=a._prev;return a.value};Ua.prototype.removeFirst$=function(){var a,b;a=this.head;this.head=b=a._next;null!=b&&(a._next._prev=null);this.length--;return a.value};Ua.prototype.removeLast$=
function(){var a,b;a=this.tail;this.tail=b=a._prev;null!=b&&(a._prev._next=null);this.length--;return a.value};Ua.prototype.insertAfter$LNode$Renderable$E$LRenderable$=function(a,b){var c,d;c={value:b,_prev:null,_next:null};null==a._next?(c._prev=a,this.tail=a._next=c):(c._next=d=a._next,c._prev=a,d._prev=c,a._next=c);this.length++;return this};Ua.prototype.insertBefore$LNode$Renderable$E$LRenderable$=function(a,b){var c,d;c={value:b,_prev:null,_next:null};null==a._prev?(c._next=a,this.head=a._prev=
c):(c._next=a,c._prev=d=a._prev,d._next=c,a._prev=c);this.length++;return this};Ua.prototype.forEach$F$LRenderable$V$=function(a){var b;for(b=this.head;b;b=b._next)a(b.value)};Ua.prototype.toString=function(){var a,b;a="list : [";for(b=this.head;null!=b;b=b._next)a+=" "+b.value.toString()+",";return a+"]"};dc.prototype={};(function(a){this.value=a;this._next=this._prev=null}).prototype=new dc;dc.prev$LNode$Renderable$E$=function(a){return a._prev};dc.next$LNode$Renderable$E$=function(a){return a._next};
Va.prototype={};Eb.prototype=new Va;(function(a){var b,c;this.tail=this.head=null;this.length=0;b=a.length;for(c=0;c<b;c++)this.prepend$LPolygon$(a.pop())}).prototype=new Va;Va.prototype.prepend$LPolygon$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.tail=this.head=a:(a._next=b=this.head,this.head=b._prev=a);this.length++;return this};Va.prototype.append$LPolygon$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.head=a:(a._prev=b=this.tail,b._next=
a);this.tail=a;this.length++;return this};Va.prototype.remove$LNode$Polygon$E$=function(a){a._prev?a._prev._next=a._next:this.head=a._next;a._next?a._next._prev=a._prev:this.tail=a._prev;return a.value};Va.prototype.removeFirst$=function(){var a,b;a=this.head;this.head=b=a._next;null!=b&&(a._next._prev=null);this.length--;return a.value};Va.prototype.removeLast$=function(){var a,b;a=this.tail;this.tail=b=a._prev;null!=b&&(a._prev._next=null);this.length--;return a.value};Va.prototype.insertAfter$LNode$Polygon$E$LPolygon$=
function(a,b){var c,d;c={value:b,_prev:null,_next:null};null==a._next?(c._prev=a,this.tail=a._next=c):(c._next=d=a._next,c._prev=a,d._prev=c,a._next=c);this.length++;return this};Va.prototype.insertBefore$LNode$Polygon$E$LPolygon$=function(a,b){var c,d;c={value:b,_prev:null,_next:null};null==a._prev?(c._next=a,this.head=a._prev=c):(c._next=a,c._prev=d=a._prev,d._next=c,a._prev=c);this.length++;return this};Va.prototype.forEach$F$LPolygon$V$=function(a){var b;for(b=this.head;b;b=b._next)a(b.value)};
Va.prototype.toString=function(){var a,b;a="list : [";for(b=this.head;null!=b;b=b._next)a+=" "+b.value.toString()+",";return a+"]"};ec.prototype={};(function(a){this.value=a;this._next=this._prev=null}).prototype=new ec;ec.prev$LNode$Polygon$E$=function(a){return a._prev};ec.next$LNode$Polygon$E$=function(a){return a._next};P.prototype={};Fc.prototype=new P;P.id$S=function(a){a=P.document.getElementById(a);return a instanceof HTMLElement?a:null};P.getElementById$S=function(a){a=P.document.getElementById(a);
return a instanceof HTMLElement?a:null};P.createElement$S=function(a){return P.document.createElement(a)};G.prototype={};Gc.prototype=new G;G.setTimeout$F$V$N=function(a,b){return A.global.setTimeout(a,b)};G.clearTimeout$LTimerHandle$=function(a){A.global.clearTimeout(a)};var Yc=G.clearTimeout$LTimerHandle$;G.setInterval$F$V$N=function(a,b){return A.global.setInterval(a,b)};G.clearInterval$LTimerHandle$=function(a){A.global.clearInterval(a)};G.requestAnimationFrame$F$NV$=function(a){return G._requestAnimationFrame(a)};
G.cancelAnimationFrame$LTimerHandle$=function(a){G._cancelAnimationFrame(a)};G.useNativeRAF$B=function(a){G._requestAnimationFrame=Oc(a);G._cancelAnimationFrame=Pc(a)};G._getRequestAnimationFrameImpl$B=function(a){var b;if(a){if(A.global.requestAnimationFrame)return function(a){return A.global.requestAnimationFrame(a)};if(A.global.webkitRequestAnimationFrame)return function(a){return A.global.webkitRequestAnimationFrame(a)};if(A.global.mozRequestAnimationFrame)return function(a){return A.global.mozRequestAnimationFrame(a)};
if(A.global.oRequestAnimationFrame)return function(a){return A.global.oRequestAnimationFrame(a)};if(A.global.msRequestAnimationFrame)return function(a){return A.global.msRequestAnimationFrame(a)}}b=0;return function(a){var d,e,f;d=Date.now();f=16-(d-b);e=0>=f?0:f;b=d+e;return A.global.setTimeout(function(){a(d+e)},e)}};var Oc=G._getRequestAnimationFrameImpl$B;G._getCancelAnimationFrameImpl$B=function(a){if(a){if(A.global.cancelAnimationFrame)return function(a){A.global.cancelAnimationFrame(a)};if(A.global.webkitCancelAnimationFrame)return function(a){A.global.webkitCancelAnimationFrame(a)};
if(A.global.mozCancelAnimationFrame)return function(a){A.global.mozCancelAnimationFrame(a)};if(A.global.oCancelAnimationFrame)return function(a){A.global.oCancelAnimationFrame(a)};if(A.global.msCancelAnimationFrame)return function(a){A.global.msCancelAnimationFrame(a)}}return Yc};var Pc=G._getCancelAnimationFrameImpl$B;pc.prototype={};Hc.prototype=new pc;Nb.prototype={};Ic.prototype=new Nb;Nb.cross$NNNN=function(a,b,c,d){return a*d-c*b};var Xc=Nb.cross$NNNN;Ia.prototype={};Jc.prototype=new Ia;Ia._currentMsec$LStopwatch$=
function(){return Date.now()};Ia.start$LStopwatch$=function(a){if(null!=a._startedMsec){debugger;throw Error("[jsx/util.jsx:39] assertion failure");}a._startedMsec=a._lastLapMsec=Date.now()};var Nc=Ia.start$LStopwatch$;Ia.stop$LStopwatch$=function(a){if(null==a._startedMsec){debugger;throw Error("[jsx/util.jsx:45] assertion failure");}a._elapsedMsec+=Date.now()-a._startedMsec;a._startedMsec=null;a._lastLapMsec=null};Ia.isStarted$LStopwatch$=function(a){return null!=a._startedMsec};Ia.isStopped$LStopwatch$=
function(a){return null==a._startedMsec};var Zc=Ia.isStopped$LStopwatch$;Ia.lap$LStopwatch$=function(a){var b,c;if(null==a._lastLapMsec){debugger;throw Error("[jsx/util.jsx:65] assertion failure");}b=Date.now();c=b-a._lastLapMsec;a._lastLapMsec=b;return c};var $c=Ia.lap$LStopwatch$;Ia.getElapsedMsec$LStopwatch$=function(a){return a._elapsedMsec};yb.prototype={};Kc.prototype=new yb;Lc.prototype=new yb;yb.start$LFpsManager$=function(a){Nc(a._stopwatch)};yb.lastLap$LFpsManager$=function(a){return a._lastMsec};
yb.update$LFpsManager$=function(a){var b,c,d;if(Zc(a._stopwatch)){debugger;throw Error("[jsx/util.jsx:126] assertion failure");}b=$c(a._stopwatch);a._lastMsec=b;1>a._recentlyMsecLog.length?a._recentlyMsecLog.push(b):(a._recentlyMsecLog.push(b),a._recentlyMsecLog.shift());b=a._recentlyMsecLog.length;for(d=c=0;d<b;d++)c+=a._recentlyMsecLog[d];b/=c/1E3;null!=a._fpsElement&&a._enabledHtmlLog?a._fpsElement.innerHTML=b.toFixed(1)+"fps":a._enabledConsoleLog&&console.log(b.toFixed(1)+"fps")};var Wc=yb.update$LFpsManager$;
A.prototype={};Mc.prototype=new A;zb(I,"images",function(){return{}});zb(I,"imageDatas",function(){return{}});zb(I,"isLoadedImage",function(){return{}});zb(P,"window",function(){return A.global.window});zb(P,"document",function(){return A.global.document});zb(G,"_requestAnimationFrame",function(){return Oc(!0)});zb(G,"_cancelAnimationFrame",function(){return Pc(!0)});A.global=function(){return this}();var Rc={"jsx/demo2.jsx":{Util3D:pb,Util3D$:sc,Player:rb,Player$:tc,BlueBall:J,BlueBall$:hc,_Main:$b,
_Main$:yc},"jsx/vector.jsx":{Vector:D,Vector$NNN:m,Vector$NNNN:R,Vector$LVector$:zc},"jsx/matrix.jsx":{Matrix:O,Matrix$:Cb,Matrix$AN:H},"jsx/quaternion.jsx":{Quaternion:$,Quaternion$NLVector$:Ac,Quaternion$LVector$:Bc,Quaternion$NNNN:Ab},"jsx/engine.jsx":{Engine:I,Engine$S:ic,Context3D:C,Context3D$LCamera$:Cc,Camera:Ib,Camera$LVector$LVector$LVector$NNNN:kc,Color:Hb,Color$III:za,Renderable:wb,Renderable$:Dc,Polygon:ob,Polygon$ALVector$LColor$:Mb,PolygonGroup:tb,PolygonGroup$LList$Polygon$E$LVector$:Ec,
PolygonGroup$LList$Polygon$E$LVector$B:mc,SmoothTexture:xb,SmoothTexture$ALVector$S:nc,SmoothTexture$ALVector$SIIII:ac,Billboard:Db,Billboard$LVector$NNS:oc},"system:lib/js/js/web.jsx":{dom:P,dom$:Fc},"system:lib/js/timer.jsx":{Timer:G,Timer$:Gc,TimerHandle:pc,TimerHandle$:Hc},"jsx/util.jsx":{Math2D:Nb,Math2D$:Ic,Stopwatch:Ia,Stopwatch$:Jc,FpsManager:yb,FpsManager$:Kc,FpsManager$S:Lc},"system:lib/js/js.jsx":{js:A,js$:Mc}};JSX.runMain=function(a,b){var c=JSX.require(a);if(!c._Main)throw Error("entry point _Main not found in "+
a);if(!c._Main.main$AS)throw Error("entry point _Main.main(:string[]):void not found in "+a);c._Main.main$AS(b)};JSX.runTests=function(a,b){var c=JSX.require(a)._Test$;if(c){if(0===b.length){var d=c.prototype,e;for(e in d)d[e]instanceof Function&&/^test.*[$]$/.test(e)&&b.push(e)}var f=new c;null!=f.beforeClass$AS&&f.beforeClass$AS(b);for(c=0;c<b.length;++c)(function(a){f.run$SF$V$(a,function(){f[a]()})})(b[c]);null!=f.afterClass$&&f.afterClass$()}};window.addEventListener("load",fc);document.addEventListener("DOMContentLoaded",
fc)})();
