var JSX={};
(function(){function yb(a,b,c){Object.defineProperty(a,b,{get:function(){var e=c();delete a[b];return a[b]=e},set:function(c){delete a[b];a[b]=c},enumerable:!0,configurable:!0})}function Gb(){}function pb(){}function sc(){}function rb(){}function tc(){var a,b;this.r=12;this.x=0;this.y=10;this.ax=this.vz=this.vy=this.vx=this.z=0;this.ay=-120;this.az=0;a=Math.cos(0);b=Math.sin(0);this.rot=new zb(a,b,0*b,0*b);this.radius=8;this.isBraking=!1}function O(){}function hc(){var a=this,b,c,e,d,f,h,g,j,i,k,
l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,A,E,V,ca,W,kb,T,L,R,M,lb,S,mb,P,ub,B,D,C,K,N,G,Ab,Q,Bb,O,Ua,Va,Wa,Xa,Ya,Za,Ja,Ka,ab,bb,Ma,cb,Na,db,Oa,ka,la,Pa,eb,Qa,Da,La,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,$,aa,wa,U,ma,na,xa,oa,ya,ba,da,ga,ha,ia,ja,X,Y,Aa,Ba,Ca,fb,gb,hb,ib,jb,J;this.trees=this.player=null;this.treeRadius=0;this.items=null;this.totalElapsedMsec=this.itemRadius=0;Qc(["http://murooka.me/project2/image/tree.png","http://murooka.me/project2/image/so-nya.png","http://murooka.me/project2/image/redbull_free.png",
"http://murooka.me/project2/image/sky1.jpg"]);this.isStarted=!1;J=this.engine=new ic("canvas_demo2");J._skyImageSrc="./image/sky1.jpg";J._skyImage=I.images["./image/sky1.jpg"];J._isMobile&&((N=this.engine.camera).farZ=200,N.fovyX=0.7853981633974483,g=N.view,j=N.target,i=N.upper,k=N.fovyX,l=N.nearZ,p=N.farZ,r=N.aspectRatio,t=new m(j.x-g.x,j.y-g.y,j.z-g.z),v=Math.sqrt((G=t.x)*G+(Ab=t.y)*Ab+(Q=t.z)*Q),q=1E-9>v?new m(0,0,0):t.divSelf$N(v),z=new m((Wa=i.y)*(O=q.z)-(Bb=i.z)*(Va=q.y),Bb*(Xa=q.x)-(Ua=i.x)*
O,Ua*Va-Wa*Xa),F=Math.sqrt((Ya=z.x)*Ya+(Za=z.y)*Za+(Ja=z.z)*Ja),s=1E-9>F?new m(0,0,0):z.divSelf$N(F),x=new m((cb=q.y)*(ab=s.z)-(Ka=q.z)*(Ma=s.y),Ka*(Na=s.x)-(bb=q.x)*ab,bb*Ma-cb*Na),y=Math.sqrt((db=x.x)*db+(Oa=x.y)*Oa+(ka=x.z)*ka),u=1E-9>y?new m(0,0,0):x.divSelf$N(y),n=new H([la=s.x,Pa=s.y,eb=s.z,-(la*(Da=g.x)+Pa*(Ea=g.y)+eb*(ea=g.z)),Qa=u.x,La=u.y,Fa=u.z,-(Qa*Da+La*Ea+Fa*ea),fa=q.x,Ga=q.y,Ha=q.z,-(fa*Da+Ga*Ea+Ha*ea),0,0,0,1]),w=1/Math.tan(k/2),A=w/r,E=p/(p-l),V=-E*l,o=new H([w,0,0,0,0,A,0,0,0,0,
E,V,0,0,1,0]),N.viewMatrix=n,N.projectionMatrix=o,ca=(pa=o._m11)*(ta=n._m11)+(qa=o._m12)*(ua=n._m21)+(ra=o._m13)*(va=n._m31)+(sa=o._m14)*($=n._m41),W=pa*(wa=n._m12)+qa*(ma=n._m22)+ra*(xa=n._m32)+sa*(ya=n._m42),kb=pa*(ba=n._m13)+qa*(da=n._m23)+ra*(ga=n._m33)+sa*(ha=n._m43),T=pa*(ia=n._m14)+qa*(ja=n._m24)+ra*(X=n._m34)+sa*(Y=n._m44),L=(aa=o._m21)*ta+(U=o._m22)*ua+(na=o._m23)*va+(oa=o._m24)*$,R=aa*wa+U*ma+na*xa+oa*ya,M=aa*ba+U*da+na*ga+oa*ha,lb=aa*ia+U*ja+na*X+oa*Y,S=(Aa=o._m31)*ta+(Ba=o._m32)*ua+(Ca=
o._m33)*va+(fb=o._m34)*$,mb=Aa*wa+Ba*ma+Ca*xa+fb*ya,P=Aa*ba+Ba*da+Ca*ga+fb*ha,ub=Aa*ia+Ba*ja+Ca*X+fb*Y,B=(gb=o._m41)*ta+(hb=o._m42)*ua+(ib=o._m43)*va+(jb=o._m44)*$,D=gb*wa+hb*ma+ib*xa+jb*ya,C=gb*ba+hb*da+ib*ga+jb*ha,K=gb*ia+hb*ja+ib*X+jb*Y,N.matrix=new H([ca,W,kb,T,L,R,M,lb,S,mb,P,ub,B,D,C,K]));this.player={r:12,x:0,y:10,z:0,vx:0,vy:0,vz:0,ax:0,ay:-120,az:0,rot:vc(0,1,0,0),radius:8,isBraking:!1};this.trees=new Lb([new m(-271,-3,450),new m(-200,-3,720),new m(139,-3,351),new m(171,-3,254),new m(214,
-3,192),new m(-253,-3,555),new m(29,-3,385),new m(-72,-3,530),new m(96,-3,678),new m(-49,-3,222)]);this.treeRadius=24;this.items=new Lb([new m(149,-10,724),new m(107,-10,483),new m(279,-10,551),new m(-295,-10,261),new m(-16,-10,225),new m(95,-10,165),new m(264,-10,161),new m(-50,-10,325),new m(-169,-10,254),new m(271,-10,401)]);this.itemRadius=8;b=function(b){var c,d,e,f,g,h,i,j,k,l,n,o,p,r,q,s,t,u,v,w,x,y,z,A,E,F,V,ca,W,T,kb,L,M,R,S,lb,mb,P,N,ub,B,D,C,uc,ba,da,ga,ha,ia,ja,X,Y,aa,U,na,I,pa,qa,ra,
sa,ta,ua,va,$,wa,ma,xa,oa,ya,K,ea,Aa,Ba,Ca,G,Da,Ea,Fa,fa,Ga,Ha,Q,O,Ab,La,J,Qb,Ma,Na,Oa,ka,la,Pa,Qa,Bb,Ua,Va,Wa,Xa,Ya,Za,Ja,Ka;a._updateClearedPlayer$N(b);c=a.player;d=new m(c.x+Math.sin(a.totalElapsedMsec/5E3)*50,c.y+20,c.z+Math.cos(a.totalElapsedMsec/5E3)*50);e=new m(c.x,c.y,c.z);(P=a.engine.camera).target=e;P.view=d;f=P.view;g=P.target;h=P.upper;i=P.fovyX;j=P.nearZ;k=P.farZ;l=P.aspectRatio;s=new m(g.x-f.x,g.y-f.y,g.z-f.z);t=Math.sqrt((N=s.x)*N+(ub=s.y)*ub+(B=s.z)*B);p=t<1E-9?new m(0,0,0):s.divSelf$N(t);
u=new m((da=h.y)*(C=p.z)-(D=h.z)*(ba=p.y),D*(ga=p.x)-(uc=h.x)*C,uc*ba-da*ga);v=Math.sqrt((ha=u.x)*ha+(ia=u.y)*ia+(ja=u.z)*ja);r=v<1E-9?new m(0,0,0):u.divSelf$N(v);w=new m((na=p.y)*(Y=r.z)-(X=p.z)*(U=r.y),X*(I=r.x)-(aa=p.x)*Y,aa*U-na*I);x=Math.sqrt((pa=w.x)*pa+(qa=w.y)*qa+(ra=w.z)*ra);q=x<1E-9?new m(0,0,0):w.divSelf$N(x);n=new H([sa=r.x,ta=r.y,ua=r.z,-(sa*($=f.x)+ta*(ma=f.y)+ua*(oa=f.z)),va=q.x,wa=q.y,xa=q.z,-(va*$+wa*ma+xa*oa),ya=p.x,K=p.y,ea=p.z,-(ya*$+K*ma+ea*oa),0,0,0,1]);y=1/Math.tan(i/2);z=y/
l;A=k/(k-j);o=new H([y,0,0,0,0,z,0,0,0,0,A,-A*j,0,0,1,0]);P.viewMatrix=n;P.projectionMatrix=o;E=(Aa=o._m11)*(Da=n._m11)+(Ba=o._m12)*(Ea=n._m21)+(Ca=o._m13)*(Fa=n._m31)+(G=o._m14)*(fa=n._m41);F=Aa*(Ha=n._m12)+Ba*(O=n._m22)+Ca*(La=n._m32)+G*(Qb=n._m42);V=Aa*(Ma=n._m13)+Ba*(Na=n._m23)+Ca*(Oa=n._m33)+G*(ka=n._m43);ca=Aa*(la=n._m14)+Ba*(Pa=n._m24)+Ca*(Qa=n._m34)+G*(Bb=n._m44);W=(Ga=o._m21)*Da+(Q=o._m22)*Ea+(Ab=o._m23)*Fa+(J=o._m24)*fa;T=Ga*Ha+Q*O+Ab*La+J*Qb;kb=Ga*Ma+Q*Na+Ab*Oa+J*ka;L=Ga*la+Q*Pa+Ab*Qa+
J*Bb;M=(Ua=o._m31)*Da+(Va=o._m32)*Ea+(Wa=o._m33)*Fa+(Xa=o._m34)*fa;R=Ua*Ha+Va*O+Wa*La+Xa*Qb;S=Ua*Ma+Va*Na+Wa*Oa+Xa*ka;lb=Ua*la+Va*Pa+Wa*Qa+Xa*Bb;mb=(Ya=o._m41)*Da+(Za=o._m42)*Ea+(Ja=o._m43)*Fa+(Ka=o._m44)*fa;P.matrix=new H([E,F,V,ca,W,T,kb,L,M,R,S,lb,mb,Ya*Ha+Za*O+Ja*La+Ka*Qb,Ya*Ma+Za*Na+Ja*Oa+Ka*ka,Ya*la+Za*Pa+Ja*Qa+Ka*Bb])};c=function(b){a._checkCollisionWithFloor$N(b);a._checkCollisionWithTrees$();a._checkCollisionWithItems$();a._updateViewpoint$()};e=function(b){a._renderPlayer$LContext3D$(b);
a._renderField$LContext3D$(b)};d=function(b){a._renderPlayer$LContext3D$(b);a._renderTrees$LContext3D$(b);a._renderItems$LContext3D$(b);a._renderField$LContext3D$(b)};f=!1;this.engine.onUpdate=function(g){var h,i,j;if(a.isStarted){if(a.player.y<-1E3){a.player={r:12,x:0,y:10,z:0,vx:0,vy:0,vz:0,ax:0,ay:-120,az:0,rot:vc(0,1,0,0),radius:8,isBraking:false};a.isStarted=false}if(!f&&1050<=(h=(i=a.player).x)&&h<=1110&&1350<=(j=i.z)&&j<=1410){c=b;d=e;f=true}c(g)}};h=new za(90,135,150);this.engine.onRender=
function(b,c){a.totalElapsedMsec=a.totalElapsedMsec+c;b.backgroundColor=h;d(b)};this.engine._isMobile?this._setMobileOperation$():this._setPCOperation$()}function $b(){}function yc(){}function D(){}function m(a,b,c){this.x=a;this.y=b;this.z=c;this.w=1}function K(a,b,c,e){a=this.x=a/e;this.y=b/e;this.z=c/e;this.w=1;NaN===a&&console.log(e)}function zc(a){this.x=a.x;this.y=a.y;this.z=a.z;this.w=1}function J(){}function Cb(){this._m11=1;this._m21=this._m14=this._m13=this._m12=0;this._m22=1;this._m32=
this._m31=this._m24=this._m23=0;this._m33=1;this._m43=this._m42=this._m41=this._m34=0;this._m44=1}function H(a){this._m11=a[0];this._m12=a[1];this._m13=a[2];this._m14=a[3];this._m21=a[4];this._m22=a[5];this._m23=a[6];this._m24=a[7];this._m31=a[8];this._m32=a[9];this._m33=a[10];this._m34=a[11];this._m41=a[12];this._m42=a[13];this._m43=a[14];this._m44=a[15]}function Z(){}function Ac(a,b){this.t=a;this.x=b.x;this.y=b.y;this.z=b.z}function Bc(a){this.t=0;this.x=a.x;this.y=a.y;this.z=a.z}function zb(a,
b,c,e){this.t=a;this.x=b;this.y=c;this.z=e}function I(){}function ic(a){var b,c,e,d,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,A,E,V,ca,W,kb,T,L,R,M,lb,S,mb,P,ub,B,D,C,I,N,K,G,O,J,za,Ua,Va,Wa,Xa,Ya,Za,Ja,Ka,ab,bb,Ma,cb,Na,db,Oa,ka,la,Pa,eb,Qa,Da,La,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,$,aa,wa,U,ma,na,xa,oa,ya,ba,da,ga,ha,ia,ja,X,Y,Aa,Ba,Ca,fb,gb,hb,ib,jb,Z,Ia,Ra,Sa,Ta,sb,$a,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb;this._skyImage=this._skyImageSrc=this.onRender=this.onUpdate=this.screenMatrix=this.camera=null;
this._isRunning=!1;b=Q.window.navigator.userAgent;this._isMobile=/iPhone/.test(b)||/Android/.test(b);var jc,wc=Q.document.getElementById(a);jc=wc instanceof HTMLElement?wc:null;c=jc instanceof HTMLCanvasElement?jc:null;var xc=c.getContext("2d");this.context=xc instanceof CanvasRenderingContext2D?xc:null;Ma=this._width=c.width;h=this._height=c.height;g=new H([1,0,0,Ma/2,0,1,0,h/2,0,0,1,0,0,0,0,1]);y=Ma/2;w=-h/2;j=g._m11;i=g._m12;k=g._m13;l=g._m14;p=g._m21;r=g._m22;n=g._m23;o=g._m24;q=g._m31;s=g._m32;
u=g._m33;t=g._m34;v=g._m41;z=g._m42;F=g._m43;x=g._m44;g._m11=j*y+0*i+0*k+0*l;g._m12=0*j+i*w+0*k+0*l;g._m13=0*j+0*i+1*k+0*l;g._m14=0*j+0*i+0*k+1*l;g._m21=p*y+0*r+0*n+0*o;g._m22=0*p+r*w+0*n+0*o;g._m23=0*p+0*r+1*n+0*o;g._m24=0*p+0*r+0*n+1*o;g._m31=q*y+0*s+0*u+0*t;g._m32=0*q+s*w+0*u+0*t;g._m33=0*q+0*s+1*u+0*t;g._m34=0*q+0*s+0*u+1*t;g._m41=v*y+0*z+0*F+0*x;g._m42=0*v+z*w+0*F+0*x;g._m43=0*v+0*z+1*F+0*x;g._m44=0*v+0*z+0*F+1*x;this.screenMatrix=g;this._skyImage=this._skyImageSrc=null;this._isRunning=!1;e=
new m(0,0,-90);d=new m(0,0,0);f=new m(0,1,0);A=this.camera=new kc(e,d,f,1.0471975511965976,0,500,this._height/this._width);E=A.view;V=A.target;ca=A.upper;W=A.fovyX;kb=A.nearZ;T=A.farZ;L=A.aspectRatio;P=new m(V.x-E.x,V.y-E.y,V.z-E.z);ub=Math.sqrt((cb=P.x)*cb+(Na=P.y)*Na+(db=P.z)*db);lb=1E-9>ub?new m(0,0,0):P.divSelf$N(ub);B=new m((eb=ca.y)*(ka=lb.z)-(Oa=ca.z)*(Pa=lb.y),Oa*(Qa=lb.x)-(la=ca.x)*ka,la*Pa-eb*Qa);D=Math.sqrt((Da=B.x)*Da+(La=B.y)*La+(Ea=B.z)*Ea);S=1E-9>D?new m(0,0,0):B.divSelf$N(D);C=new m((Ha=
lb.y)*(ea=S.z)-(Fa=lb.z)*(Ga=S.y),Fa*(pa=S.x)-(fa=lb.x)*ea,fa*Ga-Ha*pa);I=Math.sqrt((qa=C.x)*qa+(ra=C.y)*ra+(sa=C.z)*sa);mb=1E-9>I?new m(0,0,0):C.divSelf$N(I);R=new H([ta=S.x,ua=S.y,va=S.z,-(ta*(aa=E.x)+ua*(U=E.y)+va*(na=E.z)),$=mb.x,wa=mb.y,ma=mb.z,-($*aa+wa*U+ma*na),xa=lb.x,oa=lb.y,ya=lb.z,-(xa*aa+oa*U+ya*na),0,0,0,1]);N=1/Math.tan(W/2);K=N/L;G=T/(T-kb);M=new H([N,0,0,0,0,K,0,0,0,0,G,-G*kb,0,0,1,0]);A.viewMatrix=R;A.projectionMatrix=M;O=(ba=M._m11)*(ia=R._m11)+(da=M._m12)*(ja=R._m21)+(ga=M._m13)*
(X=R._m31)+(ha=M._m14)*(Y=R._m41);J=ba*(Ba=R._m12)+da*(fb=R._m22)+ga*(hb=R._m32)+ha*(jb=R._m42);za=ba*(Z=R._m13)+da*(Ia=R._m23)+ga*(Ra=R._m33)+ha*(Sa=R._m43);Ua=ba*(Ta=R._m14)+da*(sb=R._m24)+ga*($a=R._m34)+ha*(Rb=R._m44);Va=(Aa=M._m21)*ia+(Ca=M._m22)*ja+(gb=M._m23)*X+(ib=M._m24)*Y;Wa=Aa*Ba+Ca*fb+gb*hb+ib*jb;Xa=Aa*Z+Ca*Ia+gb*Ra+ib*Sa;Ya=Aa*Ta+Ca*sb+gb*$a+ib*Rb;Za=(Sb=M._m31)*ia+(Tb=M._m32)*ja+(Ub=M._m33)*X+(Vb=M._m34)*Y;Ja=Sb*Ba+Tb*fb+Ub*hb+Vb*jb;Ka=Sb*Z+Tb*Ia+Ub*Ra+Vb*Sa;ab=Sb*Ta+Tb*sb+Ub*$a+Vb*Rb;
bb=(Wb=M._m41)*ia+(Xb=M._m42)*ja+(Yb=M._m43)*X+(Zb=M._m44)*Y;A.matrix=new H([O,J,za,Ua,Va,Wa,Xa,Ya,Za,Ja,Ka,ab,bb,Wb*Ba+Xb*fb+Yb*hb+Zb*jb,Wb*Z+Xb*Ia+Yb*Ra+Zb*Sa,Wb*Ta+Xb*sb+Yb*$a+Zb*Rb])}function C(){}function Cc(a){this._groupCenter=this._polygonList=null;this._ignoringZHidden=!1;this._worldMatrix=new Cb;this._matrixStack=new lc;this.camera=a;this._depth=3;this.modelList1=new nb;this.modelList2=new nb;this.modelList3=new nb;this.modelList4=new nb;this.modelList5=new nb;this.backgroundColor=new za(90,
135,158)}function Ib(){}function kc(a,b,c,e,d,f,h){var g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,A,E,V,ca,W,kb,T,L,R,M,B,S,mb,P,ub,C,D,I,K,N,G,O,J,Q,Z,Ua,Va,Wa,Xa,Ya,Za,Ja,Ka,ab,bb,Ma,cb,Na,db,Oa,ka,la,Pa,eb,Qa,Da,La,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,$,aa,wa,U,ma,na,xa,oa,ya,ba,da,ga,ha,ia,ja,X,Y,Aa,Ba,Ca;this.matrix=this.projectionMatrix=this.viewMatrix=null;this.view=a;this.target=b;this.upper=c;this.fovyX=e;this.nearZ=d;this.farZ=f;this.aspectRatio=h;this.rotatingMatrix=new Cb;g=this.view;j=this.target;
i=this.upper;k=this.fovyX;l=this.nearZ;p=this.farZ;r=this.aspectRatio;t=new m(j.x-g.x,j.y-g.y,j.z-g.z);v=Math.sqrt((C=t.x)*C+(D=t.y)*D+(I=t.z)*I);q=1E-9>v?new m(0,0,0):t.divSelf$N(v);z=new m((J=i.y)*(N=q.z)-(K=i.z)*(O=q.y),K*(Q=q.x)-(G=i.x)*N,G*O-J*Q);F=Math.sqrt((Z=z.x)*Z+(Ua=z.y)*Ua+(Va=z.z)*Va);s=1E-9>F?new m(0,0,0):z.divSelf$N(F);x=new m((Ja=q.y)*(Xa=s.z)-(Wa=q.z)*(Za=s.y),Wa*(Ka=s.x)-(Ya=q.x)*Xa,Ya*Za-Ja*Ka);y=Math.sqrt((ab=x.x)*ab+(bb=x.y)*bb+(Ma=x.z)*Ma);u=1E-9>y?new m(0,0,0):x.divSelf$N(y);
n=new H([cb=s.x,Na=s.y,db=s.z,-(cb*(ka=g.x)+Na*(Pa=g.y)+db*(Qa=g.z)),Oa=u.x,la=u.y,eb=u.z,-(Oa*ka+la*Pa+eb*Qa),Da=q.x,La=q.y,Ea=q.z,-(Da*ka+La*Pa+Ea*Qa),0,0,0,1]);w=1/Math.tan(k/2);A=w/r;E=p/(p-l);o=new H([w,0,0,0,0,A,0,0,0,0,E,-E*l,0,0,1,0]);this.viewMatrix=n;this.projectionMatrix=o;V=(Fa=o._m11)*(Ha=n._m11)+(ea=o._m12)*(pa=n._m21)+(fa=o._m13)*(qa=n._m31)+(Ga=o._m14)*(ra=n._m41);ca=Fa*(ta=n._m12)+ea*(va=n._m22)+fa*(aa=n._m32)+Ga*(U=n._m42);W=Fa*(ma=n._m13)+ea*(na=n._m23)+fa*(xa=n._m33)+Ga*(oa=n._m43);
kb=Fa*(ya=n._m14)+ea*(ba=n._m24)+fa*(da=n._m34)+Ga*(ga=n._m44);T=(sa=o._m21)*Ha+(ua=o._m22)*pa+($=o._m23)*qa+(wa=o._m24)*ra;L=sa*ta+ua*va+$*aa+wa*U;R=sa*ma+ua*na+$*xa+wa*oa;M=sa*ya+ua*ba+$*da+wa*ga;B=(ha=o._m31)*Ha+(ia=o._m32)*pa+(ja=o._m33)*qa+(X=o._m34)*ra;S=ha*ta+ia*va+ja*aa+X*U;mb=ha*ma+ia*na+ja*xa+X*oa;P=ha*ya+ia*ba+ja*da+X*ga;ub=(Y=o._m41)*Ha+(Aa=o._m42)*pa+(Ba=o._m43)*qa+(Ca=o._m44)*ra;this.matrix=new H([V,ca,W,kb,T,L,R,M,B,S,mb,P,ub,Y*ta+Aa*va+Ba*aa+Ca*U,Y*ma+Aa*na+Ba*xa+Ca*oa,Y*ya+Aa*ba+
Ba*da+Ca*ga])}function Hb(){}function za(a,b,c){this.r=a;this.g=b;this.b=c}function vb(){}function Dc(){this.vCenter=this.center=null}function ob(){}function Mb(a,b){this.vVertices=this.vCenter=this.center=null;this.vertices=a;this._color=b;this._enabledLighting=!0;this.updateCenter$()}function tb(){}function Ec(a,b){this.vCenter=null;this.polygons=a;this.center=b;this._ignoringZHidden=!1}function mc(a,b,c){this.vCenter=null;this.polygons=a;this.center=b;this._ignoringZHidden=c}function wb(){}function nc(a,
b){ac.call(this,a,b,6,6,4,2)}function ac(a,b,c,e,d,f){var h,g,j,i,k;h=new za(0,0,0);this.vVertices=this.vCenter=this.center=null;this.vertices=a;this._color=h;this._enabledLighting=!0;this.updateCenter$();this._src=b;this._image=I.images[b];this.vertices=a;b=a[1];h=a[0];i=b.x-h.x;k=b.y-h.y;b=Math.sqrt(i*i+k*k+(g=b.z-h.z)*g);this._width=0<=b?b:-b;g=a[2];a=a[1];b=g.x-a.x;h=g.y-a.y;a=Math.sqrt(b*b+h*h+(j=g.z-a.z)*j);this._height=0<=a?a:-a;this._maxHorizontalDiv=c;this._maxVerticalDiv=e;this._maxDiv=
d;this._minDiv=f;this.updateCenter$()}function Db(){}function oc(a,b,c,e){this.vCenter=null;this._width=b;this._height=c;this._src=e;this._image=I.images[e];this.center=a}function Ra(){}function Lb(a){var b,c;this.tail=this.head=null;this.length=0;b=a.length;for(c=0;c<b;c++)this.prepend$LVector$(a.pop())}function bc(){}function Sa(){}function lc(){this.tail=this.head=null;this.length=0}function cc(){}function Ta(){}function nb(){this.tail=this.head=null;this.length=0}function dc(){}function $a(){}
function Eb(){this.tail=this.head=null;this.length=0}function ec(){}function Q(){}function Fc(){}function G(){}function Gc(){}function pc(){}function Hc(){}function Nb(){}function Ic(){}function Ia(){}function Jc(){this._lastLapMsec=null;this._elapsedMsec=0;this._startedMsec=null}function xb(){}function Kc(){this._fpsElement=null;this._stopwatch={_elapsedMsec:0,_startedMsec:null,_lastLapMsec:null};this._recentlyMsecLog=[];this._lastMsec=0;this._enabledHtmlLog=!1;this._enabledConsoleLog=!0}function Lc(a){a=
Q.document.getElementById(a);this._fpsElement=a instanceof HTMLElement?a:null;this._stopwatch={_elapsedMsec:0,_startedMsec:null,_lastLapMsec:null};this._recentlyMsecLog=[];this._lastMsec=0;this._enabledHtmlLog=!0;this._enabledConsoleLog=!1}function B(){}function Mc(){}function fc(){window.removeEventListener("load",fc);document.removeEventListener("DOMContentLoaded",fc);JSX.runMain("jsx/demo2.jsx",[])}JSX.require=function(a){a=Rc[a];return void 0!==a?a:null};JSX.profilerIsRunning=function(){return null!=
Gb.getResults};JSX.getProfileResults=function(){return(Gb.getResults||function(){return{}})()};JSX.postProfileResults=function(a){if(null==Gb.postResults)throw Error("profiler has not been turned on");return Gb.postResults(a)};JSX.resetProfileResults=function(){if(null==Gb.resetResults)throw Error("profiler has not been turned on");return Gb.resetResults()};pb.prototype={};sc.prototype=new pb;pb.sphere$LContext3D$NI=function(a,b,c){var e,d,f,h,g,j,i,k,l;e=2*c;d=Math.sin;f=Math.cos;h=new m(0,0,0);
a._polygonList=new Eb;a._groupCenter=h;a._ignoringZHidden=!1;for(h=0;h<e;h++)j=1,i=h+1,k=h,Ob(a,[new m(f(6.283185307179586*i/e)*d(0/c)*b,f(0/c)*b,d(6.283185307179586*i/e)*d(0/c)*b),new m(f(6.283185307179586*i/e)*d(3.141592653589793*j/c)*b,f(3.141592653589793*j/c)*b,d(6.283185307179586*i/e)*d(3.141592653589793*j/c)*b),new m(f(6.283185307179586*k/e)*d(3.141592653589793*j/c)*b,f(3.141592653589793*j/c)*b,d(6.283185307179586*k/e)*d(3.141592653589793*j/c)*b)],new za(128,128,255));for(h=1;h<c-1;h++)for(l=
0;l<e;l++)g=h,j=h+1,i=l+1,k=l,Ob(a,[new m(f(6.283185307179586*i/e)*d(3.141592653589793*h/c)*b,f(3.141592653589793*h/c)*b,d(6.283185307179586*i/e)*d(3.141592653589793*h/c)*b),new m(f(6.283185307179586*i/e)*d(3.141592653589793*j/c)*b,f(3.141592653589793*j/c)*b,d(6.283185307179586*i/e)*d(3.141592653589793*j/c)*b),new m(f(6.283185307179586*k/e)*d(3.141592653589793*j/c)*b,f(3.141592653589793*j/c)*b,d(6.283185307179586*k/e)*d(3.141592653589793*j/c)*b),new m(f(6.283185307179586*k/e)*d(3.141592653589793*
g/c)*b,f(3.141592653589793*g/c)*b,d(6.283185307179586*k/e)*d(3.141592653589793*g/c)*b)],new za(128,128,255));for(h=0;h<e;h++)g=c-1,j=c,i=h+1,k=h,Ob(a,[new m(f(6.283185307179586*h/e)*d(3.141592653589793*g/c)*b,f(3.141592653589793*g/c)*b,d(6.283185307179586*h/e)*d(3.141592653589793*g/c)*b),new m(f(6.283185307179586*i/e)*d(3.141592653589793*g/c)*b,f(3.141592653589793*g/c)*b,d(6.283185307179586*i/e)*d(3.141592653589793*g/c)*b),new m(f(6.283185307179586*k/e)*d(3.141592653589793*j/c)*b,f(3.141592653589793*
j/c)*b,d(6.283185307179586*k/e)*d(3.141592653589793*j/c)*b)],new za(128,128,255));gc(a)};var Sc=pb.sphere$LContext3D$NI;pb.tile$LContext3D$IIIILColor$=function(a,b,c,e,d,f){b=[new m(b-d/2,c,e-d/2),new m(b-d/2,c,e+d/2),new m(b+d/2,c,e+d/2),new m(b+d/2,c,e-d/2)];Jb(a,new Mb(b,f))};pb.tileOnGroup$LContext3D$IIIILColor$=function(a,b,c,e,d,f){Ob(a,[new m(b-d/2,c,e-d/2),new m(b-d/2,c,e+d/2),new m(b+d/2,c,e+d/2),new m(b+d/2,c,e-d/2)],f)};var qc=pb.tileOnGroup$LContext3D$IIIILColor$;pb.tileRectXZ$LContext3D$IIIIIILColor$LColor$=
function(a,b,c,e,d,f,h,g,j){var i,k,l,p,r;i=d/h;k=e/h;l=new m(0,0,0);a._polygonList=new Eb;a._groupCenter=l;a._ignoringZHidden=!0;for(l=0;l<i;l++)for(p=0;p<k;p++)r=0===(l+p)%2?g:j,qc(a,b-e/2+(p+0.5)*h,f,c-d/2+(l+0.5)*h,h,r);gc(a)};var Fb=pb.tileRectXZ$LContext3D$IIIIIILColor$LColor$;rb.prototype={};tc.prototype=new rb;rb.moveForward$LPlayer$=function(a){qb(a,50,0)};rb.move$LPlayer$NN=function(a,b,c){var e,d,f;e=a.vx;d=a.vz;f=Math.sqrt(e*e+d*d);if(1E-9<(0<=d?d:-d))d/=f;if(1E-9<(0<=e?e:-e))e/=f;d=Math.atan2(e,
d);e=Math.sin(d);d=Math.cos(d);a.az=d*b-e*c;a.ax=e*b+d*c};var qb=rb.move$LPlayer$NN;rb.brake$LPlayer$=function(a){a.isBraking=!0};rb.unbrake$LPlayer$=function(a){a.isBraking=!1};rb.update$LPlayer$N=function(a,b){var c,e,d,f,h,g,j,i,k,l;c=b/1E3;0.1<c&&(c=0.1);e=a.vx+=a.ax*c;a.vy+=a.ay*c;a.vz+=a.az*c;e=-100>=e?-100:e;a.vx=100<=e?100:e;e=a.vy;e=-3E3>=e?-3E3:e;a.vy=3E3<=e?3E3:e;e=a.vz;e=-100>=e?-100:e;f=a.vz=100<=e?100:e;e=a.vx*c;d=a.vy*c;f*=c;a.x+=e;a.y+=d;a.z+=f;d=a.isBraking?0.05:0.0010;a.vx-=(0<=
e?e:-e)*a.vx*d;a.vz-=(0<=f?f:-f)*a.vz*d;a.isBraking&&(c=Math.pow(2.718281828459045,-c),a.az*=c,a.ax*=c);c=new m(0-1*f,0*f-0*e,1*e-0);d=Math.sqrt((h=c.x)*h+(g=c.y)*g+(j=c.z)*j);h=1E-9>d?new m(0,0,0):c.divSelf$N(d);e=Math.sqrt(e*e+0+f*f)/a.r;g=h.x;j=h.y;c=h.z;h=Math.cos(e/2);e=Math.sin(e/2);g*=e;j*=e;l=c*e;c=a.rot;e=(f=c.t)*h-((d=c.x)*g+(i=c.y)*j+(k=c.z)*l);c.t=e;c.x=f*g+h*d+(i*l-k*j);c.y=f*j+h*i+(k*g-d*l);c.z=f*l+h*k+(d*j-i*g)};var Tc=rb.update$LPlayer$N;rb.bounce$LPlayer$LVector$=function(a,b){var c,
e,d,f;c=a.vx*(e=b.x)+a.vy*(d=b.y)+a.vz*(f=b.z);a.vx-=1.5*c*e;a.vy-=1.5*c*d;a.vz-=1.5*c*f};O.prototype={};hc.prototype=new O;O.prototype._initTrees$=function(){this.trees=new Lb([new m(-271,-3,450),new m(-200,-3,720),new m(139,-3,351),new m(171,-3,254),new m(214,-3,192),new m(-253,-3,555),new m(29,-3,385),new m(-72,-3,530),new m(96,-3,678),new m(-49,-3,222)]);this.treeRadius=24};O.prototype._initItems$=function(){this.items=new Lb([new m(149,-10,724),new m(107,-10,483),new m(279,-10,551),new m(-295,
-10,261),new m(-16,-10,225),new m(95,-10,165),new m(264,-10,161),new m(-50,-10,325),new m(-169,-10,254),new m(271,-10,401)]);this.itemRadius=8};O.prototype._checkCollisionWithFloor$N=function(a){var b,c,e,d,f,h,g,j,i,k,l,p,r,n,o;b=this.player;Tc(b,a);c=b.x;e=b.y;d=b.z;if((-30<=c&&30>=c&&-30<=d&&150>=d||-300<=c&&300>=c&&150<=d&&750>=d||-30<=c&&30>=c&&750<=d&&810>=d||-30<=c&&570>=c&&810<=d&&870>=d||510<=c&&1110>=c&&150<=d&&210>=d||1050<=c&&1110>=c&&750<=d&&1350>=d)&&2*-b.radius<e&&0>e)a=0*b.vx+1*b.vy+
0*b.vz,b.vx-=0*a,b.vy-=1.5*a,b.vz-=0*a,b.y=0;510<=c&&(570>=c&&510<=d&&810>=d)&&(a=Math.floor((810-d)/30),a*=5,a-2*b.radius<e&&e<a&&(j=new m(0,30,5),i=Math.sqrt((k=j.x)*k+(l=j.y)*l+(f=j.z)*f),f=1E-9>i?new m(0,0,0):j.divSelf$N(i),f=b.vx*(k=f.x)+b.vy*(l=f.y)+b.vz*(j=f.z),b.vx-=1.5*f*k,b.vy-=1.5*f*l,b.vz-=1.5*f*j,b.y=a));510<=c&&(570>=c&&210<=d&&510>d)&&(a=Math.floor((d-210)/30),a*=5,a-2*b.radius<e&&e<a&&(k=new m(0,30,-5),l=Math.sqrt((p=k.x)*p+(r=k.y)*r+(h=k.z)*h),h=1E-9>l?new m(0,0,0):k.divSelf$N(l),
h=b.vx*(p=h.x)+b.vy*(r=h.y)+b.vz*(k=h.z),b.vx-=1.5*h*p,b.vy-=1.5*h*r,b.vz-=1.5*h*k,b.y=a));1110<=c&&(1270>=c&&150<=d&&810>=d)&&(a=80*((c-1110)/160),a-2*b.radius<e&&e<a&&(c=new m(-1,2,0),e=Math.sqrt((n=c.x)*n+(o=c.y)*o+(g=c.z)*g),g=1E-9>e?new m(0,0,0):c.divSelf$N(e),g=b.vx*(n=g.x)+b.vy*(o=g.y)+b.vz*(c=g.z),b.vx-=1.5*g*n,b.vy-=1.5*g*o,b.vz-=1.5*g*c,b.y=a))};O.prototype._checkCollisionWithTrees$=function(){var a=this,b;b=this.player;this.trees.forEach$F$LVector$V$(function(c){var e,d,f,h,g,j,i,k,l;e=
b.x-c.x;d=b.y-c.y;c=b.z-c.z;f=a.treeRadius+b.radius;e*e+d*d+c*c<f*f&&(e=new m(e,d,c),d=Math.sqrt((h=e.x)*h+(g=e.y)*g+(j=e.z)*j),h=1E-9>d?new m(0,0,0):e.divSelf$N(d),g=Math.sqrt((i=b.vx)*i+(k=b.vy)*k+(l=b.vz)*l),b.ax+=2*g*(i=h.x),b.vy+=2*g*h.y,b.az+=2*g*(k=h.z),b.x+=i*(i=a.treeRadius)/4,b.z+=k*i/4)})};O.prototype._checkCollisionWithItems$=function(){var a,b,c,e,d,f,h,g;a=this.player;b=this.items;c=this.itemRadius;for(e=b.head;e;e=e._next)d=e.value,f=d.x-a.x,h=d.y-a.y,d=d.z-a.z,g=c+a.radius,f*f+h*h+
d*d<g*g&&b.remove$LNode$Vector$E$(e)};O.prototype._updateViewpoint$=function(){var a,b,c,e,d,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,A,E,V,ca,W,kb,T,L,R,M,B,S,mb,P,C,D,I,K,G,N,O,J,Q,Z,za,Ua,Va,Wa,Xa,Ya,Za,Ja,Ka,ab,bb,Ma,cb,Na,db,Oa,ka,la,Pa,eb,Qa,Da,La,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,$,aa,wa,U,ma,na,xa,oa,ya,ba,da,ga,ha,ia,ja,X,Y,Aa,Ba,Ca,fb,gb,hb,ib,jb;a=this.player;b=-a.vz;c=-a.vx;e=Math.sqrt(b*b+c*c);1E-9>e?(b=-1,c=0):(b/=e,c/=e);d=a.y;0>d&&(d=-300<=d?d:-300,d=-d/2);f=10;h=Math.sqrt((K=
a.vx)*K+(G=a.vz)*G);50>h&&(f-=0.6*(50-h));g=new m(a.x+50*c,1.2*d+f,a.z+50*b);j=new m(a.x,a.y,a.z);(N=this.engine.camera).target=j;N.view=g;i=N.view;k=N.target;l=N.upper;p=N.fovyX;r=N.nearZ;n=N.farZ;o=N.aspectRatio;z=new m(k.x-i.x,k.y-i.y,k.z-i.z);F=Math.sqrt((O=z.x)*O+(J=z.y)*J+(Q=z.z)*Q);u=1E-9>F?new m(0,0,0):z.divSelf$N(F);x=new m((Wa=l.y)*(za=u.z)-(Z=l.z)*(Va=u.y),Z*(Xa=u.x)-(Ua=l.x)*za,Ua*Va-Wa*Xa);y=Math.sqrt((Ya=x.x)*Ya+(Za=x.y)*Za+(Ja=x.z)*Ja);t=1E-9>y?new m(0,0,0):x.divSelf$N(y);w=new m((cb=
u.y)*(ab=t.z)-(Ka=u.z)*(Ma=t.y),Ka*(Na=t.x)-(bb=u.x)*ab,bb*Ma-cb*Na);A=Math.sqrt((db=w.x)*db+(Oa=w.y)*Oa+(ka=w.z)*ka);v=1E-9>A?new m(0,0,0):w.divSelf$N(A);q=new H([la=t.x,Pa=t.y,eb=t.z,-(la*(Da=i.x)+Pa*(Ea=i.y)+eb*(ea=i.z)),Qa=v.x,La=v.y,Fa=v.z,-(Qa*Da+La*Ea+Fa*ea),fa=u.x,Ga=u.y,Ha=u.z,-(fa*Da+Ga*Ea+Ha*ea),0,0,0,1]);E=1/Math.tan(p/2);V=E/o;ca=n/(n-r);s=new H([E,0,0,0,0,V,0,0,0,0,ca,-ca*r,0,0,1,0]);N.viewMatrix=q;N.projectionMatrix=s;W=(pa=s._m11)*(ta=q._m11)+(qa=s._m12)*(ua=q._m21)+(ra=s._m13)*(va=
q._m31)+(sa=s._m14)*($=q._m41);kb=pa*(wa=q._m12)+qa*(ma=q._m22)+ra*(xa=q._m32)+sa*(ya=q._m42);T=pa*(ba=q._m13)+qa*(da=q._m23)+ra*(ga=q._m33)+sa*(ha=q._m43);L=pa*(ia=q._m14)+qa*(ja=q._m24)+ra*(X=q._m34)+sa*(Y=q._m44);R=(aa=s._m21)*ta+(U=s._m22)*ua+(na=s._m23)*va+(oa=s._m24)*$;M=aa*wa+U*ma+na*xa+oa*ya;B=aa*ba+U*da+na*ga+oa*ha;S=aa*ia+U*ja+na*X+oa*Y;mb=(Aa=s._m31)*ta+(Ba=s._m32)*ua+(Ca=s._m33)*va+(fb=s._m34)*$;P=Aa*wa+Ba*ma+Ca*xa+fb*ya;C=Aa*ba+Ba*da+Ca*ga+fb*ha;D=Aa*ia+Ba*ja+Ca*X+fb*Y;I=(gb=s._m41)*
ta+(hb=s._m42)*ua+(ib=s._m43)*va+(jb=s._m44)*$;N.matrix=new H([W,kb,T,L,R,M,B,S,mb,P,C,D,I,gb*wa+hb*ma+ib*xa+jb*ya,gb*ba+hb*da+ib*ga+jb*ha,gb*ia+hb*ja+ib*X+jb*Y])};O.prototype._updateClearedPlayer$N=function(a){var b,c,e,d;b=this.player;c=b.x-1080;e=b.y-20;d=b.z-1380;1>(0<=c?c:-c)&&1>(0<=d?d:-d)?b.y-=10*Math.sin(this.totalElapsedMsec/1E3)*a/1E3:(b.x-=c*a/1E3,b.y-=e*a/1E3,b.z-=d*a/1E3)};O.prototype._updateClearedViewpoint$=function(){var a,b,c,e,d,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,A,E,V,ca,
W,kb,T,L,R,M,B,S,C,P,D,I,K,G,O,N,J,Q,Z,za,Ia,Ua,Va,Wa,Xa,Ya,Za,Ja,Ka,ab,bb,Ma,cb,Na,db,Oa,ka,la,Pa,eb,Qa,Da,La,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,$,aa,wa,U,ma,na,xa,oa,ya,ba,da,ga,ha,ia,ja,X,Y;a=this.player;b=new m(a.x+50*Math.sin(this.totalElapsedMsec/5E3),a.y+20,a.z+50*Math.cos(this.totalElapsedMsec/5E3));c=new m(a.x,a.y,a.z);(S=this.engine.camera).target=c;S.view=b;e=S.view;d=S.target;f=S.upper;h=S.fovyX;g=S.nearZ;j=S.farZ;i=S.aspectRatio;o=new m(d.x-e.x,d.y-e.y,d.z-e.z);q=Math.sqrt((C=o.x)*
C+(P=o.y)*P+(D=o.z)*D);p=1E-9>q?new m(0,0,0):o.divSelf$N(q);s=new m((N=f.y)*(K=p.z)-(I=f.z)*(O=p.y),I*(J=p.x)-(G=f.x)*K,G*O-N*J);u=Math.sqrt((Q=s.x)*Q+(Z=s.y)*Z+(za=s.z)*za);r=1E-9>u?new m(0,0,0):s.divSelf$N(u);t=new m((Xa=p.y)*(Ua=r.z)-(Ia=p.z)*(Wa=r.y),Ia*(Ya=r.x)-(Va=p.x)*Ua,Va*Wa-Xa*Ya);v=Math.sqrt((Za=t.x)*Za+(Ja=t.y)*Ja+(Ka=t.z)*Ka);n=1E-9>v?new m(0,0,0):t.divSelf$N(v);k=new H([ab=r.x,bb=r.y,Ma=r.z,-(ab*(Na=e.x)+bb*(Oa=e.y)+Ma*(la=e.z)),cb=n.x,db=n.y,ka=n.z,-(cb*Na+db*Oa+ka*la),Pa=p.x,eb=p.y,
Qa=p.z,-(Pa*Na+eb*Oa+Qa*la),0,0,0,1]);z=1/Math.tan(h/2);F=z/i;x=j/(j-g);l=new H([z,0,0,0,0,F,0,0,0,0,x,-x*g,0,0,1,0]);S.viewMatrix=k;S.projectionMatrix=l;y=(Da=l._m11)*(ea=k._m11)+(La=l._m12)*(fa=k._m21)+(Ea=l._m13)*(Ga=k._m31)+(Fa=l._m14)*(Ha=k._m41);w=Da*(qa=k._m12)+La*(sa=k._m22)+Ea*(ua=k._m32)+Fa*($=k._m42);A=Da*(aa=k._m13)+La*(wa=k._m23)+Ea*(U=k._m33)+Fa*(ma=k._m43);E=Da*(na=k._m14)+La*(xa=k._m24)+Ea*(oa=k._m34)+Fa*(ya=k._m44);V=(pa=l._m21)*ea+(ra=l._m22)*fa+(ta=l._m23)*Ga+(va=l._m24)*Ha;ca=
pa*qa+ra*sa+ta*ua+va*$;W=pa*aa+ra*wa+ta*U+va*ma;kb=pa*na+ra*xa+ta*oa+va*ya;T=(ba=l._m31)*ea+(da=l._m32)*fa+(ga=l._m33)*Ga+(ha=l._m34)*Ha;L=ba*qa+da*sa+ga*ua+ha*$;R=ba*aa+da*wa+ga*U+ha*ma;M=ba*na+da*xa+ga*oa+ha*ya;B=(ia=l._m41)*ea+(ja=l._m42)*fa+(X=l._m43)*Ga+(Y=l._m44)*Ha;S.matrix=new H([y,w,A,E,V,ca,W,kb,T,L,R,M,B,ia*qa+ja*sa+X*ua+Y*$,ia*aa+ja*wa+X*U+Y*ma,ia*na+ja*xa+X*oa+Y*ya])};O.prototype._renderPlayer$LContext3D$=function(a){var b,c,e,d,f,h,g,j,i,k,l,p,r,n,o,q,m,u,t,v,z,F,x,y,w,A;(b=this.player).y<
-b.radius?Kb(a,5):Kb(a,3);b=(e=this.player).x;c=e.y-12;e=e.z;d=a._worldMatrix;f=d._m11;h=d._m12;g=d._m13;j=d._m14;i=d._m21;k=d._m22;l=d._m23;p=d._m24;r=d._m31;n=d._m32;o=d._m33;q=d._m34;m=d._m41;u=d._m42;t=d._m43;v=d._m44;d._m11=1*f+0*h+0*g+0*j;d._m12=0*f+1*h+0*g+0*j;d._m13=0*f+0*h+1*g+0*j;d._m14=f*b+h*c+g*e+1*j;d._m21=1*i+0*k+0*l+0*p;d._m22=0*i+1*k+0*l+0*p;d._m23=0*i+0*k+1*l+0*p;d._m24=i*b+k*c+l*e+1*p;d._m31=1*r+0*n+0*o+0*q;d._m32=0*r+1*n+0*o+0*q;d._m33=0*r+0*n+1*o+0*q;d._m34=r*b+n*c+o*e+1*q;d._m41=
1*m+0*u+0*t+0*v;d._m42=0*m+1*u+0*t+0*v;d._m43=0*m+0*u+1*t+0*v;d._m44=m*b+u*c+t*e+1*v;d=this.player.rot;b=a._worldMatrix;g=2*(x=d.x)*x;j=2*(y=d.y)*y;e=2*(w=d.z)*w;c=2*x*y;f=2*x*w;h=2*y*w;i=2*x*(x=d.t);k=2*y*x;d=2*w*x;w=1-j-e;y=c+d;x=f-k;c-=d;e=1-g-e;d=h+i;f+=k;h-=i;A=1-g-j;g=b._m11;j=b._m12;i=b._m13;k=b._m14;l=b._m21;p=b._m22;r=b._m23;n=b._m24;o=b._m31;q=b._m32;m=b._m33;u=b._m34;t=b._m41;v=b._m42;z=b._m43;F=b._m44;b._m11=g*w+j*c+i*f+0*k;b._m12=g*y+j*e+i*h+0*k;b._m13=g*x+j*d+i*A+0*k;b._m14=0*g+0*j+
0*i+1*k;b._m21=l*w+p*c+r*f+0*n;b._m22=l*y+p*e+r*h+0*n;b._m23=l*x+p*d+r*A+0*n;b._m24=0*l+0*p+0*r+1*n;b._m31=o*w+q*c+m*f+0*u;b._m32=o*y+q*e+m*h+0*u;b._m33=o*x+q*d+m*A+0*u;b._m34=0*o+0*q+0*m+1*u;b._m41=t*w+v*c+z*f+0*F;b._m42=t*y+v*e+z*h+0*F;b._m43=t*x+v*d+z*A+0*F;b._m44=0*t+0*v+0*z+1*F;Sc(a,this.player.radius,6);a._worldMatrix=new Cb};O.prototype._renderTrees$LContext3D$=function(a){Kb(a,3);this.trees.forEach$F$LVector$V$(function(b){var c,e,d,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v;c=b.x;e=b.y;b=b.z;a._matrixStack.prepend$LMatrix$(a._worldMatrix.copy$());
d=a._worldMatrix;f=d._m11;h=d._m12;g=d._m13;j=d._m14;i=d._m21;k=d._m22;l=d._m23;p=d._m24;r=d._m31;n=d._m32;o=d._m33;q=d._m34;s=d._m41;u=d._m42;t=d._m43;v=d._m44;d._m11=1*f+0*h+0*g+0*j;d._m12=0*f+1*h+0*g+0*j;d._m13=0*f+0*h+1*g+0*j;d._m14=f*c+h*e+g*b+1*j;d._m21=1*i+0*k+0*l+0*p;d._m22=0*i+1*k+0*l+0*p;d._m23=0*i+0*k+1*l+0*p;d._m24=i*c+k*e+l*b+1*p;d._m31=1*r+0*n+0*o+0*q;d._m32=0*r+1*n+0*o+0*q;d._m33=0*r+0*n+1*o+0*q;d._m34=r*c+n*e+o*b+1*q;d._m41=1*s+0*u+0*t+0*v;d._m42=0*s+1*u+0*t+0*v;d._m43=0*s+0*u+1*t+
0*v;d._m44=s*c+u*e+t*b+1*v;Uc(a,new m(0,0,0),50,34,"./image/tree.png");a._worldMatrix=a._matrixStack.removeFirst$()})};O.prototype._renderItems$LContext3D$=function(a){var b,c,e,d,f;Kb(a,3);b=3.141592653589793*this.totalElapsedMsec/1E3;c=Math.cos(b/2);e=Math.sin(b/2);d=0*e;f=0*e;this.items.forEach$F$LVector$V$(function(b){var g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,A,E,V,ca,W,B;g=b.x;j=b.y;b=b.z;a._matrixStack.prepend$LMatrix$(a._worldMatrix.copy$());i=a._worldMatrix;k=i._m11;l=i._m12;p=i._m13;r=i._m14;
n=i._m21;o=i._m22;q=i._m23;s=i._m24;u=i._m31;t=i._m32;v=i._m33;z=i._m34;F=i._m41;x=i._m42;y=i._m43;w=i._m44;i._m11=1*k+0*l+0*p+0*r;i._m12=0*k+1*l+0*p+0*r;i._m13=0*k+0*l+1*p+0*r;i._m14=k*g+l*j+p*b+1*r;i._m21=1*n+0*o+0*q+0*s;i._m22=0*n+1*o+0*q+0*s;i._m23=0*n+0*o+1*q+0*s;i._m24=n*g+o*j+q*b+1*s;i._m31=1*u+0*t+0*v+0*z;i._m32=0*u+1*t+0*v+0*z;i._m33=0*u+0*t+1*v+0*z;i._m34=u*g+t*j+v*b+1*z;i._m41=1*F+0*x+0*y+0*w;i._m42=0*F+1*x+0*y+0*w;i._m43=0*F+0*x+1*y+0*w;i._m44=F*g+x*j+y*b+1*w;g=a._worldMatrix;o=2*d*d;
q=2*e*e;l=2*f*f;k=2*d*e;r=2*d*f;n=2*e*f;s=2*d*c;u=2*e*c;p=2*f*c;j=1-q-l;b=k+p;i=r-u;k-=p;l=1-o-l;p=n+s;r+=u;n-=s;B=1-o-q;o=g._m11;q=g._m12;s=g._m13;u=g._m14;t=g._m21;v=g._m22;z=g._m23;F=g._m24;x=g._m31;y=g._m32;w=g._m33;A=g._m34;E=g._m41;V=g._m42;ca=g._m43;W=g._m44;g._m11=o*j+q*k+s*r+0*u;g._m12=o*b+q*l+s*n+0*u;g._m13=o*i+q*p+s*B+0*u;g._m14=0*o+0*q+0*s+1*u;g._m21=t*j+v*k+z*r+0*F;g._m22=t*b+v*l+z*n+0*F;g._m23=t*i+v*p+z*B+0*F;g._m24=0*t+0*v+0*z+1*F;g._m31=x*j+y*k+w*r+0*A;g._m32=x*b+y*l+w*n+0*A;g._m33=
x*i+y*p+w*B+0*A;g._m34=0*x+0*y+0*w+1*A;g._m41=E*j+V*k+ca*r+0*W;g._m42=E*b+V*l+ca*n+0*W;g._m43=E*i+V*p+ca*B+0*W;g._m44=0*E+0*V+0*ca+1*W;Vc(a,[new m(-15,-10,0),new m(15,-10,0),new m(15,10,0),new m(-15,10,0)],"./image/redbull_free.png",2,2,1,1);a._worldMatrix=a._matrixStack.removeFirst$()})};O.prototype._renderField$LContext3D$=function(a){var b,c,e,d,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t;b=new za(192,192,192);c=new za(160,255,160);e=new za(96,255,96);Kb(a,4);Fb(a,0,60,60,180,-20,30,b,b);Fb(a,0,450,600,600,
-20,30,c,e);Fb(a,0,780,60,60,-20,30,e,c);Fb(a,270,840,600,60,-20,30,e,c);a._matrixStack.prepend$LMatrix$(a._worldMatrix.copy$());b=new m(0,0,0);a._polygonList=new Eb;a._groupCenter=b;a._ignoringZHidden=!0;b=a._worldMatrix;d=b._m11;f=b._m12;h=b._m13;g=b._m14;j=b._m21;i=b._m22;k=b._m23;l=b._m24;p=b._m31;r=b._m32;n=b._m33;o=b._m34;q=b._m41;s=b._m42;u=b._m43;t=b._m44;b._m11=1*d+0*f+0*h+0*g;b._m12=0*d+1*f+0*h+0*g;b._m13=0*d+0*f+1*h+0*g;b._m14=510*d+0*f+510*h+1*g;b._m21=1*j+0*i+0*k+0*l;b._m22=0*j+1*i+0*
k+0*l;b._m23=0*j+0*i+1*k+0*l;b._m24=510*j+0*i+510*k+1*l;b._m31=1*p+0*r+0*n+0*o;b._m32=0*p+1*r+0*n+0*o;b._m33=0*p+0*r+1*n+0*o;b._m34=510*p+0*r+510*n+1*o;b._m41=1*q+0*s+0*u+0*t;b._m42=0*q+1*s+0*u+0*t;b._m43=0*q+0*s+1*u+0*t;b._m44=510*q+0*s+510*u+1*t;for(b=0;10>b;b++)for(d=0;2>d;d++)f=0===(b+d)%2?c:e,qc(a,30*d+15,-20+5*(9-b),30*b+15,30,f);for(b=0;10>b;b++)for(d=0;2>d;d++)f=0===(b+d)%2?c:e,qc(a,30*d+15,-20+5*(9-b),30*-b-15,30,f);gc(a);a._worldMatrix=a._matrixStack.removeFirst$();Fb(a,810,180,600,60,-20,
30,e,c);a._matrixStack.prepend$LMatrix$(a._worldMatrix.copy$());b=new m(0,0,0);a._polygonList=new Eb;a._groupCenter=b;a._ignoringZHidden=!0;b=a._worldMatrix;d=b._m11;f=b._m12;h=b._m13;g=b._m14;j=b._m21;i=b._m22;k=b._m23;l=b._m24;p=b._m31;r=b._m32;n=b._m33;o=b._m34;q=b._m41;s=b._m42;u=b._m43;t=b._m44;b._m11=1*d+0*f+0*h+0*g;b._m12=0*d+1*f+0*h+0*g;b._m13=0*d+0*f+1*h+0*g;b._m14=1110*d+0*f+150*h+1*g;b._m21=1*j+0*i+0*k+0*l;b._m22=0*j+1*i+0*k+0*l;b._m23=0*j+0*i+1*k+0*l;b._m24=1110*j+0*i+150*k+1*l;b._m31=
1*p+0*r+0*n+0*o;b._m32=0*p+1*r+0*n+0*o;b._m33=0*p+0*r+1*n+0*o;b._m34=1110*p+0*r+150*n+1*o;b._m41=1*q+0*s+0*u+0*t;b._m42=0*q+1*s+0*u+0*t;b._m43=0*q+0*s+1*u+0*t;b._m44=1110*q+0*s+150*u+1*t;for(b=0;4>b;b++)for(d=0;22>d;d++)f=0===(b+d)%2?c:e,Ob(a,[new m(40*b,-20+20*b,30*d),new m(40*b,-20+20*b,30*(d+1)),new m(40*(b+1),-20+20*(b+1),30*(d+1)),new m(40*(b+1),-20+20*(b+1),30*d)],f);gc(a);a._worldMatrix=a._matrixStack.removeFirst$();Fb(a,1080,1050,60,600,-20,30,e,c);Fb(a,1080,1380,60,60,-20,15,new za(255,215,
0),new za(255,255,255));Kb(a,3)};O.prototype._setMobileOperation$=function(){var a=this;Q.window.addEventListener("devicemotion",function(b){var c,e,d,b=b instanceof DeviceMotionEvent?b:null;c=30*b.accelerationIncludingGravity.y;b=30*b.accelerationIncludingGravity.x/2;c=120>=c?c:120;-60>c?(c=e=a.player,c.isBraking=!0,qb(e,0,b/4)):0>c?(c=e=a.player,c.isBraking=!1,qb(e,0,b/2)):(e=d=a.player,e.isBraking=!1,qb(d,c,b))});Q.window.addEventListener("touchstart",function(){a.isStarted?a.player.vy=80:(a.isStarted=
!0,a.player.vz=100)})};O.prototype._setPCOperation$=function(){var a=this;Q.window.document.addEventListener("keypress",function(b){var c;if(a.isStarted)switch(b=b instanceof KeyboardEvent?b:null,b.keyCode){case 119:b=c=a.player;b.isBraking=!1;qb(c,100,0);break;case 115:b=a.player;b.isBraking=!0;break;case 97:b=c=a.player;b.isBraking=!1;qb(c,0,-50);break;case 100:b=c=a.player;b.isBraking=!1;qb(c,0,50);break;case 104:b=c=a.player;b.isBraking=!1;qb(c,0,-50);break;case 106:b=a.player;b.isBraking=!0;
break;case 107:b=c=a.player;b.isBraking=!1;qb(c,100,0);break;case 108:b=c=a.player;b.isBraking=!1;qb(c,0,50);break;case 113:b=a.engine;b._isRunning=!1;break;case 32:a.player.vy=80}else a.isStarted=!0,a.player.vz=100},!1)};O.prototype.run$=function(){this.engine.start$()};$b.prototype={};yc.prototype=new $b;$b.main$AS=function(){(new hc).engine.start$()};D.prototype={};m.prototype=new D;K.prototype=new D;zc.prototype=new D;D.origin$=function(){return new m(0,0,0)};D.prototype.add$LVector$=function(a){return new m(this.x+
a.x,this.y+a.y,this.z+a.z)};D.prototype.addSelf$LVector$=function(a){this.x+=a.x;this.y+=a.y;this.z+=a.z;return this};D.prototype.sub$LVector$=function(a){return new m(this.x-a.x,this.y-a.y,this.z-a.z)};D.prototype.subSelf$LVector$=function(a){this.x-=a.x;this.y-=a.y;this.z-=a.z;return this};D.prototype.mul$N=function(a){return new m(this.x*a,this.y*a,this.z*a)};D.prototype.mulSelf$N=function(a){this.x*=a;this.y*=a;this.z*=a;return this};D.prototype.div$N=function(a){return new m(this.x/a,this.y/
a,this.z/a)};D.prototype.divSelf$N=function(a){this.x/=a;this.y/=a;this.z/=a;return this};D.prototype.dot$LVector$=function(a){return this.x*a.x+this.y*a.y+this.z*a.z};D.prototype.cross$LVector$=function(a){var b,c,e,d,f,h;return new m((f=this.y)*(c=a.z)-(b=this.z)*(d=a.y),b*(h=a.x)-(e=this.x)*c,e*d-f*h)};D.prototype.crossSelf$LVector$=function(a){var b,c,e,d,f;b=(f=this.y)*(c=a.z)-(e=this.z)*(d=a.y);c=e*(e=a.x)-(a=this.x)*c;this.x=b;this.y=c;this.z=a*d-f*e;return this};D.prototype.unit$=function(){var a,
b,c,e;a=Math.sqrt((b=this.x)*b+(c=this.y)*c+(e=this.z)*e);return 1E-9>a?new m(0,0,0):new m(this.x/a,this.y/a,this.z/a)};D.prototype.unitSelf$=function(){var a,b,c,e;a=Math.sqrt((b=this.x)*b+(c=this.y)*c+(e=this.z)*e);return 1E-9>a?new m(0,0,0):this.divSelf$N(a)};D.prototype.sqabs$=function(){var a,b,c;return(a=this.x)*a+(b=this.y)*b+(c=this.z)*c};D.prototype.abs$=function(){var a,b,c;return Math.sqrt((a=this.x)*a+(b=this.y)*b+(c=this.z)*c)};D.prototype.rotateX$N=function(a){var b,c,e;b=Math.sin(a);
a=Math.cos(a);return new m(this.x,(e=this.y)*a-(c=this.z)*b,c*a+e*b)};D.prototype.rotateXSelf$N=function(a){var b,c,e,d;b=Math.sin(a);a=Math.cos(a);this.y=c=(d=this.y)*a-(e=this.z)*b;this.z=e*a+d*b;return this};D.prototype.rotateY$N=function(a){var b,c,e;b=Math.sin(a);a=Math.cos(a);return new m((e=this.x)*a+(c=this.z)*b,this.y,c*a-e*b)};D.prototype.rotateYSelf$N=function(a){var b,c,e,d;b=Math.sin(a);a=Math.cos(a);this.x=c=(d=this.x)*a+(e=this.z)*b;this.z=e*a-d*b;return this};D.prototype.rotateZ$N=
function(a){var b,c,e;b=Math.sin(a);a=Math.cos(a);return new m(this.x*a-(c=this.y)*b,c*a+(e=this.z)*b,e)};D.prototype.rotateZSelf$N=function(a){var b,c,e;b=Math.sin(a);c=Math.cos(a);a=this.x*c-(e=this.y)*b;b=e*c+this.z*b;this.x=a;this.y=b;return this};D.prototype.transform$LMatrix$=function(a){var b,c,e,d,f;b=a._m11*(c=this.x)+a._m12*(e=this.y)+a._m13*(d=this.z)+a._m14*(f=this.w);return new K(b,a._m21*c+a._m22*e+a._m23*d+a._m24*f,a._m31*c+a._m32*e+a._m33*d+a._m34*f,a._m41*c+a._m42*e+a._m43*d+a._m44*
f)};D.prototype.transformSelf$LMatrix$=function(a){var b,c,e,d,f,h,g;b=a._m11*(d=this.x)+a._m12*(f=this.y)+a._m13*(h=this.z)+a._m14*(g=this.w);c=a._m21*d+a._m22*f+a._m23*h+a._m24*g;e=a._m31*d+a._m32*f+a._m33*h+a._m34*g;a=a._m41*d+a._m42*f+a._m43*h+a._m44*g;this.x=b/a;this.y=c/a;this.z=e/a;this.w=1;return this};D.prototype.toString=function(){var a;a=function(a){var c,e,a=a.toFixed(1);c=a.length;for(e=0;e<8-c;e++)a=" "+a;return a};return"("+a(this.x)+","+a(this.y)+","+a(this.z)+","+a(this.w)+")"};
J.prototype={};Cb.prototype=new J;H.prototype=new J;J.prototype.copy$=function(){return new H([this._m11,this._m12,this._m13,this._m14,this._m21,this._m22,this._m23,this._m24,this._m31,this._m32,this._m33,this._m34,this._m41,this._m42,this._m43,this._m44])};J.translating$LVector$=function(a){return new H([1,0,0,a.x,0,1,0,a.y,0,0,1,a.z,0,0,0,1])};J.translating$NNN=function(a,b,c){return new H([1,0,0,a,0,1,0,b,0,0,1,c,0,0,0,1])};J.rotatingX$N=function(a){var b;b=Math.sin(a);a=Math.cos(a);return new H([1,
0,0,0,0,a,-b,0,0,b,a,0,0,0,0,1])};J.rotatingY$N=function(a){var b;b=Math.sin(a);a=Math.cos(a);return new H([a,0,b,0,0,1,0,0,-b,0,a,0,0,0,0,1])};J.rotatingZ$N=function(a){var b;b=Math.sin(a);a=Math.cos(a);return new H([a,-b,0,0,b,a,0,0,0,0,1,0,0,0,0,1])};J.scaling$NNN=function(a,b,c){return new H([a,0,0,0,0,b,0,0,0,0,c,0,0,0,0,1])};J.prototype.mul$LVector$=function(a){var b,c,e,d,a=this._m11*(b=a.x)+this._m12*(c=a.y)+this._m13*(e=a.z)+this._m14*(d=a.w);return new K(a,this._m21*b+this._m22*c+this._m23*
e+this._m24*d,this._m31*b+this._m32*c+this._m33*e+this._m34*d,this._m41*b+this._m42*c+this._m43*e+this._m44*d)};J.prototype.compose$LMatrix$=function(a){var b,c,e,d,f,h,g,j,i,k,l,p,r,n,o,m,s,u,t,v,z,F,x,y,w,A,E,V,ca,B;b=(g=this._m11)*(k=a._m11)+(j=this._m12)*(l=a._m21)+(i=this._m13)*(p=a._m31)+(d=this._m14)*(h=a._m41);c=g*(n=a._m12)+j*(m=a._m22)+i*(u=a._m32)+d*(v=a._m42);e=g*(z=a._m13)+j*(F=a._m23)+i*(x=a._m33)+d*(y=a._m43);a=g*(g=a._m14)+j*(j=a._m24)+i*(i=a._m34)+d*(w=a._m44);d=(r=this._m21)*k+(o=
this._m22)*l+(s=this._m23)*p+(t=this._m24)*h;f=(A=this._m31)*k+(E=this._m32)*l+(V=this._m33)*p+(ca=this._m34)*h;h=(B=this._m41)*k+(k=this._m42)*l+(l=this._m43)*p+(p=this._m44)*h;return new H([b,c,e,a,d,r*n+o*m+s*u+t*v,r*z+o*F+s*x+t*y,r*g+o*j+s*i+t*w,f,A*n+E*m+V*u+ca*v,A*z+E*F+V*x+ca*y,A*g+E*j+V*i+ca*w,h,B*n+k*m+l*u+p*v,B*z+k*F+l*x+p*y,B*g+k*j+l*i+p*w])};J.prototype.composeSelf$LMatrix$=function(a){var b,c,e,d,f,h,g,j,i,k,l,p,m,n,o,q,s,u,t,v,z,F,x,y,w,A,E,V;b=this._m11;c=this._m12;e=this._m13;d=this._m14;
f=this._m21;h=this._m22;g=this._m23;j=this._m24;i=this._m31;k=this._m32;l=this._m33;p=this._m34;m=this._m41;n=this._m42;o=this._m43;q=this._m44;this._m11=b*(s=a._m11)+c*(u=a._m21)+e*(t=a._m31)+d*(v=a._m41);this._m12=b*(z=a._m12)+c*(F=a._m22)+e*(x=a._m32)+d*(y=a._m42);this._m13=b*(w=a._m13)+c*(A=a._m23)+e*(E=a._m33)+d*(V=a._m43);this._m14=b*(b=a._m14)+c*(c=a._m24)+e*(e=a._m34)+d*(a=a._m44);this._m21=f*s+h*u+g*t+j*v;this._m22=f*z+h*F+g*x+j*y;this._m23=f*w+h*A+g*E+j*V;this._m24=f*b+h*c+g*e+j*a;this._m31=
i*s+k*u+l*t+p*v;this._m32=i*z+k*F+l*x+p*y;this._m33=i*w+k*A+l*E+p*V;this._m34=i*b+k*c+l*e+p*a;this._m41=m*s+n*u+o*t+q*v;this._m42=m*z+n*F+o*x+q*y;this._m43=m*w+n*A+o*E+q*V;this._m44=m*b+n*c+o*e+q*a;return this};J.prototype.toString=function(){var a,b;a=function(a){var b,d,a=a.toFixed(1);b=a.length;for(d=0;d<8-b;d++)a=" "+a;return a};b=""+("|"+a(this._m11)+","+a(this._m12)+","+a(this._m13)+","+a(this._m14)+"|\n");b+="|"+a(this._m21)+","+a(this._m22)+","+a(this._m23)+","+a(this._m24)+"|\n";b+="|"+a(this._m31)+
","+a(this._m32)+","+a(this._m33)+","+a(this._m34)+"|\n";return b+="|"+a(this._m41)+","+a(this._m42)+","+a(this._m43)+","+a(this._m44)+"|\n"};J.prototype.invert$=function(){var a,b,c,e,d,f;e=[this._m11,this._m12,this._m13,this._m14,this._m21,this._m22,this._m23,this._m24,this._m31,this._m32,this._m33,this._m34,this._m41,this._m42,this._m43,this._m44];d=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];for(a=0;3>a;a++){c=e[4*a+a];for(b=0;4>b;b++)e[4*a+b]/=c,d[4*a+b]/=c;for(b=a+1;4>b;b++){f=e[4*b+a];for(c=0;4>c;c++)e[4*
b+c]-=e[4*a+c]*f,d[4*b+c]-=d[4*a+c]*f}}for(a=3;0<a;a--)for(b=a-1;0<=b;b--){f=e[4*b+a];for(c=0;4>c;c++)e[4*b+c]-=e[4*a+c]*f,d[4*b+c]-=d[4*a+c]*f}return new H(d)};Z.prototype={};Ac.prototype=new Z;Bc.prototype=new Z;zb.prototype=new Z;Z.prototype.copy$=function(){return new zb(this.t,this.x,this.y,this.z)};Z.prototype.mul$LQuaternion$=function(a){var b,c,e,d,f,h,g,j,i;b=new zb(this.t,this.x,this.y,this.z);a=(c=b.t)*(d=a.t)-((f=b.x)*(e=a.x)+(h=b.y)*(i=a.y)+(j=b.z)*(g=a.z));b.t=a;b.x=c*e+d*f+(h*g-j*i);
b.y=c*i+d*h+(j*e-f*g);b.z=c*g+d*j+(f*i-h*e);return b};Z.prototype.mulSelf$LQuaternion$=function(a){var b,c,e,d,f,h,g,j;this.t=a=(b=this.t)*(e=a.t)-((d=this.x)*(c=a.x)+(f=this.y)*(j=a.y)+(g=this.z)*(h=a.z));this.x=b*c+e*d+(f*h-g*j);this.y=b*j+e*f+(g*c-d*h);this.z=b*h+e*g+(d*j-f*c);return this};Z.prototype.toMatrix$=function(){var a,b,c,e,d,f,h,g,j,i;a=2*(h=this.x)*h;b=2*(g=this.y)*g;c=2*(j=this.z)*j;e=2*h*g;d=2*h*j;f=2*g*j;h=2*h*(i=this.t);g=2*g*i;j=2*j*i;return new H([1-b-c,e+j,d-g,0,e-j,1-a-c,f+
h,0,d+g,f-h,1-a-b,0,0,0,0,1])};Z.prototype.toString=function(){var a,b,c;a=this.x.toFixed(3);b=this.y.toFixed(3);c=this.z.toFixed(3);return this.t.toFixed(3)+" : ("+a+", "+b+", "+c+", )"};Z.rotating$NNNN=function(a,b,c,e){var d;d=Math.cos(a/2);a=Math.sin(a/2);return new zb(d,b*a,c*a,e*a)};var vc=Z.rotating$NNNN;Z.rotating$NLVector$=function(a,b){var c,e,d,f,h;c=b.x;e=b.y;d=b.z;f=Math.cos(a/2);h=Math.sin(a/2);return new zb(f,c*h,e*h,d*h)};Z.rotate$LVector$LVector$N=function(a,b,c){var e,d,f,h,g,j,
i,k,l,p;e=Math.cos(c/2);d=Math.sin(c/2);c=a.x;h=a.y;g=a.z;a=b.x*d;j=b.y*d;i=b.z*d;k=-b.x*d;l=-b.y*d;p=-b.z*d;b=0*e-(k*c+l*h+p*g);d=e*c+0*k+(l*g-p*h);f=e*h+0*l+(p*c-k*g);c=e*g+0*p+(k*h-l*c);return new m(b*a+e*d+(f*i-c*j),b*j+e*f+(c*a-d*i),b*i+e*c+(d*j-f*a))};I.prototype={};ic.prototype=new I;I.prototype.isMobile$=function(){return this._isMobile};I.loadImages$AS=function(a){var b,c,e,d,f;c=Q.document.getElementById("tmp_canvas");c=c instanceof HTMLElement?c:null;c=(c instanceof HTMLCanvasElement?c:
null).getContext("2d");b=c instanceof CanvasRenderingContext2D?c:null;c=function(a){I.images[a].onload=function(){var c;c=I.images[a];I.isLoadedImage[a]=!0;b.drawImage(c,0,0);I.imageDatas[a]=b.getImageData(0,0,c.width,c.height)}};for(e=0;e<a.length;e++)d=a[e],f=Q.document.createElement("img"),f=f instanceof HTMLImageElement?f:null,f.src=d,I.isLoadedImage[d]=!1,I.images[d]=f,c(d)};var Qc=I.loadImages$AS;I.prototype.setSkyImage$S=function(a){this._skyImageSrc=a;this._skyImage=I.images[a]};I.prototype.start$=
function(){var a=this,b,c;b={_stopwatch:{_elapsedMsec:0,_startedMsec:null,_lastLapMsec:null},_recentlyMsecLog:[],_lastMsec:0,_fpsElement:null,_enabledHtmlLog:!1,_enabledConsoleLog:!0,_enabledHtmlLog:!1,_enabledConsoleLog:!1};Nc(b._stopwatch);this._isRunning=!0;c=function(){var e,d;Wc(b);e=b._lastMsec;a.onUpdate(e);d={_worldMatrix:new Cb,_matrixStack:new lc,camera:a.camera,_depth:3,modelList1:new nb,modelList2:new nb,modelList3:new nb,modelList4:new nb,modelList5:new nb,_polygonList:null,_groupCenter:null,
_ignoringZHidden:!1,backgroundColor:new za(90,135,158)};a._skyImage&&I.isLoadedImage[a._skyImageSrc]?(a.context.fillStyle="#"+d.backgroundColor.toHexString$(),a.context.fillRect(0,0,a._width,a._height),a.renderSkyImage$()):(a.context.fillStyle="#"+d.backgroundColor.toHexString$(),a.context.fillRect(0,0,a._width,a._height));a.onRender(d,e);d.modelList5.forEach$F$LRenderable$V$(function(b){b.draw$LEngine$(a)});d.modelList4.forEach$F$LRenderable$V$(function(b){b.draw$LEngine$(a)});d.modelList3.forEach$F$LRenderable$V$(function(b){b.draw$LEngine$(a)});
d.modelList2.forEach$F$LRenderable$V$(function(b){b.draw$LEngine$(a)});d.modelList1.forEach$F$LRenderable$V$(function(b){b.draw$LEngine$(a)});a._isRunning&&B.global.setTimeout(c,0)};B.global.setTimeout(function(){Q.window.scrollTo(0,1)},500);B.global.setTimeout(c,0)};I.prototype.stop$=function(){this._isRunning=!1};I.prototype.renderSkyImage$=function(){var a,b,c,e,d,f,h,g,j,i;d=(e=this.camera).target;f=e.view;e=d.x-f.x;a=d.y-f.y;d=d.z-f.z;a=-a;b=Math.atan2(e,d);c=Math.atan2(a,Math.sqrt(e*e+d*d));
e=(d=this._skyImage).width;a=d.height;d=(f=this.camera).fovyX/3.141592653589793/2*e;f=d*f.aspectRatio;b=(b/3.141592653589793/2+0.5)*e-d/2;c=(c/3.141592653589793+0.5)*a-f/2;0>b&&(b+=e);0>c&&(c+=a);h=b+d>=e;g=c+f>=a;h&&g?(j=(e-b)/d,f=(a-c)/f,this.context.drawImage(this._skyImage,~~b,~~c,~~(e-b),~~(a-c),0,0,~~(this._width*j),~~(this._height*f)),0!==~~(b+d-e)&&this.context.drawImage(this._skyImage,0,~~c,~~(b+d-e),~~(a-c),~~((i=this._width)*j),0,~~(i*(1-j)),~~(this._height*f))):h?(i=(e-b)/d,0!==~~(e-b)&&
0!==~~(this._width*i)&&this.context.drawImage(this._skyImage,~~b,~~c,~~(e-b),~~f,0,0,~~(this._width*i),this._height),0!==~~(b+d-e)&&0!==~~(this._width*(1-i))&&this.context.drawImage(this._skyImage,0,~~c,~~(b+d-e),~~f,~~((j=this._width)*i),0,~~(j*(1-i)),this._height)):g?this.context.drawImage(this._skyImage,~~b,~~c,~~d,~~(a-c),0,0,this._width,~~(this._height*((a-c)/f))):this.context.drawImage(this._skyImage,~~b,~~c,~~d,~~f,0,0,this._width,this._height)};I.prototype.setScreenMatrix$NN=function(a,b){var c,
e,d,f,h,g,j,i,k,l,p,m,n,o,q,s,u,t,v;c=new H([1,0,0,a/2,0,1,0,b/2,0,0,1,0,0,0,0,1]);t=a/2;v=-b/2;e=c._m11;d=c._m12;f=c._m13;h=c._m14;g=c._m21;j=c._m22;i=c._m23;k=c._m24;l=c._m31;p=c._m32;m=c._m33;n=c._m34;o=c._m41;q=c._m42;s=c._m43;u=c._m44;c._m11=e*t+0*d+0*f+0*h;c._m12=0*e+d*v+0*f+0*h;c._m13=0*e+0*d+1*f+0*h;c._m14=0*e+0*d+0*f+1*h;c._m21=g*t+0*j+0*i+0*k;c._m22=0*g+j*v+0*i+0*k;c._m23=0*g+0*j+1*i+0*k;c._m24=0*g+0*j+0*i+1*k;c._m31=l*t+0*p+0*m+0*n;c._m32=0*l+p*v+0*m+0*n;c._m33=0*l+0*p+1*m+0*n;c._m34=0*
l+0*p+0*m+1*n;c._m41=o*t+0*q+0*s+0*u;c._m42=0*o+q*v+0*s+0*u;c._m43=0*o+0*q+1*s+0*u;c._m44=0*o+0*q+0*s+1*u;this.screenMatrix=c};I.prototype.updateMatrix$=function(){var a,b,c,e,d,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,A,E,V,B,W,C,T,L,R,M,D,S,I,P,K,G;a=this.camera;b=a.view;c=a.target;e=a.upper;d=a.fovyX;f=a.nearZ;h=a.farZ;g=a.aspectRatio;c=new m(c.x-b.x,c.y-b.y,c.z-b.z);p=Math.sqrt((i=c.x)*i+(u=c.y)*u+(t=c.z)*t);i=1E-9>p?new m(0,0,0):c.divSelf$N(p);e=new m((x=e.y)*(v=i.z)-(r=e.z)*(F=i.y),r*(y=i.x)-
(z=e.x)*v,z*F-x*y);r=Math.sqrt((k=e.x)*k+(n=e.y)*n+(w=e.z)*w);k=1E-9>r?new m(0,0,0):e.divSelf$N(r);n=new m((V=i.y)*(q=k.z)-(o=i.z)*(E=k.y),o*(B=k.x)-(A=i.x)*q,A*E-V*B);o=Math.sqrt((l=n.x)*l+(W=n.y)*W+(C=n.z)*C);l=1E-9>o?new m(0,0,0):n.divSelf$N(o);b=new H([T=k.x,L=k.y,R=k.z,-(T*(D=b.x)+L*(I=b.y)+R*(P=b.z)),M=l.x,S=l.y,s=l.z,-(M*D+S*I+s*P),j=i.x,K=i.y,G=i.z,-(j*D+K*I+G*P),0,0,0,1]);d=1/Math.tan(d/2);h/=h-f;j=new H([d,0,0,0,0,d/g,0,0,0,0,h,-h*f,0,0,1,0]);a.viewMatrix=b;a.projectionMatrix=j;f=(P=j._m11)*
(C=b._m11)+(G=j._m12)*(l=b._m21)+(W=j._m13)*(K=b._m31)+(o=j._m14)*(s=b._m41);g=P*(d=b._m12)+G*(T=b._m22)+W*(L=b._m32)+o*(R=b._m42);h=P*(M=b._m13)+G*(D=b._m23)+W*(S=b._m33)+o*(I=b._m43);b=P*(P=b._m14)+G*(G=b._m24)+W*(W=b._m34)+o*(k=b._m44);o=(A=j._m21)*C+(E=j._m22)*l+(V=j._m23)*K+(B=j._m24)*s;q=(n=j._m31)*C+(w=j._m32)*l+(r=j._m33)*K+(v=j._m34)*s;s=(z=j._m41)*C+(C=j._m42)*l+(l=j._m43)*K+(j=j._m44)*s;a.matrix=new H([f,g,h,b,o,A*d+E*T+V*L+B*R,A*M+E*D+V*S+B*I,A*P+E*G+V*W+B*k,q,n*d+w*T+r*L+v*R,n*M+w*D+
r*S+v*I,n*P+w*G+r*W+v*k,s,z*d+C*T+l*L+j*R,z*M+C*D+l*S+j*I,z*P+C*G+l*W+j*k])};C.prototype={};Cc.prototype=new C;C.setDepth$LContext3D$I=function(a,b){if(!(1<=b&&5>=b)){debugger;throw Error("[jsx/engine.jsx:275] assertion failure");}a._depth=b};var Kb=C.setDepth$LContext3D$I;C.getDepth$LContext3D$=function(a){return a._depth};C.setBackgroundColor$LContext3D$LColor$=function(a,b){a.backgroundColor=b};C.pushMatrix$LContext3D$=function(a){a._matrixStack.prepend$LMatrix$(a._worldMatrix.copy$())};C.popMatrix$LContext3D$=
function(a){a._worldMatrix=a._matrixStack.removeFirst$()};C.resetMatrix$LContext3D$=function(a){a._worldMatrix=new Cb};C.translate$LContext3D$NNN=function(a,b,c,e){var d,f,h,g,j,i,k,l,p,m,n,o,q,s,u,t,a=a._worldMatrix;d=a._m11;f=a._m12;h=a._m13;g=a._m14;j=a._m21;i=a._m22;k=a._m23;l=a._m24;p=a._m31;m=a._m32;n=a._m33;o=a._m34;q=a._m41;s=a._m42;u=a._m43;t=a._m44;a._m11=1*d+0*f+0*h+0*g;a._m12=0*d+1*f+0*h+0*g;a._m13=0*d+0*f+1*h+0*g;a._m14=d*b+f*c+h*e+1*g;a._m21=1*j+0*i+0*k+0*l;a._m22=0*j+1*i+0*k+0*l;a._m23=
0*j+0*i+1*k+0*l;a._m24=j*b+i*c+k*e+1*l;a._m31=1*p+0*m+0*n+0*o;a._m32=0*p+1*m+0*n+0*o;a._m33=0*p+0*m+1*n+0*o;a._m34=p*b+m*c+n*e+1*o;a._m41=1*q+0*s+0*u+0*t;a._m42=0*q+1*s+0*u+0*t;a._m43=0*q+0*s+1*u+0*t;a._m44=q*b+s*c+u*e+1*t};C.scale$LContext3D$NNN=function(a,b,c,e){var d,f,h,g,j,i,k,l,m,r,n,o,q,s,u,t,a=a._worldMatrix;d=a._m11;f=a._m12;h=a._m13;g=a._m14;j=a._m21;i=a._m22;k=a._m23;l=a._m24;m=a._m31;r=a._m32;n=a._m33;o=a._m34;q=a._m41;s=a._m42;u=a._m43;t=a._m44;a._m11=d*b+0*f+0*h+0*g;a._m12=0*d+f*c+0*
h+0*g;a._m13=0*d+0*f+h*e+0*g;a._m14=0*d+0*f+0*h+1*g;a._m21=j*b+0*i+0*k+0*l;a._m22=0*j+i*c+0*k+0*l;a._m23=0*j+0*i+k*e+0*l;a._m24=0*j+0*i+0*k+1*l;a._m31=m*b+0*r+0*n+0*o;a._m32=0*m+r*c+0*n+0*o;a._m33=0*m+0*r+n*e+0*o;a._m34=0*m+0*r+0*n+1*o;a._m41=q*b+0*s+0*u+0*t;a._m42=0*q+s*c+0*u+0*t;a._m43=0*q+0*s+u*e+0*t;a._m44=0*q+0*s+0*u+1*t};C.rotate$LContext3D$LQuaternion$=function(a,b){var c,e,d,f,h,g,j,i,k,l,m,r,n,o,q,s,u,t,v,z,F,x,y,w,A,E;c=a._worldMatrix;e=2*(y=b.x)*y;d=2*(w=b.y)*w;t=2*(A=b.z)*A;v=2*y*w;z=
2*y*A;F=2*w*A;f=2*y*(y=b.t);h=2*w*y;x=2*A*y;A=1-d-t;w=v+x;y=z-h;v-=x;t=1-e-t;x=F+f;z+=h;F-=f;E=1-e-d;e=c._m11;d=c._m12;f=c._m13;h=c._m14;g=c._m21;j=c._m22;i=c._m23;k=c._m24;l=c._m31;m=c._m32;r=c._m33;n=c._m34;o=c._m41;q=c._m42;s=c._m43;u=c._m44;c._m11=e*A+d*v+f*z+0*h;c._m12=e*w+d*t+f*F+0*h;c._m13=e*y+d*x+f*E+0*h;c._m14=0*e+0*d+0*f+1*h;c._m21=g*A+j*v+i*z+0*k;c._m22=g*w+j*t+i*F+0*k;c._m23=g*y+j*x+i*E+0*k;c._m24=0*g+0*j+0*i+1*k;c._m31=l*A+m*v+r*z+0*n;c._m32=l*w+m*t+r*F+0*n;c._m33=l*y+m*x+r*E+0*n;c._m34=
0*l+0*m+0*r+1*n;c._m41=o*A+q*v+s*z+0*u;c._m42=o*w+q*t+s*F+0*u;c._m43=o*y+q*x+s*E+0*u;c._m44=0*o+0*q+0*s+1*u};C.beginGroup$LContext3D$LVector$=function(a,b){a._polygonList=new Eb;a._groupCenter=b;a._ignoringZHidden=!1};C.beginGroup$LContext3D$LVector$B=function(a,b,c){a._polygonList=new Eb;a._groupCenter=b;a._ignoringZHidden=c};C.renderPolygonGroup$LContext3D$ALVector$LColor$=function(a,b,c){b=new Mb(b,c);b.applyWorldMatrix$LMatrix$(a._worldMatrix);b.applyViewMatrix$LMatrix$(a.camera.viewMatrix);b.isHidden$LCamera$(a.camera)||
a._polygonList.prepend$LPolygon$(b)};var Ob=C.renderPolygonGroup$LContext3D$ALVector$LColor$;C.endGroup$LContext3D$=function(a){0!==a._polygonList.length&&Jb(a,new mc(a._polygonList,a._groupCenter,a._ignoringZHidden))};var gc=C.endGroup$LContext3D$;C.renderPolygon$LContext3D$ALVector$LColor$=function(a,b,c){Jb(a,new Mb(b,c))};C.renderBillboard$LContext3D$LVector$IIS=function(a,b,c,e,d){Jb(a,new oc(b,c,e,d))};var Uc=C.renderBillboard$LContext3D$LVector$IIS;C.renderTexture$LContext3D$ALVector$SIIII=
function(a,b,c,e,d,f,h){Jb(a,new ac(b,c,e,d,f,h))};var Vc=C.renderTexture$LContext3D$ALVector$SIIII;C.renderTexture$LContext3D$ALVector$S=function(a,b,c){Jb(a,new nc(b,c))};C.renderModel$LContext3D$LRenderable$=function(a,b){b.applyWorldMatrix$LMatrix$(a._worldMatrix);b.applyViewMatrix$LMatrix$(a.camera.viewMatrix);if(!b.isHidden$LCamera$(a.camera))switch(a._depth){case 1:Pb(a,a.modelList1,b);break;case 2:Pb(a,a.modelList2,b);break;case 3:Pb(a,a.modelList3,b);break;case 4:Pb(a,a.modelList4,b);break;
case 5:Pb(a,a.modelList5,b)}};var Jb=C.renderModel$LContext3D$LRenderable$;C.insertModelByZValue$LContext3D$LList$Renderable$E$LRenderable$=function(a,b,c){var e,a=!1;for(e=b.head;null!=e;e=e._next)if(e.value.vCenter.z<c.vCenter.z){b.insertBefore$LNode$Renderable$E$LRenderable$(e,c);a=!0;break}a||b.append$LRenderable$(c)};var Pb=C.insertModelByZValue$LContext3D$LList$Renderable$E$LRenderable$;Ib.prototype={};kc.prototype=new Ib;Ib.prototype.move$LVector$=function(a){var b,c,e,d,f;c=this.rotatingMatrix;
a=c._m11*(d=a.x)+c._m12*(b=a.y)+c._m13*(e=a.z)+c._m14*(f=a.w);b=new K(a,c._m21*d+c._m22*b+c._m23*e+c._m24*f,c._m31*d+c._m32*b+c._m33*e+c._m34*f,c._m41*d+c._m42*b+c._m43*e+c._m44*f);e=this.view;e.x+=c=b.x;e.y+=d=b.y;e.z+=e=b.z;b=this.target;b.x+=c;b.y+=d;b.z+=e};Ib.prototype.rotateY$N=function(a){var b,c,e,d,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,A,E,B,C;b=this.target;c=this.view;b=new m(b.x-c.x,b.y-c.y,b.z-c.z);i=Math.sin(a);k=Math.cos(a);c=k*(l=b.x)+0*(p=b.y)+i*(r=b.z)+0*(n=b.w);e=0*l+0*p+0*r+
1*n;b.x=c/e;b.y=(0*l+1*p+0*r+0*n)/e;b.z=(-i*l+0*p+k*r+0*n)/e;b.w=1;c=this.view;b.x+=c.x;b.y+=c.y;b.z+=c.z;this.target=b;b=Math.sin(a);a=Math.cos(a);a=new H([a,0,b,0,0,1,0,0,-b,0,a,0,0,0,0,1]);d=this.rotatingMatrix;f=a._m11;h=a._m12;g=a._m13;j=a._m14;b=a._m21;c=a._m22;e=a._m23;i=a._m24;k=a._m31;l=a._m32;p=a._m33;r=a._m34;n=a._m41;o=a._m42;q=a._m43;s=a._m44;a._m11=f*(u=d._m11)+h*(t=d._m21)+g*(v=d._m31)+j*(z=d._m41);a._m12=f*(F=d._m12)+h*(x=d._m22)+g*(y=d._m32)+j*(w=d._m42);a._m13=f*(A=d._m13)+h*(E=
d._m23)+g*(B=d._m33)+j*(C=d._m43);a._m14=f*(f=d._m14)+h*(h=d._m24)+g*(g=d._m34)+j*(d=d._m44);a._m21=b*u+c*t+e*v+i*z;a._m22=b*F+c*x+e*y+i*w;a._m23=b*A+c*E+e*B+i*C;a._m24=b*f+c*h+e*g+i*d;a._m31=k*u+l*t+p*v+r*z;a._m32=k*F+l*x+p*y+r*w;a._m33=k*A+l*E+p*B+r*C;a._m34=k*f+l*h+p*g+r*d;a._m41=n*u+o*t+q*v+s*z;a._m42=n*F+o*x+q*y+s*w;a._m43=n*A+o*E+q*B+s*C;a._m44=n*f+o*h+q*g+s*d;this.rotatingMatrix=a};Ib.prototype.updateMatrix$=function(){var a,b,c,e,d,f,h,g,j,i,k,l,p,r,n,o,q,s,u,t,v,z,F,x,y,w,A,E,B,C,D,G,T,L,
R,M,I,S,K,P,O;a=this.view;b=this.target;c=this.upper;e=this.fovyX;d=this.nearZ;f=this.farZ;h=this.aspectRatio;b=new m(b.x-a.x,b.y-a.y,b.z-a.z);l=Math.sqrt((j=b.x)*j+(s=b.y)*s+(u=b.z)*u);j=1E-9>l?new m(0,0,0):b.divSelf$N(l);c=new m((F=c.y)*(t=j.z)-(p=c.z)*(z=j.y),p*(x=j.x)-(v=c.x)*t,v*z-F*x);p=Math.sqrt((i=c.x)*i+(r=c.y)*r+(y=c.z)*y);i=1E-9>p?new m(0,0,0):c.divSelf$N(p);r=new m((E=j.y)*(o=i.z)-(n=j.z)*(A=i.y),n*(B=i.x)-(w=j.x)*o,w*A-E*B);n=Math.sqrt((k=r.x)*k+(C=r.y)*C+(D=r.z)*D);k=1E-9>n?new m(0,
0,0):r.divSelf$N(n);a=new H([G=i.x,T=i.y,L=i.z,-(G*(M=a.x)+T*(S=a.y)+L*(K=a.z)),R=k.x,I=k.y,q=k.z,-(R*M+I*S+q*K),g=j.x,P=j.y,O=j.z,-(g*M+P*S+O*K),0,0,0,1]);e=1/Math.tan(e/2);f/=f-d;g=new H([e,0,0,0,0,e/h,0,0,0,0,f,-f*d,0,0,1,0]);this.viewMatrix=a;this.projectionMatrix=g;d=(K=g._m11)*(D=a._m11)+(O=g._m12)*(k=a._m21)+(C=g._m13)*(P=a._m31)+(n=g._m14)*(q=a._m41);h=K*(e=a._m12)+O*(G=a._m22)+C*(T=a._m32)+n*(L=a._m42);f=K*(R=a._m13)+O*(M=a._m23)+C*(I=a._m33)+n*(S=a._m43);a=K*(K=a._m14)+O*(O=a._m24)+C*(C=
a._m34)+n*(i=a._m44);n=(w=g._m21)*D+(A=g._m22)*k+(E=g._m23)*P+(B=g._m24)*q;o=(r=g._m31)*D+(y=g._m32)*k+(p=g._m33)*P+(t=g._m34)*q;q=(v=g._m41)*D+(D=g._m42)*k+(k=g._m43)*P+(g=g._m44)*q;this.matrix=new H([d,h,f,a,n,w*e+A*G+E*T+B*L,w*R+A*M+E*I+B*S,w*K+A*O+E*C+B*i,o,r*e+y*G+p*T+t*L,r*R+y*M+p*I+t*S,r*K+y*O+p*C+t*i,q,v*e+D*G+k*T+g*L,v*R+D*M+k*I+g*S,v*K+D*O+k*C+g*i])};Hb.prototype={};za.prototype=new Hb;Hb.prototype._to2DigitHex$I=function(a){a=Math.floor(a).toString(16);1===a.length&&(a="0"+a);return a};
Hb.prototype.toHexString$=function(){return this._to2DigitHex$I(this.r)+this._to2DigitHex$I(this.g)+this._to2DigitHex$I(this.b)};Hb.prototype.toString=function(){return"#"+this._to2DigitHex$I(this.r)+this._to2DigitHex$I(this.g)+this._to2DigitHex$I(this.b)};vb.prototype={};Dc.prototype=new vb;vb.isHiddenXY$ALVector$LEngine$=function(a,b){var c,e,d,f,h;c=0;for(h=a.length;c<h;c++)if(e=a[c],-0<(d=e.x)&&d<b._width+0&&-0<(f=e.y)&&f<b._height+0)return!1;return!0};var rc=vb.isHiddenXY$ALVector$LEngine$;ob.prototype=
new vb;Mb.prototype=new ob;ob.prototype.applyWorldMatrix$LMatrix$=function(a){var b,c,e,d,f,h,g,j,i;for(b=0;b<this.vertices.length;b++)c=this.vertices[b],e=a._m11*(h=c.x)+a._m12*(g=c.y)+a._m13*(j=c.z)+a._m14*(i=c.w),d=a._m21*h+a._m22*g+a._m23*j+a._m24*i,f=a._m31*h+a._m32*g+a._m33*j+a._m34*i,h=a._m41*h+a._m42*g+a._m43*j+a._m44*i,c.x=e/h,c.y=d/h,c.z=f/h,c.w=1;this.updateCenter$()};ob.prototype.applyViewMatrix$LMatrix$=function(a){var b,c,e,d,f,h,g,j,i,k,l,p;b=[];for(c=p=l=k=0;c<this.vertices.length;c++)e=
this.vertices[c],e=a._m11*(h=e.x)+a._m12*(g=e.y)+a._m13*(j=e.z)+a._m14*(i=e.w),d=a._m21*h+a._m22*g+a._m23*j+a._m24*i,f=a._m31*h+a._m32*g+a._m33*j+a._m34*i,h=a._m41*h+a._m42*g+a._m43*j+a._m44*i,e=new K(e,d,f,h),b.push(e),k+=e.x,l+=e.y,p+=e.z;a=this.vertices.length;this.vCenter=new m(k/a,l/a,p/a);this.vVertices=b};ob.prototype.isHidden$LCamera$=function(a){var b;return a.nearZ<(b=this.vCenter.z)&&b<a.farZ?!1:!0};ob.prototype.move$LVector$=function(a){var b,c;for(b=0;b<this.vertices.length;b++)c=this.vertices[b],
c.x+=a.x,c.y+=a.y,c.z+=a.z;this.updateCenter$()};ob.prototype.updateCenter$=function(){var a,b,c,e,d;for(a=d=e=c=0;a<this.vertices.length;a++)b=this.vertices[a],c+=b.x,e+=b.y,d+=b.z;a=this.vertices.length;this.center=new m(c/a,e/a,d/a)};ob.prototype.toString=function(){var a,b;a="[";for(b=0;b<this.vertices.length;b++)a+=this.vertices[b].toString()+",";return a+"]"};ob.prototype.draw$LEngine$=function(a){var b,c,e,d,f,h,g,j,i,k,l,p,r,n,o;b=a.context;c=this.vertices.length;e=this.vVertices;d=this._color;
this._enabledLighting&&(f=this.vCenter,g=e[0],i=g.x-f.x,o=g.y-f.y,l=g.z-f.z,g=e[1],g=new m(g.x-f.x,g.y-f.y,g.z-f.z),k=(n=g.y)*l-(r=g.z)*o,l=r*i-(r=g.x)*l,k=g.x=k,l=g.y=l,i=g.z=r*o-n*i,i=Math.sqrt(k*k+l*l+i*i),g=1E-9>i?new m(0,0,0):g.divSelf$N(i),i=Math.sqrt((h=f.x)*h+(j=f.y)*j+(p=f.z)*p),f=1E-9>i?new m(0,0,0):new m(f.x/i,f.y/i,f.z/i),j=g.x*f.x+g.y*f.y+g.z*f.z,f=(0.5599999999999999*j+0.5)*d.r,h=(0.5599999999999999*j+0.5)*d.g,d=(0.5599999999999999*j+0.5)*d.b,d=new za(255<=f?255:f,255<=h?255:h,255<=
d?255:d));for(f=0;f<c;f++)h=e[f],i=a.camera.projectionMatrix,j=i._m11*(o=h.x)+i._m12*(n=h.y)+i._m13*(r=h.z)+i._m14*(k=h.w),p=i._m21*o+i._m22*n+i._m23*r+i._m24*k,g=i._m31*o+i._m32*n+i._m33*r+i._m34*k,i=i._m41*o+i._m42*n+i._m43*r+i._m44*k,h.x=j/i,h.y=p/i,h.z=g/i,h.w=1;for(f=0;f<c;f++)h=e[f],i=a.screenMatrix,j=i._m11*(o=h.x)+i._m12*(n=h.y)+i._m13*(r=h.z)+i._m14*(k=h.w),p=i._m21*o+i._m22*n+i._m23*r+i._m24*k,g=i._m31*o+i._m32*n+i._m33*r+i._m34*k,i=i._m41*o+i._m42*n+i._m43*r+i._m44*k,h.x=j/i,h.y=p/i,h.z=
g/i,h.w=1;if(rc(e,a))return!1;f=0;for(j=e.length;f<j;f++)if(a=(f+1)%j,h=(f+2)%j,0>Xc(e[a].x-e[f].x,e[a].y-e[f].y,e[h].x-e[f].x,e[h].y-e[f].y))return!1;d="#"+(d._to2DigitHex$I(d.r)+d._to2DigitHex$I(d.g)+d._to2DigitHex$I(d.b));b.strokeStyle=d;for(f=0;f<c;f++)b.beginPath(),b.moveTo(e[f].x,e[f].y),b.lineTo(e[(f+1)%c].x,e[(f+1)%c].y),b.stroke();b.fillStyle=d;b.beginPath();for(f=0;f<c;f++)d=e[f].x,a=e[f].y,b.lineTo(d,a);b.closePath();b.fill();return!0};tb.prototype=new vb;Ec.prototype=new tb;mc.prototype=
new tb;tb.prototype.applyWorldMatrix$LMatrix$=function(a){var b,c,e,d,f,h,g,j;b=this.center;c=a._m11*(f=b.x)+a._m12*(h=b.y)+a._m13*(g=b.z)+a._m14*(j=b.w);e=a._m21*f+a._m22*h+a._m23*g+a._m24*j;d=a._m31*f+a._m32*h+a._m33*g+a._m34*j;a=a._m41*f+a._m42*h+a._m43*g+a._m44*j;b.x=c/a;b.y=e/a;b.z=d/a;b.w=1};tb.prototype.applyViewMatrix$LMatrix$=function(a){var b,c,e,d,f;b=this.center;b=a._m11*(c=b.x)+a._m12*(e=b.y)+a._m13*(d=b.z)+a._m14*(f=b.w);this.vCenter=new K(b,a._m21*c+a._m22*e+a._m23*d+a._m24*f,a._m31*
c+a._m32*e+a._m33*d+a._m34*f,a._m41*c+a._m42*e+a._m43*d+a._m44*f)};tb.prototype.isHidden$LCamera$=function(a){return this._ignoringZHidden?!1:a.nearZ<this.vCenter.z&&this.vCenter.z<a.farZ?!1:!0};tb.prototype.draw$LEngine$=function(a){this.polygons.forEach$F$LPolygon$V$(function(b){b.isHidden$LCamera$(a.camera)||b.draw$LEngine$(a)});return!0};wb.prototype=new ob;nc.prototype=new wb;ac.prototype=new wb;wb.prototype.applyWorldMatrix$LMatrix$=function(a){var b,c,e,d,f,h,g,j,i;for(b=0;b<this.vertices.length;b++)c=
this.vertices[b],e=a._m11*(h=c.x)+a._m12*(g=c.y)+a._m13*(j=c.z)+a._m14*(i=c.w),d=a._m21*h+a._m22*g+a._m23*j+a._m24*i,f=a._m31*h+a._m32*g+a._m33*j+a._m34*i,h=a._m41*h+a._m42*g+a._m43*j+a._m44*i,c.x=e/h,c.y=d/h,c.z=f/h,c.w=1;b=this.center;c=a._m11*(f=b.x)+a._m12*(h=b.y)+a._m13*(g=b.z)+a._m14*(j=b.w);e=a._m21*f+a._m22*h+a._m23*g+a._m24*j;d=a._m31*f+a._m32*h+a._m33*g+a._m34*j;a=a._m41*f+a._m42*h+a._m43*g+a._m44*j;b.x=c/a;b.y=e/a;b.z=d/a;b.w=1};wb.prototype.applyViewMatrix$LMatrix$=function(a){var b,c,
e,d,f;b=[];for(c=0;c<this.vertices.length;c++)b.push(this.vertices[c].transform$LMatrix$(a));this.vVertices=b;e=this.center;e=a._m11*(b=e.x)+a._m12*(c=e.y)+a._m13*(d=e.z)+a._m14*(f=e.w);this.vCenter=new K(e,a._m21*b+a._m22*c+a._m23*d+a._m24*f,a._m31*b+a._m32*c+a._m33*d+a._m34*f,a._m41*b+a._m42*c+a._m43*d+a._m44*f)};wb.prototype.isHidden$LCamera$=function(a){var b;return a.nearZ<(b=this.vCenter.z)&&b<a.farZ?!1:!0};wb.prototype.draw$LEngine$=function(a){var b=this,c,e,d,f,h,g,j,i,k,l,p,r,n,o,q,s,u,
t,v,z,F,x,y,w,A,E,B,C,D,G,T,L,R,M,O,S,H,P,J,Q,Z,za,Ia,N,Ra,Sa,Ta,$a,rb,Ua,Va,Wa,Xa,Ya,Za,Ja,Ka,ab,bb,Ma,cb,Na,db,Oa,ka,la,Pa,eb,Qa,Da,La,Ea,Fa,ea,fa,Ga,Ha,pa,qa,ra,sa,ta,ua,va,$,aa,wa,U,ma,na,xa,oa,ya,ba,da,ga,ha,ia,ja,X,Y,Aa,Ba,Ca,fb,gb,hb,ib,jb,nb,ob,pb,qb,vb,sb,tb;if(!I.isLoadedImage[this._src])return!1;c=a.context;e=($a=this.vertices)[3];d=$a[0];f=$a[1];h=$a[2];p=a.screenMatrix;T=(rb=a.camera).projectionMatrix;L=rb.viewMatrix;R=(Ua=T._m11)*(Ya=L._m11)+(Va=T._m12)*(Za=L._m21)+(Wa=T._m13)*(Ja=L._m31)+
(Xa=T._m14)*(Ka=L._m41);M=Ua*(bb=L._m12)+Va*(cb=L._m22)+Wa*(db=L._m32)+Xa*(ka=L._m42);O=Ua*(la=L._m13)+Va*(Pa=L._m23)+Wa*(eb=L._m33)+Xa*(Qa=L._m43);S=Ua*(Da=L._m14)+Va*(La=L._m24)+Wa*(Ea=L._m34)+Xa*(Fa=L._m44);H=(ab=T._m21)*Ya+(Ma=T._m22)*Za+(Na=T._m23)*Ja+(Oa=T._m24)*Ka;P=ab*bb+Ma*cb+Na*db+Oa*ka;J=ab*la+Ma*Pa+Na*eb+Oa*Qa;Q=ab*Da+Ma*La+Na*Ea+Oa*Fa;Z=(ea=T._m31)*Ya+(fa=T._m32)*Za+(Ga=T._m33)*Ja+(Ha=T._m34)*Ka;za=ea*bb+fa*cb+Ga*db+Ha*ka;Ia=ea*la+fa*Pa+Ga*eb+Ha*Qa;N=ea*Da+fa*La+Ga*Ea+Ha*Fa;Ra=(pa=T._m41)*
Ya+(qa=T._m42)*Za+(ra=T._m43)*Ja+(sa=T._m44)*Ka;Sa=pa*bb+qa*cb+ra*db+sa*ka;Ta=pa*la+qa*Pa+ra*eb+sa*Qa;tb=pa*Da+qa*La+ra*Ea+sa*Fa;r=(ta=p._m11)*R+(ua=p._m12)*H+(va=p._m13)*Z+($=p._m14)*Ra;n=ta*M+ua*P+va*za+$*Sa;o=ta*O+ua*J+va*Ia+$*Ta;q=ta*S+ua*Q+va*N+$*tb;s=(aa=p._m21)*R+(wa=p._m22)*H+(U=p._m23)*Z+(ma=p._m24)*Ra;u=aa*M+wa*P+U*za+ma*Sa;t=aa*O+wa*J+U*Ia+ma*Ta;v=aa*S+wa*Q+U*N+ma*tb;z=(na=p._m31)*R+(xa=p._m32)*H+(oa=p._m33)*Z+(ya=p._m34)*Ra;F=na*M+xa*P+oa*za+ya*Sa;x=na*O+xa*J+oa*Ia+ya*Ta;y=na*S+xa*Q+oa*
N+ya*tb;w=(ba=p._m41)*R+(da=p._m42)*H+(ga=p._m43)*Z+(ha=p._m44)*Ra;A=ba*M+da*P+ga*za+ha*Sa;E=ba*O+da*J+ga*Ia+ha*Ta;sb=ba*S+da*Q+ga*N+ha*tb;B=r*(ia=e.x)+n*(ja=e.y)+o*(X=e.z)+q*(Y=e.w);g=new K(B,s*ia+u*ja+t*X+v*Y,z*ia+F*ja+x*X+y*Y,w*ia+A*ja+E*X+sb*Y);C=r*(Aa=d.x)+n*(Ba=d.y)+o*(Ca=d.z)+q*(fb=d.w);j=new K(C,s*Aa+u*Ba+t*Ca+v*fb,z*Aa+F*Ba+x*Ca+y*fb,w*Aa+A*Ba+E*Ca+sb*fb);D=r*(gb=f.x)+n*(hb=f.y)+o*(ib=f.z)+q*(jb=f.w);i=new K(D,s*gb+u*hb+t*ib+v*jb,z*gb+F*hb+x*ib+y*jb,w*gb+A*hb+E*ib+sb*jb);G=r*(nb=h.x)+n*(ob=
h.y)+o*(pb=h.z)+q*(qb=h.w);k=new K(G,s*nb+u*ob+t*pb+v*qb,z*nb+F*ob+x*pb+y*qb,w*nb+A*ob+E*pb+sb*qb);if(rc([g,j,i,k],a))return!1;l=function(a,d,e,f,g,h,i,j,k,p,B,C,D,G){var I,O,T,P,V,L,M,R,S,H,N,J,Q,ca,W,Z,ba,da,ga,ha,ia,ja,X,Y,$,aa,U,ma,na,oa,pa,qa,ra,sa,ta,ua,va,wa,xa,ya,za,Aa,Ba,Ca,Da,Ea,Fa,ea,fa,Ga,Ha,kb,Ia,La,Ma,Na,Oa,ka,la,Pa,Qa,Ua,Va,Wa,Xa,Ya,Za,Ja,Ka,Ra,Sa,Ta,$a,ab,bb,cb,db,eb,fb,gb,hb,ib,jb,lb,mb,nb,ob,pb,qb,rb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Ib,Hb,Jb;I=function(a,b){return Math.sqrt(a*
a+b*b)};O=I(j.x-i.x,j.y-i.y);T=I(k.x-h.x,k.y-h.y);P=I(h.x-i.x,h.y-i.y);V=I(k.x-j.x,k.y-j.y);L=O/T;M=V/P;1>L&&(L=1/L);1>M&&(M=1/M);R=1.01<L;S=1.01<M;p<=b._minDiv||p<=b._maxDiv&&R&&S?(X=new m(d.x+g.x,d.y+g.y,d.z+g.z),X.x/=2,X.y/=2,X.z/=2,H=X,Y=new m(e.x+f.x,e.y+f.y,e.z+f.z),Y.x/=2,Y.y/=2,Y.z/=2,N=Y,$=new m(d.x+e.x,d.y+e.y,d.z+e.z),$.x/=2,$.y/=2,$.z/=2,J=$,aa=new m(g.x+f.x,g.y+f.y,g.z+f.z),aa.x/=2,aa.y/=2,aa.z/=2,Q=aa,U=new m(d.x+f.x,d.y+f.y,d.z+f.z),U.x/=2,U.y/=2,U.z/=2,ma=r*(Ja=H.x)+n*(Ka=H.y)+o*(Ra=
H.z)+q*(Sa=H.w),na=s*Ja+u*Ka+t*Ra+v*Sa,oa=z*Ja+F*Ka+x*Ra+y*Sa,pa=w*Ja+A*Ka+E*Ra+sb*Sa,ca=new K(ma,na,oa,pa),qa=r*(Ta=N.x)+n*($a=N.y)+o*(ab=N.z)+q*(bb=N.w),ra=s*Ta+u*$a+t*ab+v*bb,sa=z*Ta+F*$a+x*ab+y*bb,ta=w*Ta+A*$a+E*ab+sb*bb,W=new K(qa,ra,sa,ta),ua=r*(cb=J.x)+n*(db=J.y)+o*(eb=J.z)+q*(fb=J.w),va=s*cb+u*db+t*eb+v*fb,wa=z*cb+F*db+x*eb+y*fb,xa=w*cb+A*db+E*eb+sb*fb,Z=new K(ua,va,wa,xa),ya=r*(gb=Q.x)+n*(hb=Q.y)+o*(ib=Q.z)+q*(jb=Q.w),za=s*gb+u*hb+t*ib+v*jb,Aa=z*gb+F*hb+x*ib+y*jb,Ba=w*gb+A*hb+E*ib+sb*jb,
ba=new K(ya,za,Aa,Ba),Ca=r*(lb=U.x)+n*(mb=U.y)+o*(nb=U.z)+q*(ob=U.w),Da=s*lb+u*mb+t*nb+v*ob,Ea=z*lb+F*mb+x*nb+y*ob,Fa=w*lb+A*mb+E*nb+sb*ob,da=new K(Ca,Da,Ea,Fa),l(a,d,J,U,H,h,Z,da,ca,p+1,B,C,D/2,G/2),l(a,J,e,N,U,Z,i,W,da,p+1,B,C+G/2,D/2,G/2),l(a,H,U,Q,g,ca,da,ba,k,p+1,B+D/2,C,D/2,G/2),l(a,U,N,f,Q,da,W,j,ba,p+1,B+D/2,C+G/2,D/2,G/2)):p<=b._maxVerticalDiv&&S?(ea=new m(d.x+g.x,d.y+g.y,d.z+g.z),ea.x/=2,ea.y/=2,ea.z/=2,H=ea,fa=new m(e.x+f.x,e.y+f.y,e.z+f.z),fa.x/=2,fa.y/=2,fa.z/=2,N=fa,Ga=r*(pb=H.x)+n*
(qb=H.y)+o*(rb=H.z)+q*(tb=H.w),Ha=s*pb+u*qb+t*rb+v*tb,kb=z*pb+F*qb+x*rb+y*tb,Ia=w*pb+A*qb+E*rb+sb*tb,ca=new K(Ga,Ha,kb,Ia),La=r*(ub=N.x)+n*(vb=N.y)+o*(wb=N.z)+q*(xb=N.w),Ma=s*ub+u*vb+t*wb+v*xb,Na=z*ub+F*vb+x*wb+y*xb,Oa=w*ub+A*vb+E*wb+sb*xb,W=new K(La,Ma,Na,Oa),l(a,d,e,N,H,h,i,W,ca,p+1,B,C,D/2,G),l(a,H,N,f,g,ca,W,j,k,p+1,B+D/2,C,D/2,G)):p<=b._maxHorizontalDiv&&R?(ka=new m(d.x+e.x,d.y+e.y,d.z+e.z),ka.x/=2,ka.y/=2,ka.z/=2,J=ka,la=new m(g.x+f.x,g.y+f.y,g.z+f.z),la.x/=2,la.y/=2,la.z/=2,Q=la,Pa=r*(yb=J.x)+
n*(zb=J.y)+o*(Ab=J.z)+q*(Bb=J.w),Qa=s*yb+u*zb+t*Ab+v*Bb,Ua=z*yb+F*zb+x*Ab+y*Bb,Va=w*yb+A*zb+E*Ab+sb*Bb,Z=new K(Pa,Qa,Ua,Va),Wa=r*(Cb=Q.x)+n*(Db=Q.y)+o*(Eb=Q.z)+q*(Fb=Q.w),Xa=s*Cb+u*Db+t*Eb+v*Fb,Ya=z*Cb+F*Db+x*Eb+y*Fb,Za=w*Cb+A*Db+E*Eb+sb*Fb,ba=new K(Wa,Xa,Ya,Za),l(a,d,J,Q,g,h,Z,ba,k,p+1,B,C,D,G/2),l(a,J,e,f,Q,Z,i,j,ba,p+1,B,C+G/2,D,G/2)):(ga=((Ib=k.x)-(Hb=h.x))/D,ha=((Jb=i.y)-(Gb=h.y))/G,ia=(k.y-Gb)/(Ib-Hb),ja=(i.x-Hb)/(Jb-Gb),c.transform(1,0,0,1,Hb,Gb),c.transform(1,ia,ja,1,0,0),c.transform(ga,0,
0,ha,0,0),c.drawImage(a,~~B,~~C,~~D,~~G,0,0,Math.ceil(D),Math.ceil(G)),c.setTransform(1,0,0,1,0,0))};l(vb=this._image,e,d,f,h,g,j,i,k,1,0,0,vb.width,vb.height);return!0};Db.prototype=new vb;oc.prototype=new Db;Db.prototype.applyWorldMatrix$LMatrix$=function(a){var b,c,e,d,f,h,g,j;b=this.center;c=a._m11*(f=b.x)+a._m12*(h=b.y)+a._m13*(g=b.z)+a._m14*(j=b.w);e=a._m21*f+a._m22*h+a._m23*g+a._m24*j;d=a._m31*f+a._m32*h+a._m33*g+a._m34*j;a=a._m41*f+a._m42*h+a._m43*g+a._m44*j;b.x=c/a;b.y=e/a;b.z=d/a;b.w=1};
Db.prototype.applyViewMatrix$LMatrix$=function(a){var b,c,e,d,f;b=this.center;b=a._m11*(c=b.x)+a._m12*(e=b.y)+a._m13*(d=b.z)+a._m14*(f=b.w);this.vCenter=new K(b,a._m21*c+a._m22*e+a._m23*d+a._m24*f,a._m31*c+a._m32*e+a._m33*d+a._m34*f,a._m41*c+a._m42*e+a._m43*d+a._m44*f)};Db.prototype.isHidden$LCamera$=function(a){var b;return a.nearZ<(b=this.vCenter.z)&&b<a.farZ?!1:!0};Db.prototype.draw$LEngine$=function(a){var b,c,e,d,f,h,g,j,i,k,l,m,r,n,o,q,s,u,t,v,z,B,x,y,w,A,E,C,D,G,H,J,L;if(!I.isLoadedImage[this._src])return!1;
b=a.context;h=a.screenMatrix;g=a.camera.projectionMatrix;d=(l=h._m11)*(v=g._m11)+(k=h._m12)*(z=g._m21)+(i=h._m13)*(B=g._m31)+(j=h._m14)*(q=g._m41);e=l*(s=g._m12)+k*(x=g._m22)+i*(y=g._m32)+j*(w=g._m42);f=l*(u=g._m13)+k*(A=g._m23)+i*(E=g._m33)+j*(C=g._m43);g=l*(c=g._m14)+k*(t=g._m24)+i*(D=g._m34)+j*(G=g._m44);j=(l=h._m21)*v+(m=h._m22)*z+(r=h._m23)*B+(n=h._m24)*q;i=l*s+m*x+r*y+n*w;k=l*u+m*A+r*E+n*C;l=l*c+m*t+r*D+n*G;m=(o=h._m31)*v+(H=h._m32)*z+(J=h._m33)*B+(L=h._m34)*q;r=o*s+H*x+J*y+L*w;n=o*u+H*A+J*
E+L*C;o=o*c+H*t+J*D+L*G;q=(H=h._m41)*v+(v=h._m42)*z+(z=h._m43)*B+(h=h._m44)*q;s=H*s+v*x+z*y+h*w;u=H*u+v*A+z*E+h*C;A=H*c+v*t+z*D+h*G;c=this.vCenter;E=this._width/2;C=this._height/2;E=c.x-E;C=c.y-C;x=c.z-0;t=this.vCenter;t=d*(c=t.x)+e*(y=t.y)+f*(w=t.z)+g*(D=t.w);c=new K(t,j*c+i*y+k*w+l*D,m*c+r*y+n*w+o*D,q*c+s*y+u*w+A*D);e=new K(d*E+e*C+f*x+1*g,j*E+i*C+k*x+1*l,m*E+r*C+n*x+1*o,q*E+s*C+u*x+1*A);d=e.x-c.x;e=e.y-c.y;if(rc([c],a))return!1;a=2*(d/(f=this._image).width);f=2*(e/f.height);b.setTransform(a,0,
0,f,0,0);b.drawImage(this._image,~~((c.x-d)/a),~~((c.y-e)/f));b.setTransform(1,0,0,1,0,0);return!0};Ra.prototype={};(function(){this.tail=this.head=null;this.length=0}).prototype=new Ra;Lb.prototype=new Ra;Ra.prototype.prepend$LVector$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.tail=this.head=a:(a._next=b=this.head,this.head=b._prev=a);this.length++;return this};Ra.prototype.append$LVector$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.head=
a:(a._prev=b=this.tail,b._next=a);this.tail=a;this.length++;return this};Ra.prototype.remove$LNode$Vector$E$=function(a){a._prev?a._prev._next=a._next:this.head=a._next;a._next?a._next._prev=a._prev:this.tail=a._prev;return a.value};Ra.prototype.removeFirst$=function(){var a,b;a=this.head;this.head=b=a._next;null!=b&&(a._next._prev=null);this.length--;return a.value};Ra.prototype.removeLast$=function(){var a,b;a=this.tail;this.tail=b=a._prev;null!=b&&(a._prev._next=null);this.length--;return a.value};
Ra.prototype.insertAfter$LNode$Vector$E$LVector$=function(a,b){var c,e;c={value:b,_prev:null,_next:null};null==a._next?(c._prev=a,this.tail=a._next=c):(c._next=e=a._next,c._prev=a,e._prev=c,a._next=c);this.length++;return this};Ra.prototype.insertBefore$LNode$Vector$E$LVector$=function(a,b){var c,e;c={value:b,_prev:null,_next:null};null==a._prev?(c._next=a,this.head=a._prev=c):(c._next=a,c._prev=e=a._prev,e._next=c,a._prev=c);this.length++;return this};Ra.prototype.forEach$F$LVector$V$=function(a){var b;
for(b=this.head;b;b=b._next)a(b.value)};Ra.prototype.toString=function(){var a,b;a="list : [";for(b=this.head;null!=b;b=b._next)a+=" "+b.value.toString()+",";return a+"]"};bc.prototype={};(function(a){this.value=a;this._next=this._prev=null}).prototype=new bc;bc.prev$LNode$Vector$E$=function(a){return a._prev};bc.next$LNode$Vector$E$=function(a){return a._next};Sa.prototype={};lc.prototype=new Sa;(function(a){var b,c;this.tail=this.head=null;this.length=0;b=a.length;for(c=0;c<b;c++)this.prepend$LMatrix$(a.pop())}).prototype=
new Sa;Sa.prototype.prepend$LMatrix$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.tail=this.head=a:(a._next=b=this.head,this.head=b._prev=a);this.length++;return this};Sa.prototype.append$LMatrix$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.head=a:(a._prev=b=this.tail,b._next=a);this.tail=a;this.length++;return this};Sa.prototype.remove$LNode$Matrix$E$=function(a){a._prev?a._prev._next=a._next:this.head=a._next;a._next?a._next._prev=a._prev:
this.tail=a._prev;return a.value};Sa.prototype.removeFirst$=function(){var a,b;a=this.head;this.head=b=a._next;null!=b&&(a._next._prev=null);this.length--;return a.value};Sa.prototype.removeLast$=function(){var a,b;a=this.tail;this.tail=b=a._prev;null!=b&&(a._prev._next=null);this.length--;return a.value};Sa.prototype.insertAfter$LNode$Matrix$E$LMatrix$=function(a,b){var c,e;c={value:b,_prev:null,_next:null};null==a._next?(c._prev=a,this.tail=a._next=c):(c._next=e=a._next,c._prev=a,e._prev=c,a._next=
c);this.length++;return this};Sa.prototype.insertBefore$LNode$Matrix$E$LMatrix$=function(a,b){var c,e;c={value:b,_prev:null,_next:null};null==a._prev?(c._next=a,this.head=a._prev=c):(c._next=a,c._prev=e=a._prev,e._next=c,a._prev=c);this.length++;return this};Sa.prototype.forEach$F$LMatrix$V$=function(a){var b;for(b=this.head;b;b=b._next)a(b.value)};Sa.prototype.toString=function(){var a,b;a="list : [";for(b=this.head;null!=b;b=b._next)a+=" "+b.value.toString()+",";return a+"]"};cc.prototype={};(function(a){this.value=
a;this._next=this._prev=null}).prototype=new cc;cc.prev$LNode$Matrix$E$=function(a){return a._prev};cc.next$LNode$Matrix$E$=function(a){return a._next};Ta.prototype={};nb.prototype=new Ta;(function(a){var b,c;this.tail=this.head=null;this.length=0;b=a.length;for(c=0;c<b;c++)this.prepend$LRenderable$(a.pop())}).prototype=new Ta;Ta.prototype.prepend$LRenderable$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.tail=this.head=a:(a._next=b=this.head,this.head=b._prev=a);this.length++;
return this};Ta.prototype.append$LRenderable$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.head=a:(a._prev=b=this.tail,b._next=a);this.tail=a;this.length++;return this};Ta.prototype.remove$LNode$Renderable$E$=function(a){a._prev?a._prev._next=a._next:this.head=a._next;a._next?a._next._prev=a._prev:this.tail=a._prev;return a.value};Ta.prototype.removeFirst$=function(){var a,b;a=this.head;this.head=b=a._next;null!=b&&(a._next._prev=null);this.length--;return a.value};Ta.prototype.removeLast$=
function(){var a,b;a=this.tail;this.tail=b=a._prev;null!=b&&(a._prev._next=null);this.length--;return a.value};Ta.prototype.insertAfter$LNode$Renderable$E$LRenderable$=function(a,b){var c,e;c={value:b,_prev:null,_next:null};null==a._next?(c._prev=a,this.tail=a._next=c):(c._next=e=a._next,c._prev=a,e._prev=c,a._next=c);this.length++;return this};Ta.prototype.insertBefore$LNode$Renderable$E$LRenderable$=function(a,b){var c,e;c={value:b,_prev:null,_next:null};null==a._prev?(c._next=a,this.head=a._prev=
c):(c._next=a,c._prev=e=a._prev,e._next=c,a._prev=c);this.length++;return this};Ta.prototype.forEach$F$LRenderable$V$=function(a){var b;for(b=this.head;b;b=b._next)a(b.value)};Ta.prototype.toString=function(){var a,b;a="list : [";for(b=this.head;null!=b;b=b._next)a+=" "+b.value.toString()+",";return a+"]"};dc.prototype={};(function(a){this.value=a;this._next=this._prev=null}).prototype=new dc;dc.prev$LNode$Renderable$E$=function(a){return a._prev};dc.next$LNode$Renderable$E$=function(a){return a._next};
$a.prototype={};Eb.prototype=new $a;(function(a){var b,c;this.tail=this.head=null;this.length=0;b=a.length;for(c=0;c<b;c++)this.prepend$LPolygon$(a.pop())}).prototype=new $a;$a.prototype.prepend$LPolygon$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.tail=this.head=a:(a._next=b=this.head,this.head=b._prev=a);this.length++;return this};$a.prototype.append$LPolygon$=function(a){var b,a={value:a,_prev:null,_next:null};0===this.length?this.head=a:(a._prev=b=this.tail,b._next=
a);this.tail=a;this.length++;return this};$a.prototype.remove$LNode$Polygon$E$=function(a){a._prev?a._prev._next=a._next:this.head=a._next;a._next?a._next._prev=a._prev:this.tail=a._prev;return a.value};$a.prototype.removeFirst$=function(){var a,b;a=this.head;this.head=b=a._next;null!=b&&(a._next._prev=null);this.length--;return a.value};$a.prototype.removeLast$=function(){var a,b;a=this.tail;this.tail=b=a._prev;null!=b&&(a._prev._next=null);this.length--;return a.value};$a.prototype.insertAfter$LNode$Polygon$E$LPolygon$=
function(a,b){var c,e;c={value:b,_prev:null,_next:null};null==a._next?(c._prev=a,this.tail=a._next=c):(c._next=e=a._next,c._prev=a,e._prev=c,a._next=c);this.length++;return this};$a.prototype.insertBefore$LNode$Polygon$E$LPolygon$=function(a,b){var c,e;c={value:b,_prev:null,_next:null};null==a._prev?(c._next=a,this.head=a._prev=c):(c._next=a,c._prev=e=a._prev,e._next=c,a._prev=c);this.length++;return this};$a.prototype.forEach$F$LPolygon$V$=function(a){var b;for(b=this.head;b;b=b._next)a(b.value)};
$a.prototype.toString=function(){var a,b;a="list : [";for(b=this.head;null!=b;b=b._next)a+=" "+b.value.toString()+",";return a+"]"};ec.prototype={};(function(a){this.value=a;this._next=this._prev=null}).prototype=new ec;ec.prev$LNode$Polygon$E$=function(a){return a._prev};ec.next$LNode$Polygon$E$=function(a){return a._next};Q.prototype={};Fc.prototype=new Q;Q.id$S=function(a){a=Q.document.getElementById(a);return a instanceof HTMLElement?a:null};Q.getElementById$S=function(a){a=Q.document.getElementById(a);
return a instanceof HTMLElement?a:null};Q.createElement$S=function(a){return Q.document.createElement(a)};G.prototype={};Gc.prototype=new G;G.setTimeout$F$V$N=function(a,b){return B.global.setTimeout(a,b)};G.clearTimeout$LTimerHandle$=function(a){B.global.clearTimeout(a)};var Yc=G.clearTimeout$LTimerHandle$;G.setInterval$F$V$N=function(a,b){return B.global.setInterval(a,b)};G.clearInterval$LTimerHandle$=function(a){B.global.clearInterval(a)};G.requestAnimationFrame$F$NV$=function(a){return G._requestAnimationFrame(a)};
G.cancelAnimationFrame$LTimerHandle$=function(a){G._cancelAnimationFrame(a)};G.useNativeRAF$B=function(a){G._requestAnimationFrame=Oc(a);G._cancelAnimationFrame=Pc(a)};G._getRequestAnimationFrameImpl$B=function(a){var b;if(a){if(B.global.requestAnimationFrame)return function(a){return B.global.requestAnimationFrame(a)};if(B.global.webkitRequestAnimationFrame)return function(a){return B.global.webkitRequestAnimationFrame(a)};if(B.global.mozRequestAnimationFrame)return function(a){return B.global.mozRequestAnimationFrame(a)};
if(B.global.oRequestAnimationFrame)return function(a){return B.global.oRequestAnimationFrame(a)};if(B.global.msRequestAnimationFrame)return function(a){return B.global.msRequestAnimationFrame(a)}}b=0;return function(a){var e,d,f;e=Date.now();f=16-(e-b);d=0>=f?0:f;b=e+d;return B.global.setTimeout(function(){a(e+d)},d)}};var Oc=G._getRequestAnimationFrameImpl$B;G._getCancelAnimationFrameImpl$B=function(a){if(a){if(B.global.cancelAnimationFrame)return function(a){B.global.cancelAnimationFrame(a)};if(B.global.webkitCancelAnimationFrame)return function(a){B.global.webkitCancelAnimationFrame(a)};
if(B.global.mozCancelAnimationFrame)return function(a){B.global.mozCancelAnimationFrame(a)};if(B.global.oCancelAnimationFrame)return function(a){B.global.oCancelAnimationFrame(a)};if(B.global.msCancelAnimationFrame)return function(a){B.global.msCancelAnimationFrame(a)}}return Yc};var Pc=G._getCancelAnimationFrameImpl$B;pc.prototype={};Hc.prototype=new pc;Nb.prototype={};Ic.prototype=new Nb;Nb.cross$NNNN=function(a,b,c,e){return a*e-c*b};var Xc=Nb.cross$NNNN;Ia.prototype={};Jc.prototype=new Ia;Ia._currentMsec$LStopwatch$=
function(){return Date.now()};Ia.start$LStopwatch$=function(a){if(null!=a._startedMsec){debugger;throw Error("[jsx/util.jsx:39] assertion failure");}a._startedMsec=a._lastLapMsec=Date.now()};var Nc=Ia.start$LStopwatch$;Ia.stop$LStopwatch$=function(a){if(null==a._startedMsec){debugger;throw Error("[jsx/util.jsx:45] assertion failure");}a._elapsedMsec+=Date.now()-a._startedMsec;a._startedMsec=null;a._lastLapMsec=null};Ia.isStarted$LStopwatch$=function(a){return null!=a._startedMsec};Ia.isStopped$LStopwatch$=
function(a){return null==a._startedMsec};var Zc=Ia.isStopped$LStopwatch$;Ia.lap$LStopwatch$=function(a){var b,c;if(null==a._lastLapMsec){debugger;throw Error("[jsx/util.jsx:65] assertion failure");}b=Date.now();c=b-a._lastLapMsec;a._lastLapMsec=b;return c};var $c=Ia.lap$LStopwatch$;Ia.getElapsedMsec$LStopwatch$=function(a){return a._elapsedMsec};xb.prototype={};Kc.prototype=new xb;Lc.prototype=new xb;xb.start$LFpsManager$=function(a){Nc(a._stopwatch)};xb.lastLap$LFpsManager$=function(a){return a._lastMsec};
xb.update$LFpsManager$=function(a){var b,c,e;if(Zc(a._stopwatch)){debugger;throw Error("[jsx/util.jsx:126] assertion failure");}b=$c(a._stopwatch);a._lastMsec=b;1>a._recentlyMsecLog.length?a._recentlyMsecLog.push(b):(a._recentlyMsecLog.push(b),a._recentlyMsecLog.shift());b=a._recentlyMsecLog.length;for(e=c=0;e<b;e++)c+=a._recentlyMsecLog[e];b/=c/1E3;null!=a._fpsElement&&a._enabledHtmlLog?a._fpsElement.innerHTML=b.toFixed(1)+"fps":a._enabledConsoleLog&&console.log(b.toFixed(1)+"fps")};var Wc=xb.update$LFpsManager$;
B.prototype={};Mc.prototype=new B;yb(I,"images",function(){return{}});yb(I,"imageDatas",function(){return{}});yb(I,"isLoadedImage",function(){return{}});yb(Q,"window",function(){return B.global.window});yb(Q,"document",function(){return B.global.document});yb(G,"_requestAnimationFrame",function(){return Oc(!0)});yb(G,"_cancelAnimationFrame",function(){return Pc(!0)});B.global=function(){return this}();var Rc={"jsx/demo2.jsx":{Util3D:pb,Util3D$:sc,Player:rb,Player$:tc,BlueBall:O,BlueBall$:hc,_Main:$b,
_Main$:yc},"jsx/vector.jsx":{Vector:D,Vector$NNN:m,Vector$NNNN:K,Vector$LVector$:zc},"jsx/matrix.jsx":{Matrix:J,Matrix$:Cb,Matrix$AN:H},"jsx/quaternion.jsx":{Quaternion:Z,Quaternion$NLVector$:Ac,Quaternion$LVector$:Bc,Quaternion$NNNN:zb},"jsx/engine.jsx":{Engine:I,Engine$S:ic,Context3D:C,Context3D$LCamera$:Cc,Camera:Ib,Camera$LVector$LVector$LVector$NNNN:kc,Color:Hb,Color$III:za,Renderable:vb,Renderable$:Dc,Polygon:ob,Polygon$ALVector$LColor$:Mb,PolygonGroup:tb,PolygonGroup$LList$Polygon$E$LVector$:Ec,
PolygonGroup$LList$Polygon$E$LVector$B:mc,SmoothTexture:wb,SmoothTexture$ALVector$S:nc,SmoothTexture$ALVector$SIIII:ac,Billboard:Db,Billboard$LVector$NNS:oc},"system:lib/js/js/web.jsx":{dom:Q,dom$:Fc},"system:lib/js/timer.jsx":{Timer:G,Timer$:Gc,TimerHandle:pc,TimerHandle$:Hc},"jsx/util.jsx":{Math2D:Nb,Math2D$:Ic,Stopwatch:Ia,Stopwatch$:Jc,FpsManager:xb,FpsManager$:Kc,FpsManager$S:Lc},"system:lib/js/js.jsx":{js:B,js$:Mc}};JSX.runMain=function(a,b){var c=JSX.require(a);if(!c._Main)throw Error("entry point _Main not found in "+
a);if(!c._Main.main$AS)throw Error("entry point _Main.main(:string[]):void not found in "+a);c._Main.main$AS(b)};JSX.runTests=function(a,b){var c=JSX.require(a)._Test$;if(c){if(0===b.length){var e=c.prototype,d;for(d in e)e[d]instanceof Function&&/^test.*[$]$/.test(d)&&b.push(d)}var f=new c;null!=f.beforeClass$AS&&f.beforeClass$AS(b);for(c=0;c<b.length;++c)(function(a){f.run$SF$V$(a,function(){f[a]()})})(b[c]);null!=f.afterClass$&&f.afterClass$()}};window.addEventListener("load",fc);document.addEventListener("DOMContentLoaded",
fc)})();
